- checks/security_policy.go
Part of doc at
https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository
> Add docs directory for security.md

- cmd/root.go
- pkg/scorecard.go
This will make it easier to add subcommands and to serve the scorecard over HTTP.
> Separate logic from cmd/root.go

- checker/checker.go
- checks/signed_tags.go
- go.mod
- go.sum
- pkg/scorecard.go
> Use the GraphQL API to retrieve the list of tags in signed-tags.

- README.md
- cmd/root.go
This allows the user to specify "--format=csv" to get the results output in CSV columns.
> Add CSV formatting mode.

- README.md
- cmd/root.go
This is usable as is, but is also desigend to be easy to import into a database.
> Add a JSON format mode.

- checks/code_review.go
- checks/pull_requests.go
- checks/security_policy.go
Works now for google repos like
https://github.com/google/boringssl
https://github.com/google/skia
Fixes Code-Review,Pull-Requests checks.
> Update checks for Gerrit use

- checks/security_policy.go
Fixes https://github.com/ossf/scorecard/issues/82
> Allow other accepted variants of security.md case styles.

- checks/sast.go
github-code-scanning slug does not work in custom QL definitions.
And "use: github/codeql-action" can't be detected from runtime
workflow job, but just search in .github/workflows.
Fixes result for envoyproxy/envoy and fixes
https://github.com/ossf/scorecard/issues/93
> Improve SAST check.

- go.mod
- go.sum
- pkg/scorecard.go
- pkg/scorecard_test.go
- Fixes the URL with a trailing slash #99 
- Changed the URL parsing to net package implementation.
- Included tests for URL parsing.
> fix - URL with trailing slash

- cron/cron.sh
Fixed the `shellcheck` violations in `cron.sh`
> fix - shellcheck violations for cron.sh

- .github/workflows/golangci-lint.yml
- .github/workflows/main.yml
- .gitignore
- Makefile
Implemented Makefile and actions for PR and push to validate fmt, go mod
tidy , go build and go test
> Feat - Implemented Makefile and actions for PR

- pkg/scorecard.go
Fix regression from
https://github.com/ossf/scorecard/commit/f7cb4d70e67f7551aa0caf84eca6a0c10919b3c7
> Allow skipping scheme, fix regression.

- cmd/root.go
- cmd/serve.go
Fixed the golangci-lint issues.
> fix - golangci-lint issues

- CONTRIBUTING.md
* Updated the contributing guidelines with Environment Setup, Contributing steps, How to build scorecard locally, What to do before submitting a pull request, and Where the CI Tests are configured.
> feature - Update the CONTRIBUTING guidelines

- Dockerfile
- README.md
- cron/Dockerfile
- Changed the docker container to non-root
- Fixed the hadolint dockerfile warnings.
> feat - nonroot docker container

- README.md
Included the status badge for build, golanglint-ci, and CodeQL.
> feature - Included the status badge in README

- .github/PULL_REQUEST_TEMPLATE.md
This will introduce a template for PR
No standard template for PR.
A standard template for PR.
NA
> feature - Pull request template

- README.md
Included instruction that GITHUB_AUTH_TOKEN supports round-robin with multiple tokens.
N/A
Doc - Updates the README to include instructions for multiple GITHUB_AUTH_TOKEN
N/A
N/A
None
> Document - Included instruction for GITHUB_AUTH_TOKEN

- .github/workflows/stale.yml
NA
Closes stale issues.
Issues are stale which haven't been closed.
Will close/label stale issues
NA
> feat - Close stale issues

- .github/workflows/main.yml
- CONTRIBUTING.md
- e2e/e2e_suite_test.go
Included the e2e into the PR workflows
The current behavior does not run an e2e test before merging the code into main.
The new behavior would run e2e tests prior to merging into main.
It does not.
N/A
> feature - Included the e2e into the PR workflows

- checks/sast.go
It is a random bug, hard to test
Fixed the panic by doing a nil check. fixes #135
Panic's inconsistent. 
No panics.
None
> fix - panic on nil

- .codecov.yml
- .github/workflows/main.yml
- .gitignore
- Makefile
- README.md
N/A
Reports code coverage
Reports code coverage to codecov
NONE
> Feature - Report codecoverage to codecov.io

- checks/branch_protected.go
- e2e/branchprotection_test.go
Bug fix #138 
Reports incorrect result for branch protection
NONE
> Fixes - Incorrect result for branch protection

- README.md
- checks.md
- [NA] Tests for the changes have been added (for bug fixes / features)
Adds remediation steps for various checks.
Missing remediation steps, making hard for developer to fix check failures.
Provides suggestions with links to easily fix failures.
No.
NA
> Add remediation steps for various checks.

- checks/frozen_deps.go
Bug fix
Broken `Frozen-Deps` checks
Fixes the `Frozen-Dep` checks
None
> Fix - tarball URL trailing slash

- README.md
- cmd/root.go
NO
Feature Implemented scans from `npm` package name. fix #33 
NONE
Scorecard can scan based on `npm` packages
NO
> Feature - run scans from npm pacakge name

- .github/dependabot.yml
N/A
Enable dependabot updates for githubactions
None
> Feature - enabled dependabot for githubactions

- .github/dependabot.yml
> Fix - dependabot yaml error

- .github/workflows/docker.yaml
- Dockerfile
N/A
This will release the docker container to the GitHub docker registry.
An example https://github.com/naveensrinivasan/scorecard/packages/613485
The user would have to compile the docker image 
The docker images will be available to pull
None
> Docker releases to the GitHub Docker registry

- .github/workflows/main.yml
Fixes the e2e tests for PR's
The e2e tests fail for PR
> Fix - Fixes the e2e tests for PR's

- .github/workflows/docker.yaml
Bug Fix - docker latest image
Latest tag is not published.
> Fix - docker latest image

- README.md
NA
Includes update to the README 
NONE
> Doc - Update README with the docker image

- checks/signed_tags.go
No
fixes #107
The tag checks fail for lightweight tags and do not iterate through all the tags
The code will iterate through all the tags
None
Here is the analysis https://github.com/ossf/scorecard/issues/107#issuecomment-778345705
> Fixes - verifiedtag checks

- cmd/root.go
No
Fix
The json output had non-json output. Fixed it output only for default output.
None
> Fix - output message for non default output

- checks/packaging.go
- e2e/packaging_test.go
- [x ] Tests for the changes have been added (for bug fixes / features)
Docker push was not identified in the workflow.
Docker push is identified
None
> Fix - pacakging workflow for docker push

- .goreleaser.yml
N/A
Turn's off automatic release notes generation
Generates automatic release notes
goreleaser would generate release without automatic release notes
NONE
> Fix - Turn off automatic releasenotes generation

- .goreleaser.yml
- checks/contributors.go
- e2e/contributors_test.go
Bugfix for Org checks for members
The current check ignores the org the members are in
None
> Fix - Organization checks for members

- .github/workflows/main.yml
- .gitignore
- Makefile
- e2e/executable_test.go
N/A
e2e tests for the executable
Fixed the default output message when json option is chosen
The json output had non-json output. Fixed it output only for default
output.
Included e2e tests for the executable with JSON
> Test - Included e2e test for the executable

- Dockerfile
- Makefile
N/A
Feature static builds
Does not provide static builds
Provide static binaries
None
None
> Fix - go build to static binaries

- cmd/serve.go
Not yet
Feature to serve `json` over HTTP.
Serve's text over HTTP
Server's json over HTTP. Utilize this HTTP endpoint to do `cron` jobs https://github.com/ossf/scorecard/blob/main/cron/projects.txt which would easier to scale.
None
Tests with httpie
```
http --json  http://localhost:8080\?repo\=github.com/ossf/scorecard
{
"Checks": [
{
"CheckName": "SAST", …
```
> Feature - Serve json response in http

- .github/workflows/golangci-lint.yml
- .golangci.yml
- Makefile
N/A
Linting #173 
It does not have additional lighters enabled.
Feature - Include additional linters for golangci. This is settings is based on https://github.com/kubernetes-sigs/security-profiles-operator/blob/master/.golangci.yml
None
> Feature - Include additional linters for golangci

- .github/workflows/golangci-lint.yml
No
Bug fix
golangci reporting old issues
golanglint-ci report only new issues
no
> Fix - golanglint-ci report only new issues

- .github/workflows/main.yml
N/A
Bugfix
The empty GitHub token is failing with not able to run e2e
It should not fail if the GitHub token is empty.
None
> Fix - ignore empty github token

- k8s/cron.yaml
The cron runs every day right now
The cron will only run twice a week. We added more projects than we can scan in one day.
> Slow down to every few days.

- CONTRIBUTING.md
- README.md
> Update contributing instructions and readme

- .gitignore
- Makefile
- checker/check.go
- checks/active.go
- checks/branch_protected.go
- checks/ci_tests.go
- checks/cii_best_practices.go
- checks/code_review.go
- checks/contributors.go
- checks/frozen_deps.go
- checks/fuzzing.go
- checks/packaging.go
- checks/sast.go
- checks/security_policy.go
- cmd/root.go
- cmd/serve.go
- pkg/scorecard.go
NA
Bug fix
Addressed golangci issues #173 
Fixed the golangci issues for `gomnd` and `goconst`.
Added `ginkgo` dependency in the `makefile`.
NA
Have not fixed all golangci issues just `gomnd` and `goconst`. Planning to address the others in next few PR's.
> Fix - golangci issues gomnd, goconst

- e2e/executable_test.go
Bug fix
The score of the scorecard is improving with signed-release and updating
the tests to reflect that.
None
> Fix - Changes to reflect the scorecard score

- .github/workflows/integration.yml
- .github/workflows/ok-to-test.yml
N/A
Ok-to-test via github action based on this https://github.com/imjohnbo/ok-to-test
No e2e tests run for PR merges for forks
Runs e2e in PR for git forks
None
> Feature - ok-to-test in github action

- .github/workflows/ok-to-test.yml
Bugfix
The slash command was looking for an app. Removed that to use just use Personal Token
> Fix - Remove the app reference for the slash token

- .github/workflows/main.yml
- Makefile
- hack/tree-status
N/A
Clean up
Adds new functionality to git status, help for the make file, and cleans up the GitHub action.
None
> Fix - Cleanup the makefile targets

- CONTRIBUTING.md
> Doc - Update contributing to reflect changes

- Makefile
- go.mod
- roundtripper/roundtripper.go
Bugfix
The default disk cache size is 100MB.
The default disk cache size is 100MB. Changed the default disk cache to 10GB.
None
> Fix - default disk cache size

- .github/dependabot.yml
N/A
Other
Does not have dependabot for docker
Dependabot for docker.
None
> Feat- Included dependabot for docker

- README.md
N/A
fixes #212 
Updated the README with TOC and included instructions for docker usage.
None
> Doc - Update README with the TOC

- .Dockerignore
- .github/workflows/integration.yml
- Makefile
N/A
Feature
Docker does not have e2e tests, #217 
1. Included e2e tests for docker.
2. Included`.Dockerignore` to ignore files.
3. Included Docker builds in the Makefile.
None
> Feature - Include e2e tests for docker

- .github/workflows/integration.yml
- .gitignore
- Makefile
- e2e/executable_test.go
- go.sum
Clean up
Fix - Output path for the test runs
None
> Fix - Output path for the test runs

- .github/workflows/integration.yml
- Makefile
- e2e/branchprotection_test.go
- e2e/diskcache_test.go
Tests for disk cache.
Not many tests for disk cache.
Included tests for disk cache.
Cleaned up tests.
None
> feat - Included tests for disk cache

- gitcache/README.md
N/A
Docs
Docs weren't updated.
Updated README to reflect the changes that are implemented.
None
> Updated README

- .github/dependabot.yml
N/A
Feature 
Does not have dependency checks for gitcache
Included dependabot for gitcache
None
> Feat - Included dependabot for gitcache

- gitcache/Makefile
- gitcache/e2e/e2e_test.go
- gitcache/pkg/blob.go
Tests
There aren't e2e tests for buckets
Implemented e2e tests for buckets.
None
None
> Feat - e2e tests for gitcache buckets

- .github/workflows/integration.yml
- Dockerfile.gsutil
- Makefile
N/A
Bug fix
Docker builds are broken for scorecard cron.
Fixed the docker build for scorecard cron and as well as updated the
integration to test for the docker builds.
None
> docker builds for scorecard cron

- gitcache/k8s/README.md
- gitcache/k8s/deployment.yaml
- gitcache/k8s/namespace.yaml
- gitcache/main.go
N/A
Feature
gitcache isn't deployed in k8s
Deployment of gitcache within k8s
None
> feat - k8s deployment

- gitcache/k8s/deployment.yaml
- gitcache/main.go
- gitcache/pkg/service.go
NA
Feature
* Included security context to runas nonroot
* Turned off privilege escalation
* Implemented readOnly RootFilesystem
* Implemented readiness and livenessprobe for the container
None
None
> Feat - configure k8s deployment to be non-root

- k8s/cron.yaml
N/A
Feature
The cron does not have blob based caching. Fixes #216
Included caching settings for the cron job.
None
None
> Fix - cron included caching settings

- e2e/signedtags_test.go
BugFix
The signed tags e2e tests were failing because apache/airflow pushed tags without signing.
Changed from apache/airflow to bitcoin/bitcoin.
None
None
> Fix - signed-tags e2e tests.

- k8s/cron.yaml
Tested in on a k8s cluster.
Bugfix.
The yaml wasn't valid.
The `yaml` string was missing quotes.
None
None
> Fix - Yaml string quotes for corn-job

- k8s/cron.yaml
N/A
#265
Set resource limits for the cron job pod.
None
None
> Fix - Set resource limits for the cron pod

- README.md
N/A
Docs update
The default README does not have link to gitcache.
Included documentation for gitcache.
None
None
> Doc - Included gitcache documentation

- .github/workflows/synk-cron.yaml
N/A
Feature
The cron-job.yaml wasn't checked for security issues.
Use synk to check for cron-job yaml for secuity misconfiguration.
None
None
> Feat-Use synk to check cron-job security settings

- CONTRIBUTING.md
- README.md
N/A
Docs
#277
Included a section within the CONTRIBUTING.md about the dailyscore and cron job.
None
None
> Docs - Updated the docs for cron

- CONTRIBUTING.md
N/A
Docs
Didn't have instructions for deployment of cron job.
Included instructions for deployment of the k8s cron job for the daily score.
None
None
> Docs - Included instructions for deploying cron

- pkg/scorecard.go
- roundtripper/roundtripper.go
```
➜  scorecard git:(feat/play-with-headers) ✗ ./scorecard  --repo=github.com/ossf/scorecard
Starting [Active]
Starting [Branch-Protection]
Starting [CI-Tests]
Starting [CII-Best-Practices]
Starting [Code-Review]
Starting [Contributors]
Starting [Frozen-Deps]
Starting [Fuzzing]
Starting [Packaging]
Starting [Pull-Requests]
Starting [SAST]
Starting [Security-Policy]
Starting [Signed-Releases]
Starting [Signed-Tags]
{"level":"info","ts":1616011689.6091163,"caller":"roundtripper/roundtripper.go:63","msg":"using token 1 and the len of the tokens are 2 and in the c is 1"}
{"level":"info","ts":1616011689.6918664,"caller":"roundtripper/roundtripper.go:63","msg":"using token 0 and the len of the tokens are 2 and in the c is 2"} …
```
> Fix-Using Roundrobin tokens across multiple calls

- roundtripper/roundtripper.go
N/A
chore
The roundtripper logs are flooding the cron job.
Remove the debug log for the roundtripper which is flooding.
None
None
> chore - remove debug log for roundtripper

- .github/workflows/verify.yml
None
Feature
The current release notes generation is a manual process. We want to avoid that as much as possible.
The verifier helps release notes generation.
https://github.com/kubernetes-sigs/kubebuilder-release-tools
https://github.com/kubernetes-sigs/kubebuilder-release-tools/blob/master/verify/main.go
None
None
> :seedling: verifier to generate release notes

- cron/cron.sh
Manually tested the cron.
Bug fix
The branch-protection check runs for every repository from cron
The branch protection check needs an admin access to the repository. All
of the checks from cron would fail and uses another call to the API.
This will reduce usage of the API.
None
None
> :seedling:Remove branch protection check from cron

- k8s/cron.yaml
No
Feature
Cron does not run everyday
With the latest fix for roundrobin token usage, the cron can run everyday.
None
None
> :seedling: Changed cron to run everyday

- CONTRIBUTING.md
N/A
Doc
The CONTRIBUTING.md didn't have docs for the new PR process.
* Included instructions in the PR process.
N/A
N/A
> :book: Instructions on PR process

- .gitignore
- Makefile
NA
Feature
Updated the makefile to include scripts and cron.
None
None
> :seedling: updated the makefile to include scripts and cron

- .github/dependabot.yml
N/A
Feature
The cron and scripts are based on go.mod. The dependabot settings are updated to watch those folders.
N/A
N/A
> :seedling: update dependabot for cron and scripts

- .github/PULL_REQUEST_TEMPLATE.md
N/A
Docs
Does not have reference to the PR Process
Included the reference to the PR process
None
None
> :book: Update PULL_REQUEST_TEMPLATE.md

- Dockerfile
Bug fix
Docker builds aren't working from with the experimental syntax.
The docker build syntax was in an incorrect location which was causing the builds to fail.
https://github.com/docker/buildx/issues/348#issuecomment-709155842
None
None
> :bug: Fix docker buildx syntax

- Dockerfile
- Dockerfile.gsutil
Feature
Upgrade docker container.
Golang docker container upgrade.
None
None
> :seedling: Upgrade golang docker container

- checker/checker.go
> :bug:dont retry and log http get failures.

- .github/dependabot.yml
Feature
* Updated commit message to have :seedling: prefix in dependabot PR.
None
None
> :seedling: Updated commit message for dependabot

- k8s/cron.yaml
Bug
Multiple cronjobs werer running and slowing down because of use of the same GitHUb Tokens
* With the increased scans the cronjob is running longer than expected  which was causing the multiple jobs to be executing concurrently.
* Changed the concurrent policy to "Forbid" to avoid it.
None
None
> :seedling: Fix concurrent cronjob execution

- .github/workflows/codescan.yml
- .github/workflows/docker.yaml
- Makefile
- gitcache/Makefile
Bug fix
#358
Fixes the docker build kit issue
None
None
> :seedling: Fixing the docker build issue

- cron/main.go
Feature
Lint issues in cron
* Fixed golang ci-lint issues in cron
None
None
> :seedling: Fixed lint issues in cron

- .github/workflows/gitcache-docker.yaml
Bug fix
Docker builds are broken for git cache
* Fixed docker build for git cache
None
None
> :bug: docker build for gitcache

- Makefile
Chore
The cron and the scripts didn't have mod verify
* Included go mod verify cron and scripts
None
None
> :seedling: Included go mod verify for cron and scripts

- cmd/root.go
- cmd/serve.go
- go.mod
- go.sum
- pkg/scorecard.go
- repos/repo_result.go
Bug fix
Scorecard JSON output has CheckResults field name which mismatches with BQ schema.
Rename CheckResults to Checks.
> 🐛  Rename CheckResults to Checks to match BQ schema.

- cron/main.go
Bug fix
* Included validation for the cron
* Removed branch protection check from the cron
None
None
> :seedling: Clean and Validation of cron

- .github/dependabot.yml
> :seedling: Cleanup dependabot config

- .gitignore
- Makefile
- e2e/cron-projects.txt
- e2e/cron_test.go
Test for cronjob
No tests for cron job
* Implemented basic e2e tests for cornjob
None
None
> :seedling: e2e tests for cronjob

- checks/code_review.go
This PR fixes issues from the [godot](https://github.com/tetafro/godot) linter (top level declaration comments should end in a period).
n/a
No
> :bug: Fix lint issues: godot linter

- checks/ci_tests.go
- checks/packaging.go
- checks/pull_requests.go
- checks/sast.go
This PR fixes issues from the lll linter ((lines are not longer than 120 characters)).
n/a
No
> :bug: Fix lint issues: lll linter

- checks/branch_protected.go
This PR fixes issues from the [nestif](https://github.com/nakabonne/nestif) linter (reports deeply nested if statements).
n/a
No
> :bug: Fix lint issues: nestif linter

- cmd/root.go
This PR fixes issues from the [ineffassign](https://github.com/gordonklaus/ineffassign) linter (detects when assignments to existing variables are not used).
n/a
No
> :bug: Fix lint issues: ineffassign linter

- checks/cii_best_practices.go
This PR fixes issues from the [noctx](https://github.com/sonatard/noctx) linter (finds sending http request without context.Context).
n/a
No
> :bug: Fix lint issues: noctx linter

- checks/branch_protected_test.go
- e2e/e2e_suite_test.go
This PR fixes issues from the [gofumpt](https://github.com/mvdan/gofumpt) linter (various style rules).
n/a
No
> :bug: Fix lint issues: gofumpt linter

- checker/check_request.go
- checks/cii_best_practices.go
- cmd/root.go
- cron/main.go
- e2e/active_test.go
- e2e/branchprotection_test.go
- e2e/ci_tests_test.go
- e2e/cii_best_practices_test.go
- e2e/code_review_test.go
- e2e/contributors_test.go
- e2e/frozen_deps_test.go
- e2e/fuzzing_test.go
- e2e/packaging_test.go
- e2e/pull_requests_test.go
- e2e/sast_test.go
- e2e/security_policy_test.go
- e2e/signedreleases_test.go
- e2e/signedtags_test.go
- pkg/scorecard.go
- repos/repo_url.go
- repos/repo_url_test.go
This PR fixes issues from the [golint](https://github.com/golang/lint) linter (various style rules).
n/a
No
I figured I should start signing my commits. It was nice to see the process to set that up wasn't too difficult.\
Part of issue …
> 🌱 Fix lint issues: golint linter

- checks/checks.md
- checks/checks.yaml
Docs
#350
* Included need for admin access to the branch protection api to work.
None
None
> 📖  Update branch protection API

- checks/code_review.go
**Please check if the PR fulfills these requirements**
Bug fix for #415 
See #415 , the code segfaults.
The new behavior does not crash.
no
> 🐛 Fix segfault in request-review check

- .github/workflows/codescan.yml
- .github/workflows/integration.yml
This is a patch fix.
We currently don't pin dependencies #412 
We pin dependencies in the workflow.
no
> 🐛  Pin workflow dependencies

- repos/repo_url.go
Removes log.fatal to instead return error.
Fatal failure on callee side instead letting caller decide behaviour.
Caller decides bahviour on failure.
No.
> 🌱 Return error instead of log.fatal.

- repos/repo_url.go
This PR fixes issues from the [gocritic](https://github.com/go-critic/go-critic/) linter (various bugs, performance and style checks).\
n/a
No
> 🌱 Fix lint issues: gocritic linter

- e2e/contributors_test.go
- e2e/packaging_test.go
This PR fixes issues from the [dupl](https://github.com/mibk/dupl/) linter (checks for duplicate code). \
n/a
No
> 🌱 Fix lint issues: dupl linter

- checks/contributors.go
This PR fixes issues from the [nolintlint](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/nolintlint/README.md) linter (checks for ineffective `//nolint` directive). \
n/a
No …
> 🌱 Fix lint issues: nolintlint linter

- checks/branch_protected.go
- checks/ci_tests.go
This PR fixes issues from the [gocognit](https://github.com/uudashr/gocognit/) linter (checks that functions do not have high cognitive complexity). \
n/a
No
> 🌱 Fix lint issues: gocognit linter

- .github/workflows/codeql-analysis.yml
- .github/workflows/gitcache-docker.yaml
- .github/workflows/goreleaser.yaml
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .github/workflows/ok-to-test.yml
- .github/workflows/stale.yml
- .github/workflows/verify.yml
bug
we don't pin our workflow actions by hash
we pin our workflow actions by hash
no
This way we can use scorecard for our e2e tests for the frozen-deps check.
> :seedling: Pin scorecard workflow dependencies by hash

- cron/config/config.go
- cron/config/config.yaml
- cron/config/config_test.go
- cron/config/testdata/basic.yaml
- cron/config/testdata/missing_field.yaml
- cron/controller/main.go
Uses config.yaml instead of config.go for setting PubSub job vars.
No
> 🌱  Add and use config.yaml for pubsub cron.

- Makefile
https://github.com/ossf/scorecard/issues/454
Manually generate docs
Implemented checks for auto generating docs.
None
None
> :seedling: auto generate docs

- .gitignore
- Makefile
- cron/config/config.go
- cron/config/config.yaml
- cron/config/config_test.go
- cron/pubsub/subscriber.go
- cron/pubsub/subscriber_test.go
- cron/worker/main.go
Adds the subscriber/worker logic to the Pubsub cron job setup.
No.
> ✨  Add worker to the PubSub framework.

- Makefile
- cron/controller/Dockerfile
- cron/worker/Dockerfile
Adds Dockerfiles for PubSub controller/worker. No behaviour change.
No.
> 🌱  Add Dockerfiles for PubSub batch job

- roundtripper/cache.go
- roundtripper/oauth.go
- roundtripper/rate_limit.go
- roundtripper/roundtripper.go
Refactoring only, no behaviour change.
No.
> 🌱  Refactor roundtripper code

- cron/controller/Dockerfile
- cron/worker/Dockerfile
Use the right image/dependencies for PubSub Dockerfile. No behavior change.
No.
> 🐛  Update Dockerfile dependencies for PubSub job

- .golangci.yml
- checks/frozen_deps.go
This PR fixes issues from the [govet](https://golang.org/cmd/vet/) linter. With current settings, the only checks enabled are for field alignment and invalid struct field tags. The `fieldalignment` check will look for structs that could take up less memory if the fields are re-ordered. \
Part of issue #173.
n/a
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …
> 🌱 Fix lint issues: govet linter

- checks/frozen_deps.go
- checks/testdata/Dockerfile-pinned
- checks/testdata/Dockerfile-pinned-as
bug fix
we don't ignore the "scratch" image
we ignore the "scratch" image
no
> :sparkles: Ignore scratch from dockerfile imports

- checker/check_runner.go
- cron/main.go
- cron/monitoring/exporter.go
- go.mod
- go.sum
- pkg/scorecard.go
- stats/measures.go
- stats/tags.go
- stats/views.go
Adds monitoring support to daily cron job.
No monitoring.
Logs per-repo per-check runtime statistics to Google Cloud StackDriver.
No.
> ✨  Add monitoring to checks

- checks/checkforcontent.go
- checks/frozen_deps.go
bug fix
we don't ignore test files.
we ignore test files.
no
> ✨  [Frozen-deps]: Ignore testdata/ files

- cron/main.go
- cron/monitoring/exporter.go
- roundtripper/census.go
- roundtripper/rate_limit.go
- roundtripper/roundtripper.go
- stats/measures.go
- stats/tags.go
- stats/views.go
> Add HTTP stats

- checker/check_runner.go
- roundtripper/census.go
Bug fixes in stat collection:
i) Context was not being passed down to checks for making HTTP requests.
ii) ochttp.Transport must be the outmost Transport layer for the log collection to work right.
No.
> 🐛 Fix bugs in stat collection logic

- .golangci.yml
- checks/checkforfile.go
- stats/views.go
This PR fixes issues from the [gomnd](https://github.com/tommy-muehle/go-mnd) linter (checks for magic numbers). \
Part of issue #173.
n/a
No
> 🌱 Fix lint issues: gomnd linter

- .golangci.yml
- CONTRIBUTING.md
- checks/active.go
- checks/branch_protected.go
- checks/ci_tests.go
- checks/cii_best_practices.go
- checks/code_review.go
- checks/contributors.go
- checks/frozen_deps.go
- checks/fuzzing.go
- checks/packaging.go
- checks/pull_requests.go
- checks/sast.go
- checks/security_policy.go
- checks/signed_releases.go
- checks/signed_tags.go
- cmd/root.go
- cmd/serve.go
- main.go
This PR fixes issues from the [gochecknoinits](https://github.com/leighmcculloch/gochecknoinits/) linter (checks that init functions are not used). As discussed in #173, we're going to leave the `init` calls as opposed to refactoring how checks are registered.
n/a
No
> 🌱Fix lint issues: gochecknoinits linter

- .golangci.yml
- checks/security_policy.go
This PR fixes issues from the [lll](https://golangci-lint.run/usage/linters/#lll) linter (checks that lines are under 120 characters). \
Part of issue #173.
n/a
No
> 🌱 Fix lint issues: lll linter

- .golangci.yml
- checks/checkforcontent.go
- checks/frozen_deps.go
This PR fixes issues from the [stylecheck](https://github.com/dominikh/go-tools/tree/master/stylecheck) linter (various style checks). \
Part of issue #173.
n/a
No
> 🌱 Fix lint issues: stylecheck linter

- .golangci.yml
- checker/check_result.go
- checks/code_review.go
- checks/sast.go
- checks/signed_releases.go
- checks/signed_tags.go
This PR fixes issues from the [goerr113](https://github.com/Djarvur/go-err113/) linter (checks error handling expressions). \
Part of issue #173
n/a
No
> 🌱 Fix lint issues: goerr113 linter

- cron/k8s/controller.yaml
- cron/k8s/worker.yaml
Adds k8s file for PubSub jobs - controller & worker.
No.
> ✨ Add k8s file for PubSub jobs

- cron/monitoring/exporter.go
Fix the resource exceeded errors showing up for Stackdriver: 
No.
> 🐛  Limit number of batched data points in Stackdriver

- cron/config/config.yaml
- cron/config/config_test.go
- cron/k8s/controller.yaml
- cron/k8s/worker.yaml
- cron/worker/main.go
i) Reduce shard_size to 10 so that subscriber request runs are faster
ii) Increase the shard filename padding from `%03d` -> `%05d`
iii) Change the frequency of the controller job to run `every Sunday night`. We'll be increasing the number of repos, so decreasing the frequency at which run the job.
iv) Remove/reduce the CPU/memory requirements from worker job. These resources seem to be unavailable in the deployment, so removing this for now to unblock myself from testing. Will look into adding these resource numbers in the future.
v) Change the GitHub token field key to read from.
* **Does this PR introduce a breaking change?** (What changes …
> 🐛  Cleanup PubSub deployment

- cron/controller/Dockerfile
- cron/worker/Dockerfile
Without the leading `./`, job fails with `no such file` error.
No.
> 🐛  Fix bug in Dockerfile

- cron/controller/main.go
Fixes off-by-one error in shardNum. shardNum is 0-indexed, so when writing to file we increment it by 1.
No.
> 🐛  Off-by-one error in shardNum

- cron/worker/main.go
i) Adds more logs to the PubSub worker for better debuggability.
ii) Removes parallelism during repo runs. Threads are stuck indefinitely, will debug and fix this later. Removing it for now to unblock myself.
No.
> 🐛  Bug fixes and additional logs for PubSub worker

- checks/checkforcontent.go
- checks/frozen_deps.go
enhancement
change some error message to disambiguate between frozen-deps sub checks
no
> ✨ Feat/deps msg

- cron/worker/main.go
Adds metric monitoring to PubSub cron.
No
> ✨ Add metric monitoring support to PubSub cron

- cron/k8s/cron.yaml
- cron/k8s/worker.yaml
Exchange the GitHub tokens used for PubSub cron job with the daily cron job. 
No.
> ✨ Use prod tokens for the PubSub cron

- cron/pubsub/subscriber.go
- cron/pubsub/subscriber_gcs.go
- cron/pubsub/subscriber_gocloud.go
- cron/pubsub/subscriber_gocloud_test.go
- cron/worker/main.go
- go.mod
Use lease extension in PubSub cron worker.
No.
> ✨  Use lease extension for PubSub worker

- cron/pubsub/subscriber_gcs.go
Poll PubSub worker until a message is received. Without this the worker keeps restarting until a message is received.
No.
> 🐛 Poll Pubsub worker until message is received

- checks/permissions.go
cleanup
the same.
the same.
no
This addresses some comments I missed before merging, see #534
> ✨ Cleanup code for github tokens #534

- README.md
correct path to the file that lists the projects checked each night
> 📖  Fixed the path projects.txt

- checks/checks.md
Doc
Fixed the docs for automatic checks for dependency
None
None
> :book: Fix the docs for Automatic checks for dependency

- checks/checks.md
- checks/checks.yaml
docs update
no remediation steps for github workflows and dockerfiles.
* remediation steps for github workflows and dockerfiles.
no
> ✨ Update frozen dep doc

- README.md
Doc
Included slack channel
Included bi-weekly meeting link
None
None
> :book: Updated README with community content

- .github/workflows/ok-to-test.yml
- .github/workflows/verify.yml
Bug fix
#432
Allowed write permissions to action for commenting on the status of the PR.
None
None
> 🌱 Allows write permissions for actions

- checks/checks.md
- checks/checks.yaml
- checks/permissions.go
cleanup of code/doc
fix doc and remove loop in code since we only check the 'permissions' one.
no
> ✨ cleanup for token doc and code

- cron/data/blob.go
- cron/k8s/worker.yaml
- cron/worker/main.go
Fixes 2 issues with the PubSub worker:
i) increases memory and CPU limits
ii) early return if shard already exists (temporary solution to overcome https://github.com/ossf/scorecard/issues/549)
No
> 🐛 Fix issues with PubSub worker

- checker/check_runner.go
- cron/monitoring/exporter.go
- cron/worker/main.go
- stats/tags.go
- stats/views.go
To reduce the number of `too many time series` errors from Stackdriver:
i) Ensure that Stackdriver logs are updated at the end of every request.
ii) Reduce the cardinality of the metrics by not logging `Repo` and 'HttpPath' as labels.
No.
> 🐛  Reduce cardinality of OpenCensus stats

- checker/check_runner.go
- cron/monitoring/exporter.go
- pkg/scorecard.go
- stats/measures.go
- stats/tags.go
- stats/views.go
> ✨  Add per-repo CPU stats

- cron/worker/main.go
Registers RepoRuntime View in the PubSub worker. Forgot to do this in #562 
No.
> ✨ Register RepoRuntime View in PubSub worker.

- .github/workflows/verify.yml
Bug Fix
Fixes the PR verifier. This was broken with the permissions fix. I will be addressing that in future PR
None
None
> :seedling: Fixes the broken PR Verifier

- cron/k8s/controller.yaml
Cron job gets kicked-off during the weekend (on Saturday 7pm PST). Update this to instead start during Sunday night (PST time), when are folks are online to monitor the job. 
No.
> ✨  Update cron job schedule

- cron/worker/main.go
Adds CPU profile tracking to Cron worker.
No.
> ✨ Add CPU profile to cron worker

- cron/k8s/worker.yaml
Adds `RollingUpdate` strategy to cron worker job to allow for auto updates.
No.
> ✨ Use RollingUpdate strategy for cron worker job

- .gitignore
- Makefile
- cron/bq/Dockerfile
- cron/bq/main.go
- cron/bq/transfer.go
- cron/config/config.go
- cron/data/blob.go
- cron/data/blob_test.go
- cron/k8s/transfer.yaml
Adds a new data transfer service which runs as a Cron job to transfer GCS data to BQ.
No.
> ✨  Add a BQ data transfer cron job

- cron/worker/main.go
Use continuous pprof for monitoring runtime profiles instead of writing to blob store all the time.
No.
> ✨  Continous pprof for monitoring runtime profiles

- roundtripper/cache.go
- roundtripper/census.go
- roundtripper/rate_limit.go
Use `X-From-Cache` header to recognize if the request was returned from cache. Use this to log Stackdriver stats.
No.
> 🐛  Update how we record cached requests

- README.md
- roundtripper/README.md
Updates existing documentation.
> ✨  Update documentation

- checks/checkforcontent.go
- checks/checkforfile.go
- clients/githubrepo/client.go
- clients/repo_client.go
- cmd/root.go
- cmd/serve.go
- cron/worker/main.go
- pkg/scorecard.go
Adds [`RepoClient interface`](#462) v0. Also improves upon the performance issues mentioned in #578 
No.
> ✨  Add v0 of RepoClient interface

- checks/checkforcontent.go
- checks/checkforfile.go
- clients/githubrepo/client.go
- clients/repo_client.go
Fixes OOM-ing issues of PubSub cron by writing Repo tarball to file instead of memory.
No.
> 🐛 Fix cron worker OOM-ing

- pkg/scorecard.go
> 🐛 Check error type instead of value

- checks/checks.md
- cmd/root.go
- cmd/serve.go
- cron/worker/main.go
- pkg/scorecard.go
Add error handling to RunScorecard fn instead of panicking.
No.
> ✨ Add error handling to RunScorecard fn

- .gitignore
- checks/automatic_dependency_update.go
- checks/binary_artifact.go
- checks/checks.md
- checks/checks.yaml
- go.mod
- go.sum
Feature
#400
* Implemented binary artifact checks
* Didn't include the filetype check as it requires extracting of the 
tarball and getting the file content which is a larger effort.
None
None
> ✨  Binary Artifact check

- checker/check_result.go
- checker/check_runner.go
- cron/worker/main.go
- errors/names.go
- errors/types.go
- stats/measures.go
- stats/views.go
Adds monitoring for Scorecard errors.
No.
> ✨ Add monitoring for Scorecard errors

- clients/githubrepo/client.go
bug fix
addresses https://github.com/ossf/scorecard/pull/598#discussion_r656479064
addresses https://github.com/ossf/scorecard/pull/598#discussion_r656479064
no
> 🐛  Comments

- checks/frozen_deps.go
- checks/frozen_deps_test.go
- checks/shell_download_validate.go
- checks/testdata/Dockerfile-aws-file
- checks/testdata/Dockerfile-curl-file-sh
- checks/testdata/Dockerfile-curl-sh
- checks/testdata/Dockerfile-gsutil-file
- checks/testdata/Dockerfile-proc-subs
- checks/testdata/Dockerfile-wget-bin-sh
- checks/testdata/Dockerfile-wget-file
feature
no support. see https://github.com/ossf/scorecard/pull/584#discussion_r656312099
Support for `bash -c "CMD"` in docker `RUN`. see https://github.com/ossf/scorecard/pull/584#discussion_r656312099
no
> ✨ Support bash -c "CMD" for docker RUN downloads-then-exec

- checks/frozen_deps.go
- checks/frozen_deps_test.go
- checks/shell_download_validate.go
- checks/testdata/Dockerfile-pkg-managers
feature
no support
check for `go install/get pkname` where `pkgname` is not pinned
check for `pip install` where there's no `-r requirements.txt`
> ✨  Support for package manager's unpinned downloads

- checks/binary_artifact.go
feature
no support
we support
no
> ✨ Add .whl to list of binary artifact extensions

- README.md
> 📖   Removed Code Coverage badge

- checks/code_review.go
Use the GraphQL API instead of REST API for CodeReview checks. This reduced outgoing HTTP requests and GitHub token usage.
No.
> ✨ Use GraphQL to reduce token usage in CodeReview

- clients/githubrepo/client.go
bug
we log an error
we don't log the symlink error type. Fixes https://github.com/ossf/scorecard/issues/638
The symlink points to a file in the archive, so we'll catch it anyway. if it's invalid and points somewhere else, then it's malicious and we ignore it as well.
no
> 🐛  Fix unsupported file

- clients/githubrepo/client.go
- clients/githubrepo/client_test.go
Not cleaning `files` list causes performance issues.
No.
> 🐛 Fix bug causing performance issues

- checks/security_policy.go
- e2e/frozen_deps_test.go
- e2e/security_policy_test.go
Feature
Fixes #655
* Included security.rst as name check for security policy.
None
None
> :sparkles: Included security.rst as SecurityPolicy

- clients/githubrepo/stats.go
- clients/githubrepo/transport.go
- cron/worker/main.go
- roundtripper/roundtripper.go
Adds monitoring to track remaining Github REST API tokens.
No.
> ✨ Add monitoring to measure remaining Github tokens

- clients/githubrepo/client.go
- clients/githubrepo/tarball.go
- clients/githubrepo/tarball_test.go
Refactoring to add a tarball handler. Will be adding more types of handlers in the future.
No.
> ✨ Add a tarball handler

- pkg/scorecard_result.go
Feature
#661
* Grouped the output results to pass and fail
* Sorted them by confidence
The output would display like this.
```
RESULTS
-------
Repo: github.com/ossf/scorecard
Pass 10 Active
Pass 10 Automatic-Dependency-Update
Pass 10 Binary-Artifacts
Pass 10 CI-Tests
Pass 9 Code-Review
Pass 10 Contributors
Pass 10 Frozen-Deps
Pass 10 Packaging
Pass 10 Pull-Requests
Pass 10 SAST
Pass 10 Security-Policy
Pass 10 Vulnerabilities
Fail 10 Branch-Protection
Fail 10 CII-Best-Practices
Fail 10 Fuzzing
Fail 3 …
```
> :sparkles: Sorted and grouped the output results

- checks/checks.md
Very minor typos in docs
N/A
N/A (no change in behaviour)
No
> 📖 👻 Minor grammar/readability docs fix

- checks/checks.md
- checks/checks.yaml
- checks/security_policy.go
- cron/pubsub/subscriber_gcs.go
- cron/pubsub/subscriber_gocloud.go
- cron/worker/main.go
> 🐛 Fix some bugs

- clients/githubrepo/tarball.go
Google seems to have moved most of their Github repos. E.g: https://github.com/google/YouCompleteSubl, https://github.com/google-research-datasets/quest/ which causes 404 errors retrieving the tarballs. 
PR changes behaviour to continue processing instead of panic.
> 🐛 Handle 404 status code for GitHub tarball

- checks/frozen_deps_test.go
- checks/shell_download_validate.go
- checks/testdata/Dockerfile-pkg-managers
- checks/testdata/script-pkg-managers
feature
no support
we support
no
There are some false positives (same for `pip install`) if someone genuinely tries to do `pip install *.whl` for `*.whl` for tests. Example: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/builds/docker_cpu_pip.sh#L23
> ✨ Detect python -m pip pkg

- go.mod
- pkg/scorecard_result.go
Feature
Fixes #661
* Included the table output in the default results
```
-------
Repo: github.com/ossf/scorecard
|--------|------------|-----------------------------|
| STATUS | CONFIDENCE |            NAME             |
|--------|------------|-----------------------------|
| Pass   |         10 | Active                      |
|--------|------------|-----------------------------|
| Pass   |         10 | Automatic-Dependency-Update |
|--------|------------|-----------------------------|
| Pass   |         10 | …
```
> :sparkles: Table output for the results

- clients/githubrepo/tarball.go
Some Github repos have `refs` as their default branch (e.g `v1.3.0`, `2.0.0` etc.). When we try to get the tarball for these refs, Github returns a `300` HTTP status. So instead, make the `ref` as empty to let Github return the default branch (https://docs.github.com/en/rest/reference/repos#download-a-repository-archive-tar).
E.g repos which return 300 status - https://api.github.com/repos/cocos2d/cocos2d-objc/tarball/v3.5.0, https://api.github.com/repos/dargullin/icheck/tarball/1.0.3
No.
> 🐛 Handle 300 MultipleChoices HTTP status

- cmd/root.go
> :bug: Log error if GITHUB_AUTH_TOKEN is unset

- checks/checks.md
- checks/checks.yaml
doc update
lack of doc for Packaging check.
doc for Packaging check.
no
> ✨ packaging doc

- checks/checks.md
- checks/checks.yaml
doc update
bad doc.
address comment in https://github.com/ossf/scorecard/pull/703
no
> ✨ Packaging doc v2

- checks/checks.md
- checks/checks.yaml
> ✨  nits in doc

- Makefile
- cron/controller/Dockerfile
- cron/controller/main.go
- cron/data/add/main.go
- cron/data/iterator.go
- cron/data/iterator_test.go
- cron/data/projects.release.csv
- cron/data/testdata/comment.csv
- cron/data/update/dependency.go
- cron/data/update/main.go
- cron/data/validate/main.go
- cron/data/writer.go
Provides a way to run PubSub with a custom file. This allows for using a smaller list of repositories for release testing.  
No.
> ✨ Framework for PubSub release testing 

- roundtripper/roundtripper.go
CensusTransport got mistakenly disabled. Re-enabling it to monitor stats.
No.
> 🐛 Re-enable CensusTransport

- checks/errors.go
bug
missing file in https://github.com/ossf/scorecard/pull/712
add the file
no
> ✨ add errors file missing from previous PR

- checker/check_result.go
- checks/branch_protected.go
- checks/code_review.go
- checks/contributors.go
- checks/packaging.go
- checks/sast.go
- checks/vulnerabilities.go
- e2e/contributors_test.go
- e2e/packaging_test.go
- e2e/sast_test.go
- e2e/vulnerabilities_test.go
feature
no migration to contributors, vulnerabilities and packaging
contributors, vulnerabilities and packaging migrated.
no
I've fixed some error handling I missed during previous PRs
> ✨ [migration to score] 5: contributors, vulnerabilities, packaging and sast

- checks/checks.md
- checks/checks.yaml
- checks/ci_tests.go
- checks/cii_best_practices.go
- checks/code_review.go
- checks/sast.go
- checks/security_policy.go
- e2e/ci_tests_test.go
- e2e/cii_best_practices_test.go
- e2e/e2e_suite_test.go
- e2e/frozen_deps_test.go
- e2e/security_policy_test.go
- pkg/scorecard_result.go
feature
old code for CI-Test, CII Best practices, security policy file
new code for CI-Test, CII Best practices, security policy file
no
> ✨ [migration to score] 7: CI-Test, CII Best practices, security policy file

- checker/check_result.go
- checks/sast.go
- e2e/sast_test.go
cleanup
see https://github.com/ossf/scorecard/issues/737
see https://github.com/ossf/scorecard/issues/737
no
> ✨  sast cleanup

- checker/check_result.go
- checks/checks.md
- checks/checks.yaml
- checks/code_review.go
- e2e/code_review_test.go
fix
see https://github.com/ossf/scorecard/issues/737
see https://github.com/ossf/scorecard/issues/737
no
> ✨ Code-Review cleanup

- checks/code_review.go
- checks/security_policy.go
- clients/githubrepo/client.go
- clients/githubrepo/graphql.go
- clients/repo_client.go
- cmd/root.go
- cmd/serve.go
- cron/worker/main.go
- e2e/automatic_deps_test.go
- e2e/binary_artifacts_test.go
- e2e/ci_tests_test.go
- e2e/code_review_test.go
- e2e/frozen_deps_test.go
- e2e/security_policy_test.go
Adds new APIs for PRs and DefaultBranch
No.
> ✨ Create APIs for MergedPRs and DefaultBranch

- checks/automatic_dependency_update.go
- checks/binary_artifact.go
- checks/checkforcontent.go
- checks/checkforfile.go
- checks/frozen_deps.go
- checks/permissions.go
- checks/security_policy.go
- clients/githubrepo/client.go
- clients/githubrepo/tarball.go
- clients/githubrepo/tarball_test.go
- clients/repo_client.go
ListFiles API now returns error along with filename slice.
No.
> ✨ Update ListFiles API to return error

- cron/data/projects.release.csv
- cron/releasetest/k8s/controller.yaml
Adds more projects to the release test
No.
> ✨ Add more projects to the release test

- e2e/ci_tests_test.go
Bug fix
Broken tests
Fixed the broken tests that was looking for specific number of debug messages
No
No
> :seedling: Fix the broken e2e tests

- checker/check_result.go
- checks/pull_requests.go
bug
see https://github.com/ossf/scorecard/issues/748
fix for https://github.com/ossf/scorecard/issues/748
no
This check is most likely going away https://github.com/ossf/scorecard/issues/731
> ✨  BUG fix divide by 0

- checks/shell_download_validate.go
cleanup
just a code cleanup
just a code cleanup
no
> ✨  frozen-deps cleanup

- checker/check_result.go
- checks/sast.go
cleanup
see https://github.com/ossf/scorecard/pull/755#discussion_r676962217
see https://github.com/ossf/scorecard/pull/755#discussion_r676962217
no
> ✨  rename var

- checks/vulnerabilities.go
> ✨  update text for OSV

- checks/vulnerabilities.go
cleanup
https://github.com/ossf/scorecard/pull/775
https://github.com/ossf/scorecard/pull/775
no
> ✨  update text OSV

- .github/workflows/main.yml
bug
we cannot submit any PRs
disable the check for license header temporarily
no
> ✨ disable license check

- .github/workflows/integration.yml
- Makefile
Disabled e2e tests to unblock PR submission.re change)?**
No.
> 🐛 Disable e2e tests temporarily

- Makefile
- checks/write.md
- docs/checks.md
- docs/checks/checks.yaml
- docs/checks/generate/main.go
- docs/checks/reader.go
- docs/checks/validate/main.go
`checks.md` and `checks.yaml` seem to have gone out of sync with #740. Adding some validation code so that we stay in sync.
No.
> ✨ Add validation for checks.yaml

- checks/file_utils.go
- checks/permissions.go
- checks/permissions_test.go
- checks/testdata/github-workflow-permissions-actions.yaml
- checks/testdata/github-workflow-permissions-contents.yaml
- checks/testdata/github-workflow-permissions-packages.yaml
- checks/testdata/github-workflow-permissions-secevent-deployments.yaml
- checks/testdata/github-workflow-permissions-status-checks.yaml
- e2e/permissions_test.go
feature
see https://github.com/ossf/scorecard/issues/727
see https://github.com/ossf/scorecard/issues/727
> ✨  Make Token-Permission check more granular

- checks/automatic_dependency_update.go
- checks/binary_artifact.go
- checks/file_utils.go
- checks/permissions.go
- checks/pinned_dependencies.go
- checks/security_policy.go
- e2e/binary_artifacts_test.go
cleanup
* **What is the current behavior?** (You can also link to an open issue here) **
signature of file utility functions are not generic
https://github.com/ossf/scorecard/issues/786
migrate other uses of utility function to use the one defined in this commit https://github.com/ossf/scorecard/commit/c48fe4f9edfabf31244472bd6e6371b8e74c9fa1
no
> ✨  change signature of FileIfExist and FileContent

- cmd/root.go
- pkg/scorecard_result.go
feature
score results hidden behind `SCORECARD_V2=1` env variable.
score results by default
no
> ✨  enable score results by default

- cron/releasetest/worker/Dockerfile
- cron/worker/Dockerfile
- cron/worker/main.go
Catch errors of type `ErrScorecardInternal` during release testing. We will continue to ignore these in prod for now, so that the weekly jobs don't break.
No.
> ✨ Catch RuntimeErrors in release testing

- checker/check_result.go
- checks/all_checks.go
- checks/sast.go
- clients/githubrepo/client.go
- cmd/root.go
- cron/bq/main.go
- cron/config/config.go
- cron/controller/main.go
- cron/data/add/main.go
- cron/data/update/main.go
- cron/data/validate/main.go
- docs/checks/reader.go
- errors/types.go
- main.go
- pkg/scorecard.go
- repos/repo_url.go
- roundtripper/roundtripper.go
- stats/views.go
- utests/utlib.go
More linter fixes to be in sync with Google guidelines.
No.
> 🐛 More linter issues

- cron/worker/main.go
> 🐛 Linter fix

- cron/bq/Dockerfile
- cron/bq/main.go
- cron/bq/transfer.go
- cron/releasetest/k8s/transfer.yaml
Add a new BQ transfer job for the e2e release tests.
No.
> ✨ Add a BQ transfer job for release tests

- checks/fuzzing.go
bug
wrong error message Thanks @olivekl for finding this bug!
correct error message
no
> ✨  fix message for fuzzing

- checks/packaging.go
- e2e/packaging_test.go
Uses `ListFiles` and `GetFileContent` APIs for `Packaging` check. Also adds and updates e2e repo.
No.
> ✨ Update `Packaging` check to use new APIs

- README.md
- pkg/scorecard_result.go
bug
broken link in result and doc
fix broken link in result and doc
no
Thanks @olivekl for catching this!
> ✨  broken link to doc

- e2e/signedreleases_test.go
Update tests
Updated the e2e signed releases to the new repository.
None
None
> :seedling: Updated e2e signed releases

- e2e/signedtags_test.go
Update tests
Fixed e2e for signed tags
None
None
> :seedling: Fix the e2e fixes for signedtags

- cron/k8s/controller.yaml
Rollout cron worker everytime cron controller is scheduled.
No.
> ✨ Rollout worker whenever controller starts

- docs/checks.md
- docs/checks/checks.yaml
Docs update
The docs use the wrong file extension
The docs use the correct file extension (as does the implementation already: https://github.com/ossf/scorecard/blob/254f316ce5a2a7da885155a929228e7001ec5619/checks/signed_releases.go#L46).
* **Does this PR introduce a breaking change?**
No
> 📖 Fix minisign file extension example

- clients/githubrepo/tarball.go
If GitHub tarballs are unable to be downloaded, skip those repos.
No.
> 🐛 Handle tarballs that cannot be downloaded.

- checks/pinned_dependencies.go
- e2e/pinned_dependencies_test.go
bug+feature
lack of details when there's no files to check: e.g. no dockerfile -> we still need to display a message
wrong results because result is shared across files
fix the above
no
> ✨  fix/enhance pinned-dependencies

- checks/permissions.go
- checks/permissions_test.go
- e2e/permissions_test.go
- utests/utlib.go
feature
we only look for CodeQl scanning workflow
we also look for externally run CodeQl's results uploaded to sarif db (GHSA)
no
> :sparkles: improve token permission

- clients/githubrepo/tarball.go
Ignore errors while extracting a corrupted tarball.
No.
> 🐛 Ignore errors extracting corrupted tarball

- cron/cloudbuild/controller.yaml
- cron/cloudbuild/transfer.yaml
- cron/cloudbuild/worker.yaml
Add configs for CloudBuild so that every build tags the images with `latest` and `COMMIT_SHA`.
No.
> ✨ Add CloudBuild config for CronJob

- cron/config/config.go
Fix typo `BIQQUERY` -> `BIGQUERY`
No.
> 🐛 Fix typo

- .github/workflows/goreleaser.yaml
- .goreleaser.yml
- Makefile
- scripts/version-ldflags
- shared configuration generation in ./scripts/version-ldflags
Signed-off-by: Appu Goundan <appu@google.com>
fixes #818
> 🐛Also add version info to goreleaser

- .github/workflows/main.yml
- go.mod
- go.sum
Bug Fix
Fixes #767
The license check was updated with the ignore files.
Fixed the issue https://github.com/ossf/scorecard/issues/767
No
No
> :seedling: Implemented ignore for license check

- README.md
> 🐛 Update BQ query in README.md

- .gitignore
- Makefile
- cron/cloudbuild/webhook.release.yaml
- cron/k8s/webhook.release.yaml
- cron/webhook/Dockerfile
- cron/webhook/main.go
- go.mod
- go.sum
Adds a new webhook server which tags docker images as `stable` on successful POST requests.
No.
> ✨ Create a webhook for tagging Docker images

- cron/worker/main.go
Fixes a bug flag parsing in cron worker job.
No.
> 🐛 Fix a bug in flag parsing

- checker/check_runner.go
bug fix
old details is no longer populated so it's missing from json and cron job results.
fix the above
no
> 🐛  populate old details

- checks/ci_tests.go
- checks/sast.go
- clients/githubrepo/graphql.go
- clients/pull_request.go
- e2e/ci_tests_test.go
- e2e/sast_test.go
Use Repoclient API for SAST and CITest checks.
No.
> ✨ Update SAST and CITest with Repoclient API

- Makefile
- checks/signed_releases.go
- clients/githubrepo/client.go
- clients/githubrepo/graphql.go
- clients/release.go
- clients/repo_client.go
- e2e/signedreleases_test.go
Use RepoClient API in `Signed-Releases` check.
No.
> ✨ Update SignedReleases to use RepoClient API

- cron/bq/main.go
- cron/k8s/controller.yaml
- cron/k8s/transfer.release.yaml
- cron/k8s/transfer.yaml
- cron/k8s/webhook.release.yaml
- cron/k8s/worker.yaml
- cron/webhook/main.go
Enables automated testing and tagging of releases.
No.
> ✨ Enable automated e2e testing and releases

- checker/check_request.go
- checks/branch_protection.go
- checks/branch_protection_test.go
- checks/ci_tests.go
- checks/contributors.go
- checks/fuzzing.go
- checks/packaging.go
- checks/sast.go
- clients/githubrepo/client.go
- clients/githubrepo/tarball.go
- cmd/root.go
- cmd/serve.go
- cron/data/update/dependency.go
- cron/worker/main.go
- e2e/e2e_suite_test.go
- go.mod
- go.sum
- pkg/scorecard.go
Update go-github versions across all Scorecard packages.
No.
> 🐛 Update go-github version for consistency

- e2e/contributors_test.go
> 🐛 Fix nil pointer bug

- checks/fuzzing.go
- clients/githubrepo/client.go
- clients/repo_client.go
- clients/search.go
- e2e/fuzzing_test.go
Update Fuzzing check to use RepoClient API.
No.
> ✨ Use RepoClient API for Fuzzing

- checker/check_result.go
- checker/check_runner.go
- pkg/scorecard_result.go
- utests/utlib.go
feature
no sarif support
we add the underlying structure to details
no
> ✨ SARIF 1: add structured detail

- clients/githubrepo/client.go
Nil pointer dereference. Wasn't caught since e2e tests are disabled.
No.
> 🐛 Fix nil pointer dereference bug

- checks/automatic_dependency_update.go
- checks/ci_tests.go
- checks/code_review.go
- checks/contributors.go
- checks/permissions.go
- checks/vulnerabilities.go
feature
no structured details
structured details
no
> ✨ Transition Vulnerabilities, Permissions, CI-Tests, Dependency-Update-Tool, Code-Reviews to structured details

- checks/packaging.go
- checks/permissions.go
- checks/sast.go
- checks/security_policy.go
- checks/signed_releases.go
- pkg/sarif.go
- pkg/testdata/check6.sarif
feature
no structured details
structured details
no
> ✨ Transition Packaging, SAST, Security-policy, Signed-releases check to the new structured detail format

- checks/branch_protection.go
- pkg/scorecard.go
Minor fixes for the `Branch-Protection` check.
No.
> 🐛 Fixes for Branch Protection

- checks/fuzzing.go
Avoids `Init-Repo` which downloads the tarball everytime.
No.
> 🐛 Use singleton pattern for OSS-Fuzz

- .github/workflows/main.yml
- Makefile
Use `arduino/setup-protoc` action to install protoc. Its way faster than doing it ourselves.
Note: if we choose to do protoc installation ourselves in the future, we should simply download the release archive which will have the `protoc` binary.
No.
> 🐛 Use `arduino/setup-protoc` for installing Protoc

- clients/githubrepo/tarball.go
Fixes nil pointer dereference error.
No.
> 🐛 Fix nil ptr dereference

- cron/bq/main.go
- cron/config/config.go
- cron/config/config.yaml
- cron/config/config_test.go
- cron/k8s/transfer.release.yaml
To allow for some shard failures, use a completion threshold instead of equality to start a BQ transfer job.
No.
> 🌱 Use a completion threshold for BQ transfers

- cron/k8s/transfer.release.yaml
> 🐛 Syntax bug in k8s file

- checks/branch_protection.go
- checks/branch_protection_test.go
- checks/signed_releases.go
- clients/githubrepo/client.go
- clients/githubrepo/graphql.go
- clients/githubrepo/releases.go
- clients/release.go
Use `ListReleases` API for BranchProtection check.
No.
> 🌱 Use ListReleases API for BranchProtection check

- checks/signed_releases.go
> 🐛 Use release tag URL for path

- checks/packaging.go
- clients/githubrepo/client.go
- clients/githubrepo/workflows.go
- clients/mockrepo/client.go
- clients/repo_client.go
- clients/workflows.go
Add and use a new RpoClient API for Packaging check.
No.
> 🌱 Use RepoClient API for Packaging check

- cloudbuild/scorecard.yaml
Needed for marking Scorecard docker images as `stable` on a successful release test run.
No.
> 🐛 Add COMMIT_SHA to Scorecard docker image

- cloudbuild/scorecard.yaml
> 🐛 Fix syntax bug in CloudBuild YAML

- Makefile
Increase cron job limit to 100k repos.
No.
> ✨ 100k cron job repos

- clients/githubrepo/branches.go
Bug fix - ListBranches may not return DefaultBranch unless we explicitly add it.
No.
> 🐛 Return DefaultBranch as part of ListBranches

- Makefile
> 📖 Fixed typo reepo to repo

- docs/checks.md
- docs/checks/checks.yaml
Docs
Fixed the deadlink to the documentation
No
No
> :book: Fixed the deadlink to the documentation

- clients/githubrepo/roundtripper/roundtripper.go
- go.mod
- go.sum
Bug fix
* This fixes the JWT finding CVE
None
None
> :seedling: Fix the jwt finding

- cmd/version.go
- pkg/sarif.go
- pkg/scorecard.go
- pkg/scorecard_version.go
bug
version reported in JSON is `x.y.z`
version is `x.y.z`
yes
> ✨ semantic version

- Makefile
Generates check.md in the wrong dir.
No.
> 📖 Bug in Makefile generate-docs

- Makefile
bug
the cron job JSON format reports scorecard version as `unknown`
fix the above
no
> Add version for cron

- checks/dependency_update_tool.go
Docs
Fixes https://github.com/ossf/scorecard/issues/1028
Fixed the dependabot warning message.
No
> :book: Fixed the dependabot check message

- checks/dependency_update_tool.go
> :book: Fixed the docs for dependabot

- cron/k8s/transfer-v2.yaml
- cron/k8s/transfer.release-v2.yaml
bug
not updated
updated with transfer.release.yaml
no
> ✨ Update k8's transfer releasetest-v2

- cron/k8s/transfer.release-v2.yaml
fix bug
https://github.com/ossf/scorecard/pull/1023/files#r710416794
fix https://github.com/ossf/scorecard/pull/1023/files#r710416794
no
> 🐛  fix k8 web hook

- go.mod
- go.sum
Bug Fix
Fixes the issue
https://deps.dev/advisory/OSV/GO-2020-0017?from=%2Fgo%2Fk8s.io%252Fclient-go%2Fv0.0.0-20200207030105-473926661c44
None
None
> :seedling: Fixes GO-2020-0017 OSV

- .golangci.yml
- clients/githubrepo/roundtripper/transport.go
Adds a lock mechanism to ensure a single token isn't used by multiple threads. This is the first step towards developing the `secret server` - https://github.com/ossf/scorecard/issues/318#issuecomment-924159260
Will test the impact of this change on the cron performance and will follow up with another PR which separates out this logic into a different server.
No.
> 🌱 Enforce non-concurrent token usage

- go.mod
- go.sum
Bug Fix
Fixes the reference to version of library that has the fix for GO-2020-0020
https://go.googlesource.com/vulndb/+/refs/heads/master/reports/GO-2020-0020.yaml
None
None
> :seedling: Fix GO-2020-0020

- checks/code_review.go
bug
we show `Gerrit code reviews found for 0 commits out of the last 30 -- score normalized to 0` when no reviews were found
we show  `no reviews found` and we add `Gerrit code reviews found for 0 commits out of the last 30` in the details instead.
no
> 🐛  Update message for Code-Review

- cmd/root.go
- pkg/sarif.go
- pkg/sarif_test.go
- pkg/testdata/check6.sarif
- pkg/testdata/check7.sarif
feature
no per-check thresholds
per-check thresholds
yes
> ✨ Per-check score threshold for SARIF

- checks/code_review.go
Check if the committer login is non-empty before comparing with PR author.
No.
> 🐛 Fix CodeReview bug

- cron/cloudbuild/worker.yaml
CloudBuild does a "shallow" clone of the repository, leading to commands like `git describe` not working as intended. 
No.
> 🐛 Fix GitVersion in cron job

- cmd/root.go
feature
we decide which checks to run from CLI argument `--checks`
we decide which checks to run from CLI argument `--checks` if present, otherwise from policy file if present, otherwise we run them all.
no
> ✨  Take checks from policy file if none are given via `--checks` argument

- README.md
Minor fixes to restructure the README better.
No.
> 📖 Minor fixes to README.md

- Makefile
- cron/controller/Dockerfile
- cron/controller/main.go
Use consistent `-ldflags` and version info across all `go build`s in Scorecard.
No.
> 🌱 Consistent `-ldflags` across `go build`

- .github/workflows/scorecard-analysis.yml
bug
https://github.com/ossf/scorecard/issues/1079
https://github.com/ossf/scorecard/issues/1079
close https://github.com/ossf/scorecard/issues/1079
> 🐛 Fix scorecard config name

- actions/Dockerfile
- actions/entrypoint.sh
- pkg/sarif.go
- pkg/sarif_test.go
- pkg/testdata/check6-bug.sarif
bug
https://github.com/ossf/scorecard/issues/1079
https://github.com/ossf/scorecard/issues/1079
no
close https://github.com/ossf/scorecard/issues/1079
> 🐛 Fix failing GH action

- checks/write.md
Fix broken link: errors/errors.md 
Replace checks/frozen_deps.go with checks/pinned_dependencies.go
Docs update: fix links in response to [Bug #1082](https://github.com/ossf/scorecard/issues/1082)
> 📖 Update write.md

- Makefile
- pkg/scorecard_version.go
- scripts/version-ldflags
Feature
Builds aren't reproducible 
Builds are reproducible
Builds are reproducible
> :seedling: Reproducible go builds

- checks/pinned_dependencies.go
> 🐛 Update unpinned message

- .github/workflows/scorecard-analysis.yml
- actions/Dockerfile
- actions/entrypoint.sh
- pkg/sarif.go
feature
no support for action on PR
prepare for PR code
no
> ✨ Start support for action on PR

- .github/workflows/scorecard-analysis.yml
bug
https://github.com/ossf/scorecard/runs/3750175726?check_suite_focus=true
https://github.com/ossf/scorecard/runs/3750175726?check_suite_focus=true
no
> 🐛  Fix failing action

- .github/workflows/scorecard-analysis.yml
> ✨ Disable GH action dogfooding on PRs

- go.mod
- go.sum
Bug fix
https://deps.dev/advisory/OSV/GO-2020-0008
Updated the DNS library version to address the CVE
None
> :seedling: Updates the DNS library for CVE

- go.mod
- go.sum
Bug fix
This fixes the https://github.com/advisories/GHSA-25xm-hr59-7c27
None
> :seedling:Upgrad xz library to FIX CVE-2021-29482

- Makefile
The checks for OSV ignored a few OSV. These have been fixed and removing them from the ignore list.
None
> :seedling: Remove OSV ignores

- cron/data/update/dependency.go
This regular expression has an unescaped dot before 'com', so it might match more hosts than
expected when used.
This addresses the code scanning alert.
Fixes the unescaped issue
None
> :bug:Incomplete regular expression for hostnames

- cron/config/config.yaml
- cron/config/config_test.go
- cron/k8s/transfer-v2.yaml
feature
name is scorecard2
name is scorecard-v2
no
> ✨ Rename BQ table

- cron/worker/main.go
Disable all monitoring. Context: #1109
> 🌱 Disable RepoRuntime monitoring temporarily

- e2e/binary_artifacts_test.go
Bug Fix
Fixed the broken e2e tests for Binary artifacts.
> :bug: Fix broken e2e tests for Binary Artifacts

- .goreleaser.yml
Reproducible builds were missing the modtime flag and this PR addresses that.
> :seedling: Reproducible builds in goreleaser

- README.md
Included the meeting minutes in the README.
No
Already shared the doc with the google group.
> :book: Included the meeting minutes

- checks/permissions.go
- clients/localdir/client.go
- clients/localdir/client_test.go
- cmd/root.go
- pkg/scorecard.go
This add `--local` option as argument. No breaking changes.
> ✨ Add `--local` option to CLI

- .github/workflows/scorecard-analysis.yml
This PR updates the workflow that runs scorecard by enabling support for pull request events.
No braking changes.
> ✨ Run GitHub actions on pull request events on our repo

- .golangci.yml
- checks/fileparser/errors.go
- checks/fileparser/github_workflow.go
- checks/fileparser/github_workflow_test.go
- checks/permissions.go
- checks/pinned_dependencies.go
- checks/pinned_dependencies_test.go
- checks/testdata/github-workflow-multiple-unpinned-uses.yaml
- go.mod
- go.sum
- [n/a] Tests for the changes have been added (for bug fixes / features)
Refactor
We currently parse Github workflow files manually. This is error prone and increase our maintenance burden.
Part of https://github.com/ossf/scorecard/issues/839
We'll use a 3rd-party library [rhysd/actionlint](https://github.com/rhysd/actionlint) to parse Github workflow files. This has several advantages:
1. Should help prevent bugs where our parsing logic wasn't handling edge cases correctly
2. Enables us to delete a decent …
> 🌱 Using library to parse github workflows

- README.md
- [n/a] Tests for the changes have been added (for bug fixes / features)
Docs update
Per Naveen's suggestion, listing myself as a facilitator
No
> 📖 Adding me (Chris) as facilitator

- Makefile
- checks/maintained.go
- clients/githubrepo/branches.go
- clients/githubrepo/client.go
- clients/githubrepo/copy.go
- clients/githubrepo/graphql.go
- clients/issue.go
- clients/localdir/client.go
- clients/mockrepo/client.go
- clients/repo_client.go
- docs/checks/internal/validate/main.go
- e2e/maintained_test.go
- tools/go.mod
- tools/go.sum
> 🌱 Check for issue activity in Maintained

- e2e/binary_artifacts_test.go
- e2e/branch_protection_test.go
- e2e/ci_tests_test.go
- e2e/code_review_test.go
- e2e/contributors_test.go
- e2e/dependency_update_tool_test.go
- e2e/fuzzing_test.go
- e2e/maintained_test.go
- e2e/packaging_test.go
- e2e/permissions_test.go
- e2e/pinned_dependencies_test.go
- e2e/sast_test.go
- e2e/security_policy_test.go
- e2e/signedreleases_test.go
- e2e/vulnerabilities_test.go
Use `repoClient.Close` to cleanup tar files created by e2e tests. Part of #1264 
No.
> 🌱 Add `repoClient.Close` for all e2e tests

- checks/security_policy.go
close https://github.com/ossf/scorecard/issues/1276
> 🐛 Fixes 404 in Security-Policy check

- .gitignore
- Makefile
- cron/cii/Dockerfile
- cron/cii/main.go
- cron/cloudbuild/cii.yaml
- cron/config/config.go
- cron/config/config_test.go
- cron/k8s/cii.yaml
- cron/webhook/main.go
- e2e/permissions_test.go
New cron job to copy over CII data on a monthly basis. Part of #1240.
No.
> 🌱 Add a cron job to copy CII badges data

- .goreleaser.yml
https://github.com/sigstore/cosign/pull/1053
> :bug: Fix the reproducible builds

- checker/check_request.go
- checks/cii_best_practices.go
- checks/fuzzing.go
- clients/githubrepo/client.go
- cmd/root.go
- cmd/serve.go
- cron/worker/main.go
- docs/checks/internal/validate/main.go
- e2e/fuzzing_test.go
- pkg/scorecard.go
Add OssFuzzRepoClient to CheckRequest. Fixes #1264 and also gives us a way to specify a mock OssFuzzRepo is needed (like in local directory cases).
No.
> 🌱 Add a OssFuzzRepoClient

- checks/dangerous_workflow_test.go
- checks/fileparser/github_workflow.go
- checks/pinned_dependencies.go
More nil-ptr issues. Maybe we need extensive unit tests for these new `actionlint` changes. @chrismcgehee FYI.
No.
> 🐛 Fix more nil-ptr dereferences

- clients/cii_blob_client.go
- cron/k8s/cii.yaml
- Ignore not present filenames.
- Update CII cron to run weekly.
No.
> 🐛 Fix issues with CII client

- go.mod
- go.sum
- tools/go.mod
- tools/go.sum
Fixed some of the dependabot vulnerabilities.
> :seedling: Fix vulnerabilities in dependencies

- .github/workflows/main.yml
- Makefile
Add `make -j` option to improve build times in GitHub workflows.
No.
> 🌱 Add parallelism to improve build times

- .github/workflows/scorecard-analysis.yml
- e2e/branch_protection_test.go
Update action names to satisfy the market place requirements.
Also added an option to share results - currently does nothing, though.
> ✨ Update action names

- checks/license_check.go
- checks/license_check_test.go
- cmd/root.go
- docs/checks/internal/checks.yaml
- e2e/license_check_test.go
close https://github.com/ossf/scorecard/issues/1038
> :sparkles: Presence of license information

- README.md
- docs/checks/internal/checks.yaml
change the risk from high to critical, since the patterns can typically be exploited thru a PR
> ✨ Make dangerous workflow critical

- README.md
see the title. no breaking changes
body is really short so adding this line to have the pre-submit pass.
> ✨  Add license check to README

- checks/branch_protection.go
- checks/branch_protection_test.go
- e2e/branch_protection_test.go
This cleans up the branch protection check and adds additional e2e tests.
It also fixes a bug whereby score would be 10 if none of the branches had branch protection enabled.
> ✨ Cleanup Branch Protection and add e2e tests

- cmd/root.go
Improves `local` option by substituting `CII-Client` and `OssFuzzClient`
No.
> 🌱 Use updated clients for `local`

- docs/checks.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>
> Bug fix
It redirects no wrong page.
It redirect to correct page
Nope
> 🐛  deadlink for security policy

- checks/license_test.go
all in the title. no breaking changes.
> 🐛 Move testsdata of license check into testdata/ folder

- README.md
- docs/checks.md
- docs/checks/internal/checks.yaml
1.Update the Risk of dangerous-workflow 
docs update
#1348  
> Update the Risk of dangerous-workflow

- .github/workflows/stale.yml
The number of issues and PR aren't getting attention and this will help
us with this.
> :seedling: Fix the stale configuration.

- README.md
Add suggestion of which PAT to set;
Add explanation of why authentication is needed;
Clarity the "either-or" options for authentication;
Add link to GH Installations (please confirm link is correct)
Docs update
Closes #1139
> 📖 Clarify Authentication and Token Info in README.md

- .github/workflows/stale.yml
> :seedling: Update stale.yml

- checker/check_result.go
- checks/binary_artifact.go
- checks/dependency_update_tool.go
- checks/evaluation/security_policy.go
- checks/fileparser/listing.go
- checks/license.go
- checks/pinned_dependencies.go
- checks/raw/binary_artifact.go
- checks/raw/common.go
- checks/raw/security_policy.go
- checks/security_policy.go
- docs/checks.md
- docs/checks/internal/validate/main.go
- pkg/json_raw_results.go
PR separates checks from policy for the Security-Policy check.
No breaking changes on output.
> ✨ [DRAFT: RAW]: Security policy support

- checker/check_result.go
- checks/dependency_update_tool.go
- checks/evaluation/binary_artifacts.go
- checks/evaluation/dependency_update_tool.go
- checks/fileparser/listing.go
- checks/raw/dependency_update_tool.go
- e2e/dependency_update_tool_test.go
- pkg/json_raw_results.go
Adds raw results for the Dependency-Update-Tool
Also renamed a few variables.
Output:
```
{
"date": "2021-12-15",
"repo": {
"name": "github.com/ossf/scorecard",
"commit": "46e94eb925191f505856f7673f06efbbf762e2ef"
},
"scorecard": {
"version": "unknown",
"commit": "unknown"
},
"metadata": null,
"results": {
...
"dependency-update-tools": [
{
"name": "Dependabot",
"url": "https://github.com/dependabot",
"desc": "Automated dependency updates built into GitHub",
"file": {
"path": ".github/dependabot.yml",
"offset": 1
}
}
]
}
}
```
> ✨ [RAW]: dependency update tool

- .github/workflows/integration.yml
> :seedling: Improves the ci-e2e with retries

- .github/workflows/integration.yml
Fixes the failing workflow. Follow-up of #1386 
No.
> 🐛 Fix retry workflow

- checker/check_result.go
- checker/check_runner.go
- checker/detail_logger.go
- checker/detail_logger_impl.go
- checker/raw_result.go
- cmd/root.go
Basic refactoring to improve readability.
No.
> 🌱 Refactor to improve readability

- .github/workflows/integration.yml
> 🐛 Fix more retry breakages

- .github/workflows/integration.yml
Fixes breaking e2e tests. Again :( 
Hopefully no more.
> 🐛 Update timeout for retries

- checks/evaluation/binary_artifacts.go
- e2e/binary_artifacts_test.go
See title.
closes https://github.com/ossf/scorecard/issues/1349
> ✨ Reduce score by 1 point for each binary found

- checks/sast.go
See https://github.com/ossf/scorecard/issues/1418
closes https://github.com/ossf/scorecard/issues/1418
> 🐛 Fix incorrect detection of CodeQl

- README.md
> :book: Included goreport in the README

- README.md
Add information about running a scorecard container for a specific scorecard version.
> ✨ Update doc for scorecard container

- README.md
Add links to individual checks in the README.
No braking changes.
> ✨ Add links to check doc in README

- checker/check_result.go
- checker/raw_result.go
- checks/dangerous_workflow.go
- checks/fileparser/github_workflow.go
- checks/permissions_test.go
- checks/pinned_dependencies.go
- checks/pinned_dependencies_test.go
- checks/shell_download_validate.go
- checks/shell_download_validate_test.go
- checks/testdata/Dockerfile-args
- checks/testdata/Dockerfile-base
- checks/testdata/Dockerfile-download-lines
- checks/testdata/Dockerfile-download-multi-runs
- checks/testdata/Dockerfile-pkg-managers
- checks/testdata/github-workflow-download-lines.yaml
- checks/testdata/github-workflow-pkg-managers.yaml
- checks/testdata/script-pkg-managers
- checks/testdata/shell-download-lines.sh
- docs/checks.md
- e2e/pinned_dependencies_test.go
- pkg/common.go
- pkg/sarif.go
- pkg/testdata/check1.sarif
- pkg/testdata/check3.sarif
- pkg/testdata/check4.sarif
- pkg/testdata/check8.sarif
- utests/utlib.go
We don't have support for lines for secure download yet. This PR adds support. I happened to have time to look into it...
closes https://github.com/ossf/scorecard/issues/710
closes https://github.com/ossf/scorecard/issues/725
closes https://github.com/ossf/scorecard/issues/701
> ✨ Add line numbers for insecure downloads

- pkg/sarif.go
- pkg/testdata/check3.sarif
- pkg/testdata/check4.sarif
I broke some invariant in a previous commit thru refactoring. Inconclusive results are reported in SARIF, but should not be. Thanks you @azeemsgoogle for reporting!
This PR fixes it.
> 🐛 Inconclusive results should not be reported

- README.md
Updated instructions for accessing the new BigQuery table.
No.
> 🌱 Update BigQuery access instructions

- checks/signed_releases_test.go
Implemented tests for signed releases.
> :seedling: Unit tests for signed release

- checks/maintained_test.go
Included unit tests for maintained check.
> :sparkles: Unit test for maintained check

- checks/fileparser/listing_test.go
Included tests
Included tests for listing.go
> :sparkles: Unit tests for listing file -CheckFileContainsCommands

- checks/raw/security_policy_test.go
Unit tests for security policy
> :sparkles: Unit test for security policy

- checks/fileparser/github_workflow_test.go
> :sparkles: Unit tests github_workflow

- checks/contributors_test.go
Implemented unit tests for contributors.
> :seedling: Unit tests for contributors

- checks/permissions.go
the permissions are set at the "job level", not "run level", so update the message.
> ✨ Update msg from "run level" to "job level"

- checks/pinned_dependencies_test.go
- checks/shell_download_validate.go
- checks/testdata/Dockerfile-pkg-managers
- checks/testdata/github-workflow-pkg-managers.yaml
- checks/testdata/script-pkg-managers
Add support for `npm install-test`
> ✨  Add support for `npm install-test` as unpinned

- cmd/root.go
- cron/config/config.yaml
- cron/config/config_test.go
> ✨ Enable Dangerous-Workflow & License checks for v4

- checks/code_review_test.go
Unit tests for code review check.
> :seedling: Unit tests for code review

- checks/evaluation/security_policy_test.go
Unit test for security policy https://github.com/ossf/scorecard/issues/435
> :sparkles: Unit test for securitypolicy

- cloudbuild/scorecard-tag.yaml
- cloudbuild/scorecard.yaml
Scorecard docker images do not have the correct behavior for `scorecard version` command. This should fix that.
No.
> 🐛 Fix `scorecard version` in Scorecard Docker images

- .github/workflows/stale.yml
Add exemption labels to stale issue workflow.
No.
> 🌱 Add exemption to stale issue workflow

- .github/workflows/main.yml
- .gitignore
- Makefile
> :seedling: Track code coverage

- README.md
> :book: Updated codecov badge

- .github/workflows/integration.yml
> :seedling: Included e2e coverage for codecov

- checks/fileparser/listing_test.go
> :seedling: Unit test for fileparser

- checks/raw/branch_protection_test.go
Fix the reflect.DeepEqual with google cmp
> :seedling: Fix the reflect.DeepEqual with google cmp

- checks/evaluation/binary_artifacts_test.go
Unit tests for binary artifacts.
> :seedling: Unit tests for binary artifacts

- checks/maintained.go
- checks/maintained_test.go
- clients/githubrepo/copy.go
- clients/githubrepo/graphql.go
- clients/issue.go
- clients/user.go
- docs/checks.md
- docs/checks/internal/checks.yaml
Bug fix
For the Maintained check, any issues activity by any Github user increased the score.
https://github.com/ossf/scorecard/issues/1488
Now only if an issue is created, closed, or commented on by a user who is a collaborator, owner, or member will the score be increased.
No
> 🐛 Issue activity only counts if done by a maintainer

- checks/evaluation/dependency_update_tool_test.go
- utests/utlib.go
Unit tests dependency_update_tool
> :seedling: Unit tests dependency_update_tool

- checks/fuzzing_test.go
Unit tests checks for fuzzing.
> :seedling: Unit tests for Fuzzing

- checks/maintained.go
- checks/maintained_test.go
- clients/githubrepo/graphql.go
- clients/issue.go
- * **Please check if the PR fulfills these requirements**
Bug fix
If an issue was closed in the past 90 days, we would count that as activity. However, the person who opened the issue can close it, so an issue closing does not indicate activity by a maintainer.
https://github.com/ossf/scorecard/issues/1523
We will not look at closed date on issues when determining if a repo has activity.
No
> 🐛 Not considering an issue as having activity if closed recently

- README.md
Adds a new badge pointing to our Slack channel.
No
> 🌱 Add Slack channel badge

- .github/dependabot.yml
Included dependabot setting for tools module to get updates.
> :seedling: Included dependabot setting for tools

- checks/raw/dependency_update_tool_test.go
Unit tests
Unit tests for dependency_update_tool
> :seedling: Unit test for dependency_update_tool

- clients/githubrepo/graphql.go
If committer login is not available use another field from GH. Closes #1543 
No.
> 🌱 Use committer name if login isn't available

- checks/fileparser/github_workflow_test.go
Included additional tests for fileparser.
> :seedling: Unit tests for fileparser

- checks/security_policy_test.go
Unit tests for security policy.
> :seedling: Unit tests for security policy

- clients/githubrepo/graphql.go
Reverting broken change from #1558  
No.
> 🐛 Revert `Committer.Name` change

- checks/evaluation/vulnerabilities_test.go
- Unit tests for Vulnerabilities
- https://github.com/ossf/scorecard/issues/986
> :seedling: Unit tests for Vulnerabilities

- .github/workflows/main.yml
Ignore all files under testdata/
needed for https://github.com/ossf/scorecard/pull/1591
> 📖  Ignore all files under testdata/

- CONTRIBUTING.md
Adds a missing step to the development environment setup documentation. 
Fixes #1588
> :book: Add make install to Environment Setup

- checks/fileparser/listing_test.go
Unit test for fileparser/listing
> :seedling: Unit test for fileparser/listing

- README.md
Which is more idiomatic
README update
It recommends the side-effecting `nix-env` command.
It recommends the more isolated `nix-shell` command.
No
> :book: recommend `nix-shell` over `nix-env`

- checks/raw/vulnerabilities_test.go
Unit tests for vulnerabilities raw package
> :seedling: Unit tests for vulnerabilities raw package

- checks/raw/code_review_test.go
Unit tests code-review for raw.
> :seedling: Unit tests code-review for raw

- .codecov.yml
> :seedling: Tweaking codecov config

- checks/ci_tests_test.go
Unit tests for tests checks/ci_tests_test.go
> :seedling: Unit tests checks/ci_tests_test.go

- README.md
- [✔️ ] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process
Docs update to the README.md
Change from Mondays to Thursdays
n/a
No
> 📖  Update the biweekly meeting times

- checks/dependency_update_tool_test.go
Unit tests for dependency_update_tool
> :seedling: Unit tests for dependency_update_tool

- .github/workflows/integration.yml
- .github/workflows/main.yml
> :seedling: Cache builds between runs

- checks/fileparser/listing_test.go
> :seedling: Unit tests fileparser/listing

- README.md
Part of https://github.com/ossf/scorecard/issues/1618.
📖 README.md: Add OpenSSF Best Practices badge
> 📖 README.md: Add OpenSSF Best Practices badge

- cmd/root.go
- cmd/serve.go
- log/log.go
Allow any `Debug` or `debug` for `--verbosity`
No.
> 🐛 Make verbosity levels case insensitive

- .github/workflows/docker.yml
- ignore docker builds for non-main branches
- ignore docker builds for *.md
> :seedling: Ignore docker builds

- .github/workflows/main.yml
- Makefile
The builds were sequential.
- parallelize builds 
- uses the GitHub CI as separate jobs to parallelize builds. 
- GitHub CI Jobs still refer to the makefile targets
> :seedling: Parallelize builds

- .github/workflows/main.yml
Avoiding duplicate builds on main
https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/2
> :seedling: Avoid duplicate builds

- checks/fileparser/listing.go
- checks/fileparser/listing_test.go
- checks/license.go
- checks/raw/security_policy.go
> 🌱 Remove duplicated function definitions

- .codecov.yml
- Ignoring the cron folder from codecov
> :seedling: Ignore cron folder from codecov

- tools/go.mod
- tools/go.sum
- Fixes the containerd vulnerability by replacing 1.58 to 1.59 which
addresses the fix and dependabot will stop complaining about the
issue.
> :seedling: Fix containerd vulns

- checks/fileparser/github_workflow_test.go
- Unit tests for github workflow.
```release-note
NONE
```
> :seedling: Unit tests for github workflow

- checker/client.go
Fixes #1690 
No.
```release-note
```
> 🐛 Fix cmd panic

- checks/fileparser/github_workflow_test.go
unit tests
- Additional tests for github_workflow
NONE
```release-note
NONE
```
> :seedling: additional tests for github_workflow

- tools/go.mod
- tools/go.sum
- Fix for https://github.com/advisories/GHSA-crp2-qrr5-8pq7
NONE
```release-note
Fixed dependecies that had vulnerabilities https://github.com/advisories/GHSA-crp2-qrr5-8pq7
```
> :seedling: Fix for  CVE-2022-23648

- clients/githubrepo/graphql.go
Fixes https://github.com/ossf/scorecard/issues/1710
closes https://github.com/ossf/scorecard/issues/1710
```release-notes
Allow empty committer
```
> 🐛  Allow empty committer

- checks/pinned_dependencies_test.go
Included additional tests
- Additional tests for pinned_dependencies
NONE
```release-note
NONE
```
> :seedling: Unit tests for pinned_dependencies

- .codecov.yml
- Ignoring mock clients for code coverage tracking.
NONE
```release-note
NONE
```
> :seedling: Ignore mock clients for code coverage

- options/options_test.go
- Initial tests for CLI options.
NONE
```release-note
Unit tests for CLI options.
```
> :sparkles: Unit test for CLI options

- cron/format/json.raw.schema
- pkg/json.raw.schema
Add JSON schema for cron and scorecard's raw results
```release-notes
Add JSON schema for cron and scorecard's raw results
```
> 📖 Add schema for the raw JSON

- cron/k8s/transfer.release-raw.yaml
Update BQ table name for raw result's releasetest
```release-notes
Update BQ table name for raw result's releasetest
```
> ✨ Update BQ table name for raw results

- checker/raw_result.go
- checks/cii_best_practices.go
- checks/evaluation/maintained.go
- checks/maintained.go
- checks/maintained_test.go
- checks/raw/code_review.go
- checks/raw/code_review_test.go
- checks/raw/maintained.go
- clients/githubrepo/client.go
- clients/githubrepo/graphql.go
- clients/issue.go
- clients/mockclients/repo_client.go
- e2e/maintained_test.go
- pkg/json_raw_results.go
- pkg/scorecard_result.go
Add support for raw results for Maintained check
```release-notes
Add support for raw results for Maintained check
```
> ✨ Raw result for Maintained check

- .github/workflows/main.yml
- Fix protoc build failures by retries
```release-note
```
> :seedling: Fix protoc build failures

- e2e/permissions_test.go
- Included e2e tests for local repoclient for permissions.
NONE
```release-note
NONE
```
> :seedling: e2e tests for local repoclient for permissions

- e2e/security_policy_test.go
- Included e2e tests for security policy for localrepo client
https://github.com/ossf/scorecard/issues/1353
NONE
```release-note
NONE
```
> :seedling: e2e tests for security policy localrepo

- checker/raw_result.go
- checks/evaluation/signed_releases.go
- checks/raw/signed_releases.go
- checks/raw/vulnerabilities.go
- checks/signed_releases.go
- pkg/json_raw_results.go
Raw results for Signed-Release check
```release-notes
Raw results for Signed-Release check
```
> ✨ Raw results for Signed-Release check

- .github/workflows/codeql-analysis.yml
- Included the experimental option for Codeql
https://github.blog/2022-02-17-code-scanning-finds-vulnerabilities-using-machine-learning/
```release-note
```
> :seedling: Experimental option for codeql

- checks/dangerous_workflow.go
- checks/dangerous_workflow_test.go
- checks/testdata/.github/workflows/github-workflow-dangerous-pattern-untrusted-checkout-workflow_run.yml
- docs/checks.md
- docs/checks/internal/checks.yaml
feature
The dangerous workflow checks don't test for the 'workflow_run' trigger.
Check for the 'workflow_run' trigger when conducting 'unsafe checkout' and 'secrets in environment' checks.
[1817](https://github.com/ossf/scorecard/issues/1817)
> ✨ detect workflow_run as a dangerous trigger

- .github/workflows/depsreview.yml
Included the https://github.com/actions/dependency-review-action
> :seedling: Dependency review action

- .github/workflows/publishimage.yml
- Makefile
- go.sum
- Publish images with ko
https://github.com/ossf/scorecard/issues/744
> :seedling: Publish images with ko

- checks/binary_artifact_test.go
- checks/code_review_test.go
- checks/contributors_test.go
- checks/maintained_test.go
- checks/sast_test.go
- checks/signed_releases_test.go
- checks/webhook_test.go
- cron/format/json.go
- e2e/binary_artifacts_test.go
- e2e/branch_protection_test.go
- e2e/cii_best_practices_test.go
- e2e/contributors_test.go
- e2e/dangerous_workflow_test.go
- e2e/dependency_update_tool_test.go
- e2e/license_test.go
- e2e/maintained_test.go
- e2e/permissions_test.go
- e2e/sast_test.go
- e2e/security_policy_test.go
- e2e/signedreleases_test.go
- e2e/vulnerabilities_test.go
- pkg/json.go
- Removing the pass field from result
https://github.com/ossf/scorecard/issues/1393
> :warning: Removing the pass field from result 

- cron/worker/main.go
- removed the old json format from cron
fix https://github.com/ossf/scorecard/issues/1393 
> :warning: Remove the oldjson format from cron

- checker/raw_result.go
- checks/evaluation/dependency_update_tool.go
- checks/evaluation/dependency_update_tool_test.go
- checks/evaluation/fuzzing.go
- checks/raw/dependency_update_tool.go
- checks/raw/fuzzing.go
- cron/format/json_raw_results.go
- pkg/json_raw_results.go
Use Tool for raw fuzzing results, so that it is shared with Dependency update tools.
```release-notes
Use Tool for raw fuzzing results
```
closes https://github.com/ossf/scorecard/issues/1933
> ✨ Use Tool for raw fuzzing results

- checks/evaluation/code_review.go
Minor bug fix.
Piper review debug logs claim that the review is done by phabricator.
There are no tests for the log messages.
NONE
NO
```release-note
NONE
```
> 🐛 Fix debug log for Piper

- checker/raw_result.go
- checks/evaluation/maintained.go
- checks/raw/maintained.go
- clients/user.go
- pkg/json_raw_results.go
Part of #1943 
NONE
```release-note
NONE
```
> 🌱 Replace `checker.Issue` with `clients.Issue`

- checker/raw_result.go
- checks/evaluation/signed_releases.go
- checks/raw/signed_releases.go
- pkg/json_raw_results.go
Part of #1943 
NONE
```release-note
NONE
```
> 🌱 Replace `checker.Release` with `clients.Release`

- checker/raw_result.go
- checks/evaluation/webhooks.go
- checks/evaluation/webhooks_test.go
- checks/raw/webhook.go
- checks/raw/webhooks_test.go
- checks/webhook_test.go
- clients/githubrepo/client.go
- clients/githubrepo/webhook.go
- clients/localdir/client.go
- clients/mockclients/repo_client.go
- clients/repo_client.go
Part of #1943 
NONE
```release-note
NONE
```
> 🌱 Replace `checker.Webhook` with `clients.Webhook`

- checker/raw_result.go
- checks/evaluation/branch_protection.go
- checks/evaluation/branch_protection_test.go
- checks/raw/branch_protection.go
- cron/format/json_raw_results.go
- pkg/json_raw_results.go
Part of #1943 
NONE
```release-note
NONE
```
> 🌱 Replace `checker.BP` with `clients.BP`

- checker/raw_result.go
- checks/contributors_test.go
- checks/evaluation/contributors.go
- checks/raw/contributors.go
- clients/contributor.go
- clients/githubrepo/contributors.go
- pkg/json_raw_results.go
Part of #1943 
NONE
```release-note
NONE
```
> 🌱 Replace `checker.User` with `clients.User`

- checker/raw_result.go
- checks/contributors_test.go
- checks/evaluation/code_review.go
- checks/evaluation/code_review_test.go
- checks/evaluation/contributors.go
- checks/evaluation/maintained.go
- checks/raw/code_review.go
- checks/raw/code_review_test.go
- checks/raw/contributors.go
- checks/raw/maintained.go
- clients/contributor.go
- clients/githubrepo/contributors.go
- cron/format/json_raw_results.go
- pkg/json_raw_results.go
Part of #1943 
NONE
```release-note
NONE
```
> 🌱 Replace `checker.Commit` with `clients.Commit`

- cron/internal/controller/Dockerfile
- cron/k8s/controller.release.yaml
- cron/k8s/controller.yaml
Fixes bus introduced in #1960 
NONE
```release-note
NONE
```
> 🐛 Fix bug in move to `internal`

- checks/branch_protection_test.go
- checks/evaluation/security_policy.go
- checks/raw/branch_protection.go
- checks/raw/branch_protection_test.go
- checks/raw/errors.go
- clients/githubrepo/branches.go
- clients/githubrepo/client.go
- clients/localdir/client.go
- clients/mockclients/repo_client.go
- clients/repo_client.go
Fixes #1320 
Fixes #1320 
```release-note
NONE
```
> 🐛 Only pull required branch names

- README.md
> :seedling: Included Stargazers over time

- .github/workflows/main.yml
> :seedling: Workaround for Protoc failures in GH Actions

- README.md
> :seedling: Naveen Company updated.

- clients/githubrepo/client.go
- clients/localdir/client.go
- cron/internal/config/config.go
- cron/internal/config/config.yaml
- cron/internal/config/config_test.go
- cron/internal/controller/main.go
- cron/internal/worker/main.go
- cron/k8s/worker.release.yaml
- Exporting the Scorecard results for the scorecard API.
- The code exports as result.json without the commit SHA and also with
the commit SHA.
Fixes https://github.com/ossf/scorecard/issues/1056
> ✨  Export Scorecards results for API

- .github/workflows/scorecard-analysis.yml
- README.md
Early adopt the Scorecard badges beta feature. 
NONE
```release-note
NONE
```
> ✨ Enable Scorecard badge

- .github/workflows/scorecard-analysis.yml
Typo: `token-id` -> `id-token` in GH workflow
NONE
```release-note
NONE
```
> 🐛 Fix bug in Scorecard analysis CI

- .github/workflows/scorecard-analysis.yml
Scorecard action fails if the steps included as part of the Scorecard action job diverge from the "accepted" actions. Need to remove the extra step to conform to this.
NONE
```release-note
NONE
```
> 🐛 Scorecard runs fail with any unrecognized steps

- cron/internal/config/config.go
- cron/internal/config/config.yaml
- cron/internal/config/config_test.go
- cron/internal/worker/main.go
The current cron job writes its data to the releasetest bucket and also uses the wrong filename. This PR fixes that and fixes the naming convention used.
#1056 
```release-note
NONE
```
> 🐛 Fix a bug in cron API data exporting

- .github/workflows/docker.yml
- .github/workflows/goreleaser.yaml
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .github/workflows/publishimage.yml
- .github/workflows/scorecard-analysis.yml
- .github/workflows/slsa-goreleaser.yml
- github actions cleanup and set to get the latest go available 
n/a
NONE
```release-note
NONE
```
> 🌱 github actions cleanup and set to get the latest go available 

- cron/internal/data/add/main.go
Bug fix: there is URL duplication simply due to projects specified with unique casings. This PR fixes that.
```release-note
NONE
```
> 🐛 Remove duplicate projects with different casings

- .github/workflows/scorecard-analysis.yml
Update scorecard-action to v2:alpha which has some bug fixes
NONE
NONE
```release-note
NONE
```
> 🌱 Update scorecard-action to v2:alpha

- checks/raw/license.go
- checks/raw/license_test.go
Enhance license check to address #2159 
GPL-2.0 not detected as a valid license. The other license files in #2159 are already accepted
GPL-2.0 license now detected.
Fixes #2159 
Should GPL-3.0 be included as well? Should be an easy regex change
```release-note
GPL-2.0 license files are now detected by the License check
```
> ✨ Improved license check

- cron/k8s/README.md
docs update explaining how to apply k8s changes to the cron job infrastructure
NONE
```release-note
NONE
```
> 📖 Add k8s README

- clients/githubrepo/client.go
- clients/githubrepo/tarball.go
This PR adds a `httpClient`  in `tarballHandler` that adds `authorizationHeader` while sending requests; because the current way of fetching tarball fails for `private-repos`  as no `Authorization Header` is being added
Fixes #2277
```release-note
None
```
> :bug: Add fix for issue2277

- Makefile
Signed-off-by: Azeem Shaikh <azeemshaikh38@gmail.com>
Part of #2287. Improves consistency of installed tool behavior.
```release-note
NONE
```
> 🌱 Modify tool installation

- .github/dependabot.yml
- Reduce the number of PR's opened by dependabot
> :seedling: Reduce the number of PR's opened by dependabot

- Makefile
Bug fix for typo in  #2293 
`make build-proto` will fail
`make build-proto` will succeed
NONE
```release-note
NONE
```
> 🐛  Fix argument typo in Makefile

- Makefile
- Remove Check OSV as it is integrated into GitHub now.
> :seedling: Remove check-osv

- cron/internal/bq/main_test.go
- cron/internal/bq/testdata/basic/2022.09.19/020001/.shard_metadata
- cron/internal/bq/testdata/basic/2022.09.26/020003/.shard_metadata
- cron/internal/data/blob.go
Add tests as requested here: https://github.com/ossf/scorecard/pull/2308#discussion_r982786821
No tests for getBucketSummary.
* `cron/internal/data` loads `fileblob` drivers from `gocloud.dev/blob/fileblob`
* this was a blocker for testing many functions that dealt with a bucketURL parameter
* getBucketSummary (main package of `cron/internal/bq`) is tested
https://github.com/ossf/scorecard/pull/2308#discussion_r982786821
`cron/internal/data` loads `fileblob` drivers from `gocloud.dev/blob/fileblob`.
While the change helps testing, the import side effect also occurs for the production binaries. I don't anticipate any change in behavior as it only matters when the bucket prefix starts with `file:///`
For user-facing changes, please add a …
> 🌱 Add tests for getBucketSummary.

- .github/workflows/goreleaser.yaml
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .github/workflows/slsa-goreleaser.yml
- go.mod
- tools/go.mod
- Migrate to go 1.19
NONE
```release-note
Migrate to go 1.19
```
> :seedling: Migrate to go 1.19

- docs/faq.md
Typos and copy-editing for docs/faq.md.
> 📖 Copy-editing docs/faq.md

- .github/workflows/integration.yml
fix failing integration workflow
syntax issue I didn't catch
fixed syntax.
NONE
```release-note
NONE
```
> 🌱 fix failing integration workflow

- .github/workflows/scorecard-analysis.yml
fix for scorecard action failures
The scorecard action workflow (https://github.com/ossf/scorecard/actions/workflows/scorecard-analysis.yml) has been failing for days due to a `sigstore/cosign` change. 
See https://github.com/ossf/scorecard-action/issues/997 for details.
workflow works
NONE
```release-note
NONE
```
> 🌱  Bump scorecard-action

- .github/workflows/integration.yml
- .github/workflows/main.yml
bug fix
PRs are blocked when codecov has rate-limit issues
PRs not blocked on codecov
Fixes #2420 
```release-note
NONE
```
> 🌱 revert failing CI on codecov upload errors

- clients/githubrepo/repo.go
Signed-off-by: Michael Scovetta <michael.scovetta@microsoft.com>
Trivial spelling fix.
The word "expected" is mis-spelled.
The word "expected" is correctly spelled.
NONE
The error message would be spelled correctly, but I don't think that it needs a release note, unless someone thinks that users would be relying it.
> :seedling: Trivial: Fix typo (exepted -> expected)

- .github/workflows/integration.yml
- Including Gitlab token for https://github.com/ossf/scorecard/pull/2280
> :seedling: Included Gitlab token

- .github/workflows/goreleaser.yaml
Signed-off-by: laurentsimon <64505099+laurentsimon@users.noreply.github.com>
```release-note
Bump SLSA generator version
```
> ✨ Bump SLSA generator version

- checks/raw/dependency_update_tool.go
- e2e/dependency_update_tool_test.go
- Fix typo in renovatebot
- Fixes https://github.com/ossf/scorecard/issues/2568
> :bug: Fix Renovate bot typo

- README.md
Signed-off-by: Ashwin Ramaswami <aramaswamis@gmail.com>
Fix typo (add s to ')
> :book: Fix typo (add s to ')

- README.md
docs update
The README shows the old 'Pin a Project' label
The README shows the new 'Star a project by name' label
NONE
```release-note
NONE
```
> :book: update bigquery docs in README

- checker/detail_logger_impl_test.go
- checker/raw_result.go
- Included tests for detail_logger_impl.
- It has 100% coverage.
```release-note
```
> :seedling: Unit tests for checker/detail_logger_impl

- checks/evaluation/cii_best_practices.go
- checks/evaluation/cii_best_practices_test.go
- Add a test file for the CII Best Practices checker
- Add tests for different badge responses and assign different scores based on badge responses
- Change CIIBestPractices function parameter and add a check for empty raw data
```release-note
```
> :seedling: Included unit tests for CII Best practices

- checks/evaluation/dangerous_workflow_test.go
- Add a test to check for dangerous workflow patterns
- Add checks to prevent script injection and invalid types
- Add a check to ensure workflow data is valid
- 100% Coverage.
```release-note
```
> :seedling: Unit tests for dangerous workflows

- checks/evaluation/fuzzing_test.go
- Add fuzzing tests for checker
- Enhance logic for checking if project is fuzzed
- Handle nil FuzzingData
```release-note
```
> :seedling: Unit tests Fuzzing Checker

- checks/evaluation/contributors_test.go
- Code coverage of 95% for contributors.
```release-note
```
> :seedling: Unit test for Contributors

- checks/evaluation/maintained_test.go
- Unit tests for checks/evaluation/maintained.go
- 100% coverage.
```release-note
```
> :seedling: Unit tests  checks/evaluation/maintained.go

- checks/evaluation/packaging_test.go
- Include unit tests for checks/evaluation/packaging.go
```release-note
```
> :seedling: Unit tests for checks/evaluation/packaging.go

- checks/evaluation/ci_tests.go
- checks/evaluation/ci_tests_test.go
- Included additional tests for ci_tests.
- The coverage is at 90% for ci tests.
```release-note
```
> :seedling: Unit tests for checks/ci_tests

- .github/workflows/integration.yml
- Update codecov to include multiple directories in the workflow integration
[.github/workflows/integration.yml]
- Update codecov files to include multiple directories
```release-note
```
> :seedling: Included coverage metrics from other e2e

- checks/evaluation/security_policy.go
- checks/evaluation/security_policy_test.go
- Add tests for security policy evaluation
- Fix the typo in the comment
```release-note
```
> :seedling: Unit tests checks/evaluation/security_policy.go

- .github/workflows/goreleaser.yaml
- .github/workflows/slsa-goreleaser.yml
There is no verification step for provenance
Provenance will be verified right after the generated during the build.
Fixes #2747 
- Successful workflow: https://github.com/developer-guy/scorecard/actions/runs/4457375709/jobs/7828447299
PTAL @laurentsimon 
Nope.
> 🌱 feature: enable verification for provenance

- rule/rule_test.go
- Unit tests for rule/rule.go
- Covered with 88% of code.
```release-note
```
> :seedling: Unitest for rule/rule.go

- checks/evaluation/signed_releases_test.go
- Add a test file to the Signed Releases check provenance
```release-note
```
> :seedling: Unit tests checks/evaluation/signedrelease.go

- clients/githubrepo/copy_test.go
- Add tests for the utility functions
- 100% test coverage.
```release-note
```
> :seedling: Unit test clients/githubrepo/copy.go

- cron/config/config.yaml
- cron/config/config_test.go
- cron/k8s/worker.release.yaml
cron
config had outdated info
config matches the checks that are running in the cron.
NONE
```release-note
NONE
```
> :seedling: Update cron config to reflect SAST and Vulnerabilities are running again.

- errors/internal_test.go
- errors/public_test.go
Unit tests errors/internal.go
```release-note
```
> :seedling: Unit tests errors/internal.go

- checks/evaluation/pinned_dependencies_test.go
Unit tests for checks/evaluation/pinned_dependencies.go
```release-note
```
> :seedling: Unit tests for checks/evaluation/pinned_dependencies.go

- log/log_test.go
- Add unit tests for the log package
```release-note
```
> :seedling: Unit tests log/log.go

- clients/githubrepo/checkruns_e2e_test.go
Additional e2e clients/githubrepo/checkruns.go
```release-note
```
> :seedling: Additional e2e clients/githubrepo/checkruns.go

- clients/githubrepo/contributors_e2e_test.go
- clients/githubrepo/githubrepo_suite_test.go
- go.mod
- Add an end-to-end test for `contributorsHandler`
```release-note
```
> :seedling: E2E for clients/githubrepo/contributors.go

- checks/raw/maintained_test.go
- Add tests and checks for the `Maintained` function
```release-note
```
> :seedling: Unit tests for checks/raw/maintained.go

- .codecov.yml
- policy/policy_test.go
- Included tests for policy.go
```release-note
```
> :seedling: Unit tests for Policy.go

- .codecov.yml
- Included directories that don't require coverage.
```release-note
```
> :seedling: Included directories that don't require coverage

- checks/raw/contributors_test.go
- Add tests Contributors function in checks/raw/contributors_test.go
```release-note
```
> :seedling: Unit tests for checks/raw/contributors.go

- pkg/json_raw_results.go
- pkg/json_raw_results_test.go
> :seedling: Unit tests for pkg/json_raw_results

- README.md
>  📖 Adds zoom link and agenda link

- .github/workflows/main.yml
-Fixed the YAML indenting issue.
```release-note
```
> :seedling: Fixed the YAML  indenting issue main.yml

- cron/internal/controller/Dockerfile
> 🐛 GitLab cron: rename

- README.md
> :book: agenda link change

- options/flags_test.go
- Add flags for repo, local, commit, log level, NPM, PyPI, RubyGems, metadata, show details, checks to run, policy file, and format
- Add tests for checks to run and format flags
```release-note
```
> :seedling: Unit tests for option

- .codecov.yml
- Update .codecov.yml to ignore additional files
```release-note
```
> :seedling: Ignore all pb files for test

- finding/finding_test.go
- Add tests for Outcome UnmarshalYAML function in `finding/finding_test.go`
```release-note
```
> :seedling: Increase test coverage for finding outcomes

- clients/githubrepo/releases_e2e_test.go
- Add e2e test for githubrepo releases handler
```release-note
```
> :seedling: Improve Githubrepo Releases handler E2E tests

- clients/githubrepo/statuses_e2e_test.go
- e2e for statuses.
```release-note
```
> :seedling: e2e for statuses

- clients/githubrepo/licenses_e2e_test.go
- e2e for licenses
```release-note
```
> :seedling: e2e for licenses

- clients/githubrepo/roundtripper/tokens/accessor_test.go
- Replace `startTestServer()` with `httptest.NewServer`
```release-note
```
> :seedling: Improve GitHub Access Token Tests

- clients/githubrepo/roundtripper/tokens/round_robin_test.go
- Add tests for the round-robin token accessor
```release-note
```
> :seedling: Add unit tests for roundrobin

- attestor/command/cli_test.go
- Add a test for the `addSignFlags` function
```release-note
```
> :seedling: Add test for attestor CLI

- checker/raw_result_test.go
- Included unit tests
```release-note
```
> :seedling: Included unit tests for raw_restult

- .github/workflows/main.yml
- Exclude dependabot from codecov job in main.yml
[.github/workflows/main.yml]
- Exclude dependabot from codecov job
```release-note
```
> :seedling: Excluded dependabot from codecov

- e2e/searchCommits_test.go
- Add an e2e test for searching commits by author
- Search commits by author `dependabot[bot]` and expect results
```release-note
```
> :seedling: Increase test coverage for searching commits

- .github/workflows/gitlab.yml
- .github/workflows/integration.yml
ci change, trying to reduce CI time
- The gitlab e2e tests on PR runs in serial with the github e2e tests.
- The gitlab tests are defined in multiple places
- The workflows are centralized in `gitlab.yml`.
- The gitlab e2e test runs in parallel with the github e2e tests.
- There's a few if statements to make sure the right commit gets checked out, and the right test run for the environment.
NONE
I did test some of the fallback value semantics [here](https://github.com/spencerschrock/actions-test/actions/workflows/ref.yml) and code checks out the right contents.
```release-note …
```
> :seedling: Consolidate GitLab e2e workflows.

- clients/gitlabrepo/project_e2e_test.go
- Add e2e test for GitLab projects
- Test Project details- GitLab: check if project is archived and get createdAt date
```release-note
```
> :seedling: Improve GitLab project e2e tests

- clients/cii_response_test.go
- Add functions for parsing JSON responses and converting to/from JSON
- Add tests for the badge response functions
```release-note
```
> :seedling: Unit tests badge response

- clients/gitlabrepo/releases_e2e_test.go
- Add a context for gitlabrepo list releases test
- Initialize a gitlab client and repo
- Add an assertion for the number of releases returned
```release-note
```
> :seedling: Add e2e test for GitLab repo releases

- clients/gitlabrepo/branches_e2e_test.go
- Add an E2E test to check the default branch of a GitLab repo
- Initialize the repo with the HEAD commit and 0 depth
- Check that the default branch is named "main"
[clients/gitlabrepo/branches_e2e_test.go]
- Add an E2E test to check the default branch of a GitLab repo
- Initialize the repo with the HEAD commit and 0 depth
- Check that the default branch is named "main"
```release-note
```
> :seedling: Improve GitLab repo branches E2E test

- clients/gitlabrepo/statuses_test.go
- clients/gitlabrepo/testdata/valid-status
- clients/gitlabrepo/testdata/valid-webhook
- clients/gitlabrepo/webhook_test.go
Included test for Gitlab status and webhook
```release-note
```
> :seedling: Unit tests for Gitlab status and WebHooks

- pkg/scorecard.go
Cleans up some duplicate comments and fixes a typo.
Comment fix
This PR is unrelated to behavior.
NONE
No
```release-note
NONE
```
> :book: Remove repeated comment

- .github/workflows/stale.yml
Removes recent workflow change
Closes issues marked stale after 7 days
Issues will be marked stale, but not closed
NONE
```NONE
```
> 🌱 workflows/stale: Remove issue auto-close

- checker/raw_result.go
This PR re-orders the fields of the `RawResults` for easier readability.
NONE
NONE
```release-note
```
> :seedling: Sort fields of raw results alphabetically

- checks/raw/fuzzing.go
lint fix
linter complained
linter issue fixed
Not entirely sure how it slipped through the initial PR (#3473)
```release-note
```
> :seedling: checks/raw: fix struct alignment linter issue

- finding/finding.go
bug fix
https://github.com/ossf/scorecard/pull/3558/files#r1355375992
Fixes #3560 
NONE
```release-note
```
> :bug: Fix wrong quotes

- finding/finding.go
feature
`UnmarshalYAML` cannot return `OutcomeNotApplicable`
`UnmarshalYAML` can return `OutcomeNotApplicable`
NONE
NONE
```release-note
```
> :seedling: Add new outcome to UnmarshalYAML

- .github/workflows/scdiff.yml
workflow fix
User controlled input was improperly sanitized, leading to scenarios where attackers who previously contributed to Scorecard could leak our (unprivileged) GitHub/GitLab CI tokens. Thanks to @AdnaneKhan for the report.
Environment variables are used to prevent both JavaScript and Bash injections
Private report. 
```release-note
NONE
```
> :seedling: fix script injection

- tools/go.mod
- tools/go.sum
- Update go version from `1.19` to `1.21`
[tools/go.mod]
- Update go version from `1.19` to `1.21`
```release-note
```
> :seedling: Update Go version to 1.21 for tools

- checks/evaluation/permissions/permissions.go
Currently, the Permissions checks applies the score directly from the raw results.
This PR adds an extra step to the the Permissions check. Instead of Permissions applying the score directly from the raw results, the check now creates a slice of findings from the raw results, and then passes the slice of findings onto the scoring.
This is the workflow that Permissions will use, once it gets migrated to probes. The reason I don't migrate to probes at once is to reduce complexity and size of PRs. In addition, this PR highlights the limitations of the migration: The enums are used because findings have a `map[string]int` values map.
This check might require a few iterations of refactoring before introducing the probes.
For user-facing …
> :seedling: refactor permissions

- checks/all_checks_test.go
- checks/branch_protection_test.go
- checks/dependency_update_tool_test.go
- checks/fuzzing_test.go
- checks/maintained_test.go
- checks/sast_test.go
- checks/security_policy_test.go
- Fixed the struct size govet issues.
```release-note
```
> :seedling: Fix struct size govet issues

- pkg/scorecard.go
- changed the channel to write only
```release-note
```
> :seedling: Change the chan to write only

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/stale.yml
Update label references stale workflow and issue templates to reflect changes to label names
Stale workflow exemptions include 'priority', 'bug', 'good first issue', 'backlog', and 'help wanted' labels.
Bug template uses 'bug' label.
Enhancement template uses 'enhancement' label.
Stale workflow exemptions include 'priority/must-do', 'kind/bug', 'good first issue', and 'help wanted' labels.
Bug template uses 'kind/bug' label.
Enhancement template uses 'kind/enhancement' label.
NONE
```release-note
NONE
```
> ✨ Update stale.yml, issue template label references

- README.md
Added user feedback survey to readme.md
Survey not included
Survey included in the Using Scorecard section of readme.md
NONE
```release-note
NONE
```
> 📖 Add survey announcement to readme

- Dockerfile
- attestor/Dockerfile
- clients/githubrepo/roundtripper/tokens/server/Dockerfile
- cron/internal/bq/Dockerfile
- cron/internal/cii/Dockerfile
- cron/internal/controller/Dockerfile
- cron/internal/webhook/Dockerfile
- cron/internal/worker/Dockerfile
dep upgrade
Combination of
* #3933 
* #3934
* #3935 
* #3936 
* #3937 
* #3938 
* #3939 
* #3940 
This should be one of the last last time we need to do a non-grouped update.
The feature that would let dependabot do this for us should be in beta soon ([related issue](https://www.github.com/dependabot/dependabot-core/issues/7547#issuecomment-1979489566))
```release-note
NONE
```
> :seedling: Bump golang from 1.22.0 to 1.22.1

- probes/README.md
- probes/archived/def.yml
- probes/blocksForcePushOnBranches/def.yml
- probes/branchProtectionAppliesToAdmins/def.yml
- probes/branchesAreProtected/def.yml
- probes/contributorsFromOrgOrCompany/def.yml
- probes/createdRecently/def.yml
- probes/dependencyUpdateToolConfigured/def.yml
- probes/dismissesStaleReviews/def.yml
- probes/hasBinaryArtifacts/def.yml
- probes/hasDangerousWorkflowScriptInjection/def.yml
- probes/hasDangerousWorkflowUntrustedCheckout/def.yml
- probes/hasFSFOrOSIApprovedLicense/def.yml
- probes/hasLicenseFile/def.yml
- probes/hasOSVVulnerabilities/def.yml
- probes/hasOpenSSFBadge/def.yml
- probes/hasRecentCommits/def.yml
- probes/hasUnverifiedBinaryArtifacts/def.yml
- probes/issueActivityByProjectMember/def.yml
- probes/packagedWithAutomatedWorkflow/def.yml
- probes/requiresPRsToChangeCode/def.yml
- probes/securityPolicyContainsLinks/def.yml
- probes/securityPolicyContainsText/def.yml
- probes/securityPolicyContainsVulnerabilityDisclosure/def.yml
- probes/securityPolicyPresent/def.yml
- probes/webhooksUseSecrets/def.yml
documentation
Related to #2657 but we'll need another review after the prerelease feedback.
```release-note
NONE
```
> :book: Review and update some probe documentation

- README.md
- docs/faq.md
Update docs to point to new website: https://securityscorecards.dev -> https://scorecard.dev
> 📖 Docs: update website

- .github/workflows/publishimage.yml
fix the publishimage workflow
- the signing command assumes v4, but we're now on v5 release candidates
- a new image gets pushed for every commit, which is a lot!
- Use v5 tag in cosign signing
- only publish ghcr images for tagged releases
```release-note
```
> :seedling: bump publishimage version

- pkg/sarif.go
- pkg/testdata/check-remediation.sarif
- pkg/testdata/check1.sarif
- pkg/testdata/check1_annotations.sarif
- pkg/testdata/check2.sarif
- pkg/testdata/check3.sarif
- pkg/testdata/check4.sarif
- pkg/testdata/check5.sarif
- pkg/testdata/check6.sarif
- pkg/testdata/check7.sarif
- pkg/testdata/check8.sarif
bug fix
link to https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json
link to https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json
NONE
```release-note
NONE
```
> :bug: fix: correct sarif json schema url

- SECURITY.md
Fast-follow to https://github.com/ossf/scorecard/pull/4212.
> 📖 SECURITY: Represent response times in business days instead of hours

- checker/check_result.go
- checker/check_result_test.go
- pkg/json.go
- pkg/sarif.go
- pkg/scorecard_result.go
breaking change, just a simple rename
Related to #4048
```release-note
NONE
```
> :warning: rename annotation IsExempted to Annotations

- README.md
- config/README.md
Remove "experimental" language around maintainer annotations.
> 📖 Docs: Remove experimental language around maintainer annotations

- clients/githubrepo/client.go
bug fix
see issue
Fixes #4255
no
```release-note
NONE
```
> :bug: Update Org RepoClient creation to use transport from parent Client

- .gitignore
- checks/evaluation/maintained.go
- probes/createdRecently/impl.go
Fix grammar in maintained check message.
Wording could be improved.
Wording is improved.
NONE
None.
```release-note
Fix grammar in maintained check messages.
```
> :book: Fix grammar for maintained check

- probes/issueActivityByProjectMember/impl.go
- probes/issueActivityByProjectMember/impl_test.go
AuthorAssociation can technically be nil so add two checks
bug
Fixes https://issues.oss-fuzz.com/issues/420740700
```release-note
```
> 🐛 add nil-pointer check in issueActivityByProjectMember

- checks/raw/security_policy_test.go
Expanding unit test coverage.
There's no explicit testing of the regular expressions in collectPolicyHits.
NONE
I would like to propose changes to these regular expressions in a future change - so, I'm adding tests now to establish baseline coverage.
```release-note
NONE
```
> :seedling: Add unit tests to cover collectPolicyHits

- checks/raw/sast.go
- checks/raw/sast_test.go
- checks/raw/signed_releases.go
bug fix
Currently Scorecard logs even though the logger technically can be nil.
Scorecard now checks whether the logger is nil before logging.
I have added a test case to the existing test.
Fixes https://github.com/ossf/scorecard/issues/4531
```release-note
add nil check for loggers in checks raw
```
> 🐛 add nil check to loggers in checks/raw

- checks/raw/dangerous_workflow_test.go
bug fix
Scorecard does not test for commit author name and email. This is important to test for to make sure Scorecard correctly reads the array.
Scorecard tests for commit author name and email.
NONE
no
```release-note
NONE
```
> :seedling: add test cases for author name and email

- checks/raw/pinned_dependencies_test.go
- checks/raw/shell_download_validate.go
Bug fix
_"dependencies"_ is spelled incorrectly.
_"dependencies"_ is spelled correctly.
NONE
```release-note
Fix typo of "dependencies" for the `pinned-dependencies` rule.
```
> :book: fix dependencies typo 
