ossf/scorecard

checks/code_review.go
PR review policy is good to check but keep its confidence low
since actual enforcement is checked by GithubCodeReview and
ProwCodeReview and those values should be used.
=> Lower pr review policy confidence to enforce GithubCodeReview

checks/frozen_deps.go
According to npm, it has the same effect as a package-lock.json:
https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json
Resolves #54
=> Frozen-Deps Check: Add npm-shrinkwrap.json lockfile

checks/security_policy.go
The current Security-Policy check only looks for policy files within the target repository, which is not the only way of specifying a security policy.
This extends the check to also look for a security policy that is set via GitHub's default community health file functionality (see https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file).
Seems relevant to https://github.com/ossf/scorecard/issues/39.
=> extend Security-Policy check to check default community health files

checks/ci_tests.go
I'm not quite sure how it happens since I've never been able to reproduce
it a second time in a row, so let's treat it as somethign to be retried.
=> I've seen this test crash a couple times with a "nil" result.

checks/code_review.go, cmd/root.go
See
```
$ go run . --repo=https://github.com/protocolbuffers/protobuf --show-details --checks=Code-Review
Starting [Code-Review]
Finished [Code-Review]
RESULTS
-------
Code-Review: Pass 9
found different author and committer for pr: 8053
found different author and committer for pr: 8052
found review approved pr: 8048
found review approved pr: 8045
found different author and committer for pr: 8043
found review approved pr: 8035
found review approved pr: 8032
found review approved pr: 8030
found review approved pr: 8029
found review approved pr: 8028
found review approved pr: 8026
found review approved pr: 8025
found review approved pr: 8024
found review approved pr: 8023
found review approved pr: 8022
found different author and committer for pr: 8014
found different author and committer …
```
=> Improve code review check to account for diff author-committer usecase.

cron/cron.sh, cron/projects.txt
This way we can add things in multiple sections and not worry about deduping.
=> Sort/uniquify the projects list before running.

checks/pull_requests.go, checks/signed_releases.go, checks/signed_tags.go
I have one commit per check in this PR.  See commit messages for more details.
I'd like to get more checks updated, but these are the simple ones.
Updates #95
=> Show negative results in some check details

checks/ci_tests.go
Add negative check results to the CI-Tests output.
Assuming that a repo will only support one CI system, GithubStatuses and
GithubCheckRuns are merged into a single CITests function.  Since both
GithubStatuses and GithubCheckRuns were essentially validating the same
PRs, it makes more sense to keep all of that state together in a single
check.
Additionaly, a single check can reduce the number of API queries once we
detect the CI system in use.
Fixes #96
Updates #95
=> Refactor CI-Tests to show negative results

checks/signed_releases.go
Use the release TagName instead of Name when reporting found releases.
An example of the problem using Name:
```
$ go run . --repo=github.com/magefile/mage --show-details --checks=Signed-Releases
Starting [Signed-Releases]
Finished [Signed-Releases]
RESULTS
-------
Signed-Releases: Fail 10
release found: Colors, working directory, some better errors
!! release Colors, working directory, some better errors has no signed artifacts
release found: Modules and go1.13 Fixes
!! release Modules and go1.13 Fixes has no signed artifacts
release found: v1.8.0 - Papercuts and Bug Fixes
!! release v1.8.0 - Papercuts and Bug Fixes has no signed artifacts
release found: v1.7.1
!! release v1.7.1 has no signed artifacts
release found: v1.7.0 Mage Imports
!! release v1.7.0 Mage Imports has no signed …
```
=> Use release tag name instead of name in log messages

cron/cron.sh
This change will add a `details` section to the cron job output.
Fixes #112
=> Add --show-details to the cron job.

.github/workflows/goreleaser.yaml
Implemented [goreleaser](https://github.com/goreleaser/goreleaser-action) for releasing the code to Github. The release would happen only for `tag` pushes
The release would be automated and would be something like this. 
https://github.com/naveensrinivasan/scorecard/releases/tag/v1.4
=> Feat - implemented goreleaser for releases

README.md, checks/active.go
Fixes https://github.com/ossf/scorecard/issues/120
=> Remove releases from active check.

.github/CODEOWNERS
Included the codeowners for enabling branch protection "Require review from Code Owners"
=> feature - CODEOWNERS for GitHub branch protection feature

checks/branch_protected.go
Handle structs that could be nil while checking for branch protection.
=> fix - Handle nil structs in branch protection

.github/dependabot.yml
The third time is a charm.
Fixes the path of the actions.
```
Dependabot couldn't find a .yml.
Dependabot requires a .yml to evaluate your Github_actions dependencies. It had expected to find one at the path: /.github/workflows/.github/workflows/<anything>.yml.
If this isn't a Github_actions project, you may wish to disable updates for it in the .github/dependabot.yml config file in this repo.
```
=> Fix - dependabot githubactions location

.github/workflows/goreleaser.yaml, .goreleaser.yml
Used it against the fork.
```
./scorecard --repo=https://github.com/naveensrinivasan/scorecard  --checks Signed-Releases --show-details
Starting [Signed-Releases]
Finished [Signed-Releases]
RESULTS
-------
Signed-Releases: Fail 8
release found: v1.1.4
signed release artifact found: scorecard_1.1.4_checksums.txt.sig, url: https://api.github.com/repos/naveensrinivasan/scorecard/releases/assets/32224145
release found: v1.1.2
!! release v1.1.2 has no signed artifacts
release found: v1.1.1
!! release v1.1.1 has no signed artifacts
release found: v1.4
!! release v1.4 has no signed artifacts
found signed artifacts for 1 out of 4 releases
```
Feature …
=> Feature - signing releases

Makefile, cmd/root.go, e2e/executable_test.go, pkg/scorecard.go
Feature
Does not include metadata for scan
Included metadata that can be passed an argument to the command line. The same metadata will be returned with the `json` results.
The scorecard cron jobs would be scanning 1000's of repositories and would store the results in a format that would make it easier for the end-users to consume(CDN, API, Big Query). It would easier to filter based on this metadata.
For example, The envoy team dependencies are scanned right now as part of the cron. With this metadata, the …
=> Feature - Include metadata in the results

Makefile, checker/check.go, checks/checkforfile.go, checks/frozen_deps.go, checks/security_policy.go
No, the `e2e` test cover for these
Reduce the number of API calls to GitHub. Closes #221 
The current behavior uses up to `16` calls to GitHub API for checking the existence of Security.md 
Reduced the number of calls to GitHub API from 16 to a max of 2 calls.
Utilized tarball to download and check for the contents of those files.
No
=> Reduced GitHub API calls for security check

.golangci.yml
N/A
Address warnings
golang-ci warnings
```
golangci_lint: unexpected output on stderr: level=warning msg="[runner]
The linter 'interfacer' is deprecated due to: The repository of the linter has been archived by the owner."
level=warning msg="[runner] The linter 'maligned' is deprecated due to:
The repository of the linter has been archived by the owner. Use govet 'fieldalignment' instead."
```
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to …
=> Fix - Updated golangci-lint based on warnings

gitcache/main.go, gitcache/pkg/repourl.go
Fix the repo parsing from log.fatal to error. This was causing the
process to terminate.
Bug fix
The process was terminating because of log.Fatal
Changed the log.Fatal to error
None
=> Fix - Change log.fatal to error in URL parsing

Dockerfile.gsutil, cron/cron.sh
Bugfix
fix #269
Fixed the results.json to be wellformed from the cron job.
Changed the docker image from gsutil to cloudsdk:slim to `sed` binary which is being used with the cron.sh
Yes, the latest.json will be wellformed.
=> Fix - Made the results.json wellformed from cron

checks/checkforfile.go
Manually tested with the large repository `go run .  --repo=github.com/ApolloAuto/apollo  --checks=Frozen-Deps`
The subsequent PR's will update the test to include a large repository.
Bug Fix
Fixed the cron job eviction bug. Fixes #265
The httpcache client caches everything in memory and if the repository is large then the process gets evicted with oom.
Changed the implementation to use the standard http client to fetch the tarball.
* **Does this PR introduce a breaking change?** (What changes might users need …
=> Fix - out of memory error for large repository

cron/projects.txt
Adds Envoy deps statically to projects/cron.txt (and removes dupes). In the future this should be automated.
Part of https://github.com/ossf/scorecard/issues/287
=> :seedling: update envoy deps to projects/cron.txt statically

cron/main.go
Fixes https://github.com/ossf/scorecard/issues/323
* **What kind of change does this PR introduce?** 
* Zero pads months and dates to follow a MM-DD-YYYY format.
No zero padding, may output M-D-YYYY
Now zero pads.
Yes but switches back to consistent implementation.
=> :bug: Zero pad scorecard json filename.

pkg/scorecard.go
This is causing the Date to be incorrectly expanded as:
`<Day><Month>6-<Month>-<Day>` rather than `<Year>-<Month>-<Day>`
And causing the BQ import to still fail (#295)
=> :bug: Fix typo in scorecard date format.

.github/workflows/integration.yml
Reverts ossf/scorecard#354 as it breaks the `docker build`
🤦  I approved the previous PR from dependabot.
=> :seedling: Revert Bump actions/github-script from v3 to v4.0.1

.github/workflows/integration.yml
Including the commit from dependabot as the `ok-to-test` is failing
Bumps [actions/github-script](https://github.com/actions/github-script) from v3 to v4.0.2.
- [Release notes](https://github.com/actions/github-script/releases)
- [Commits](https://github.com/actions/github-script/compare/v3...a3e7071a34d7e1f219a8a4de9a5e0a34d1ee1293)
Signed-off-by: dependabot[bot] <support@github.com>
* …
=> :seedling: Bump actions/github-script from v3 to v4.0.2

roundtripper/roundtripper_test.go
- [n/a] Tests for the changes have been added (for bug fixes / features)
Test fix
I believe I introduced a bug in one of the tests in  PR [#348](https://github.com/ossf/scorecard/pull/348). In `roundtripper_test.go`, I added `t.Parallel()` inside the `for` loops. Because these tests are calling `os.Setenv` and `os.Getenv` for the same environment variables, it is possible for one test case to interfere with another. This appears to have happened in https://github.com/ossf/scorecard/runs/2487189008.
These tests …
=> 🌱 Fix intermittent test failure

roundtripper/roundtripper_test.go
This PR fixes issues from the [tparallel](https://github.com/moricho/tparallel/) linter (detects inappropriate usage of `t.Parallel()`). \
n/a
No
My first thought was to remove tparallel from the …
=> 🌱 Fix lint issues: tparallel linter

Makefile, repos/repo_result.go, repos/repo_url.go
This PR fixes issues from the [wrapcheck](https://github.com/tomarrell/wrapcheck/) linter (checks that errors returned from external packages are wrapped). \
n/a
No
=> 🌱 Fix lint issues: wrapcheck linter

roundtripper/roundtripper_test.go
This PR fixes issues from the [thelper](https://github.com/kulti/thelper/) linter (checks test helper functions call t.Helper()). \
n/a
No
Without this call to `t.Helper()`, if the first case of …
=> 🌱 Fix lint issues: thelper linter

Makefile, cmd/root.go, cmd/serve.go, cron/main.go, pkg/scorecard.go
Updates the RunScorecard function API.
Currently, RunScorecards library:
i) forces gitcache to be used for every call.
ii) instantiates a new HTTP and related clients per-repo-per-check.
i)Allow clients to pass in their custom HTTP and GitHub clients.
ii) More efficient use of these clients due to single instantiation.
No (hopefully). Checked cron/main.go locally, but can only be fully …
=> ✨  Update RunScorecards API

cron/bq/transfer.go, cron/config/config.go, cron/config/config.yaml, cron/config/config_test.go, cron/config/testdata/basic.yaml, cron/main.go, go.mod, go.sum
Uses TRUNCATE instead of APPEND to load GCS data into BQ.
Currently, the BQ scheduled data transfer service uses APPEND to load data into BQ table. But, we want the TRUNCATE behaviour for reasons discussed here: https://github.com/ossf/scorecard/issues/366. However, this can't be done for 2 reasons:
(i) the scheduled service does not allow for this option
(ii) TRUNCATE requires that all input data has the same `date` field
This PR implements that behaviour.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to …
=> 🌱  Use TRUNCATE to load data into BigQuery

go.mod, roundtripper/github.go, roundtripper/roundtripper.go
Remove the oauth library usage which was causing issues in token access. 
The `oauth.Token()` fn relies on [`Token.Expiry` field](https://github.com/golang/oauth2/blob/f6687ab2804c/token.go#L50). Without this, it always [returns the same token](https://github.com/golang/oauth2/blob/f6687ab2804c/oauth2.go#L301). This was unintentionally working fine before https://github.com/ossf/scorecard/pull/461 since we always created a new instance of the oauth client. 
For our usecase, it is enough if we set the correct `Authorization` header. So updating to use that instead of the oauth library.
FYI, this issue is causing the cron job to be stuck forever.
* …
=> 🐛  Fix bug in GitHub token access

cron/monitoring/exporter.go
Adds options to Stackdriver exporter:
i) `MonitoredResource` limits the metric to be recorded against `gke_container` instead of `global`
ii) `Timeout` increases the deadline for API calls to Stackdriver.
No.
=> 🐛  Add options to Stackdriver exporter

checks/active.go, checks/branch_protected.go, checks/branch_protected_test.go, checks/ci_tests.go, checks/cii_best_practices.go, checks/code_review.go, checks/contributors.go, checks/frozen_deps.go, checks/fuzzing.go, checks/packaging.go, checks/pull_requests.go, checks/sast.go, checks/security_policy.go, checks/signed_releases.go, checks/signed_tags.go, cron/main.go, cron/worker/main.go
In context of https://github.com/ossf/scorecard/issues/512, removing checks which use ArchiveURL.
No.
=> 🌱  Export registered check names 

.golangci.yml, checks/checkforfile.go, cmd/root.go, cron/data/iterator.go
- [n/a] Tests for the changes have been added (for bug fixes / features)
Adding one of the new linters listed in #173. [errorlint](https://github.com/polyfloyd/go-errorlint) checks for `fmt.Errorf` that uses `%v` instead of `%w` with an existing error and checks that comparisons between errors use `errors.check`.
=> 🌱 Add new linter: errorlint

Makefile, cron/config/config.go, cron/config/config.yaml, cron/config/config_test.go, cron/main.go, cron/monitoring/exporter.go, cron/monitoring/printer.go
Adds a factory for OpenCensus exporter. This can be used in tests to mock a `PrintExporter`. Fixes https://github.com/ossf/scorecard/issues/510
No.
=> ✨  Factory for OpenCensus Exporter to use in tests

checks/automatic_dependency_update.go, checks/checks.md, checks/checks.yaml, e2e/automatic_deps_test.go
Feature
#179
* Checks if the dependencies are automatically updated.
None
None
=> :sparkles: Automatic dependency update checks

.github/workflows/integration.yml, .github/workflows/main.yml
Bug fix
e2e are failing #573
The validate and the e2e are failing because of the bug in golang https://github.com/golang/go/issues/44129
This fix is a temporary workaround.
None
None
=> 🌱  Fixes GitHub workflow failures

checks/checkforcontent.go, checks/frozen_deps_test.go, checks/permissions_test.go
bug fix
tarball files were truncated if the call to `tr.Read` did not return all the bytes at once.
fix the above.
no
=> 🐛 Fix truncated file extraction from tarball

checks/frozen_deps.go, checks/frozen_deps_test.go, checks/shell_download_validate.go, checks/testdata/script-bash, checks/testdata/script-sh, checks/testdata/script.sh
feature
we don't support.
we support `curl | bash` type detection for shell scripts.
no
A lot of refactoring has happened in the code to be able to share the detection for docker, shell, and later makefiles/github workflows. The refactoring simplifies things, though.
=> ✨ Check for shell script's insecure download

pkg/scorecard.go, pkg/scorecard_result.go
Moves `repos.RepoResult` to `pkg.ScorecardResult`. This decouples the `repos` package from `checker` package. This allows us to import `repos` inside `checker` as intended. Today, we were unable to do this since `repos.RepoResult` depended on `checker`.
No.
=> 🐛 Move `repos.RepoResult` -> `pkg.ScorecardResult`

cmd/root.go
Fixes #673
No error is returned if invalid checks are provided.
An error is returned if an invalid check is provided.
```bash
scorecard --repo=github.com/ossf/scorecard --checks=invalid-check
2021/07/13 08:44:22 Invalid check: invalid-check
```
Maybe, but only if users are providing `checks` arguments which are invalid anyway.
=> :bug: Added error for invalid checks

README.md, cmd/root.go, roundtripper/roundtripper.go
feature
we only use GITHUB_AUTH_TOKEN
we add GITHUB_TOKEN and GH_TOKEN. This is helpful because some existing tools use different naming, so re-using the names requires users to set the env variable once only across multiple tools.
no
=> ✨ Add more github token names for env variable

README.md
The docs instructions for installing locally would `go get` an older version of scorecards. This updates to `v2`.
Signed-off-by: Appu Goundan <appu@google.com>
=> 📖 Update local install instructions to use v2

Makefile, cmd/version.go
`scorecard version` will print out something like
```
GitVersion:     v2.0.0-73-g7fd331a-dirty
GitCommit:      7fd331adf2a0f6578b78d951e16646da03e6a6f5
GitTreeState:   dirty
BuildDate:      2021-07-27T14:14:34Z
GoVersion:      go1.16.4
Compiler:       gc
Platform:       linux/amd64
```
Signed-off-by: Appu Goundan <appu@google.com>
=> ✨Add version cli subcommand

checks/branch_protected.go, checks/branch_protected_test.go
Bug fix
When `github.Protection.RequiredPullRequestReviews == nil`, then `requiresThoroughReviews()` emits panic.
(it seemed caused by PR reviews are disabled in the repo or lack of GitHub token's permission?)
When `github.Protection.RequiredPullRequestReviews == nil`, then `requiresThoroughReviews()` does not emit panic.
No.
=> 🐛  Fix panic error when RequiredPullRequestReviews is nil

.goreleaser.yml
Feature
osx didn't have arm64 builds
Removed the arm64 ignore from goreleaser
None
None
=> :sparkles: Scorecard builds for osx arm64

cron/bq/main.go, cron/config/config.go, cron/config/config.yaml, cron/config/config_test.go, cron/controller/main.go
Make a HTTP POST request to webhook URL (when non-empty), on a successful completion of cron job.
No.
=> ✨ Post to webhook on successful cron job completion

cron/worker/main.go
Log runtime failures in cron job instead of skipping them.
No.
=> ✨ Log runtime failures in cron job

Dockerfile, cron/bq/Dockerfile, cron/controller/Dockerfile, cron/webhook/Dockerfile, cron/worker/Dockerfile
Use the same Golang image across Dockerfiles.
No.
=> 🐛 Use consistent Golang image across Dockerfiles

docs/checks.md, docs/checks/checks.yaml
Docs
*  Fixed a few typos
*  Rephrased a few statements.
None
None
=> :book: Fixed the typos and rephrased some

checks/contributors.go, clients/contributor.go, clients/githubrepo/client.go, clients/githubrepo/contributors.go, clients/repo_client.go, e2e/contributors_test.go
Use RepoClient API for Contributors check.
No.
=> ✨ Use RepoClient API for Contributors check

checks/sast.go, clients/githubrepo/client.go, clients/githubrepo/search.go, clients/githubrepo/search_test.go, clients/repo_client.go, clients/search.go
Update SAST check to use the new RepoClient.Search API.
No.
=> 🐛 Use RepoClient.Search API in SAST check

docs/checks/checks.yaml, pkg/scorecard_result.go
feature
no metadata
add tags so we can use them in SARIF. (tags are optional in SARIF)
no
=> ✨ SARIF 3: add flag to yaml

clients/githubrepo/client.go
=> 🐛 Nil pointer dereference

repos/repo_url.go, repos/repo_url_test.go
New feature outlined #780 
Currently, it does not accept `repo/owner` format
New behaviour will accept `repo/owner` format and using `github.com` as the default domain.
No
=> :sparkles:  fix: add github.com as default for owner/repo parameter 

clients/githubrepo/client.go, cron/data/projects.release.csv
Some repos can redirect to different owner/name. Eg:
- github.com/chromium/ct-policy -> github.com/GoogleChrome/CertificateTransparency
- github.com/flavioislima/HeroicGamesLauncher -> github.com/Heroic-Games-Launcher/HeroicGamesLauncher
- github.com/farag2/Windows-10-Sophia-Script -> github.com/farag2/Sophia-Script-for-Windows
No.
=> 🐛 Handle GitHub repos with redirects

cron/worker/main.go
Removes token heavy checks from the cron job to try and improve scaling.
No.
=> ✨ Remove token-heavy checks from cron job

checks/binary_artifact.go, pkg/scorecard_result.go
feature
no structured detail for binary artifacts
* **What is the new behavior (if this is a feature change)?** 
* structured detail for binary artifacts
no
=> SARIF 5: binary artifact check uses new structure

cron/k8s/worker.release.yaml, cron/k8s/worker.yaml
Cron workers were getting evicted since no ephemeral storage was requested. Explicitly requesting ephemeral-storage to avoid this.
No.
=> 🐛 Add ephemeral-storage to cron worker

README.md
=> 📖  Move authentication section in README.md to the beginning of the Usage section.

pkg/json.go, pkg/sarif.go, pkg/sarif_test.go, pkg/scorecard.go, pkg/scorecard_result.go, pkg/testdata/check1.sarif, pkg/testdata/check2.sarif, pkg/testdata/check3.sarif, pkg/testdata/check4.sarif, pkg/testdata/check5.sarif, pkg/testdata/check6.sarif
feature
no hash are stored in the results.
add a commit hash to the results.
no
close https://github.com/ossf/scorecard/issues/891
=> ✨  Add hash to results (JSON, SARIF)

checks/security_policy.go, clients/githubrepo/tarball.go, clients/githubrepo/tarball_test.go, cmd/root.go, cron/config/config.go, cron/worker/main.go, pkg/scorecard.go
Replace `errors.As` calls with `Is` to avoid overwriting original error values. Thanks to @laurentsimon https://github.com/ossf/scorecard/pull/900#discussion_r695266616
No.
=> 🐛 Replace `errors.As` with `Is`

checks/branch_protection_test.go, checks/permissions_test.go, checks/pinned_dependencies_test.go, e2e/binary_artifacts_test.go, e2e/branch_protection_test.go, e2e/ci_tests_test.go, e2e/cii_best_practices_test.go, e2e/code_review_test.go, e2e/contributors_test.go, e2e/dependency_update_tool_test.go, e2e/fuzzing_test.go, e2e/maintained_test.go, e2e/packaging_test.go, e2e/permissions_test.go, e2e/pinned_dependencies_test.go, e2e/sast_test.go, e2e/security_policy_test.go, e2e/signedreleases_test.go, e2e/vulnerabilities_test.go, utests/utlib.go
- Use `cmp` package for result comparison
- Update `Errors` to `Error`
No.
=> 🌱 Update test utils

cron/worker/json.go, cron/worker/main.go, pkg/common.go
feature
use same json for cron and scorecard
separate the two json. This way we can change the scorecard JSON format without affecting the cron job.
We already decoupled the scorecard JSON format from the internal scorecard structure used to store result. This is the next step.
no
This PR …
=> ✨ Decouple scorecard json from cron json

cron/config/config.yaml, cron/config/config_test.go, cron/k8s/transfer.release.yaml
https://github.com/ossf/scorecard/blob/main/cron/bq/main.go#L103 expects a fractional value between 0-1. Currently we were specifying percentages.
No.
=> 🐛 Specify fractions instead of percentage

cmd/root.go, cmd/version.go, cron/worker/json.go, go.mod, go.sum, pkg/json.go, pkg/json.v2.schema, pkg/json_test.go, pkg/sarif.go, pkg/sarif_test.go, pkg/scorecard.go, pkg/scorecard_result.go, pkg/scorecard_version.go, pkg/testdata/check1.json, pkg/testdata/check1.sarif, pkg/testdata/check2.json, pkg/testdata/check2.sarif, pkg/testdata/check3.json, pkg/testdata/check3.sarif, pkg/testdata/check4.json, pkg/testdata/check4.sarif, pkg/testdata/check5.json, pkg/testdata/check5.sarif, pkg/testdata/check6.json, pkg/testdata/check6.sarif, scripts/version-ldflags
feature
lack of info in JSON format
1. JSON format uses lower-case letter for fields (OSV, GitHub API, etc all use lowercase fields)
2. Add scorecard's hash and version to JSON
3. Retrieve version/hash information automatically
4. Move build info under `pkg/`
no
=> ✨  Improve JSON format

checks/ci_tests.go, checks/sast.go, clients/checkruns.go, clients/githubrepo/checkruns.go, clients/githubrepo/client.go, clients/mockrepo/client.go, clients/repo_client.go
Add and use a new RepoClient API for ListcheckRunsForRef.
No.
=> 🌱 Add RepoClient API for ListCheckRunsForRef

checks/ci_tests.go, clients/githubrepo/client.go, clients/githubrepo/statuses.go, clients/mockrepo/client.go, clients/repo_client.go, clients/statuses.go
Use a new ListStatuses for CITests check.
No.
=> 🌱 Add and use RepoClient API for ListStatuses

checks/pinned_dependencies.go, checks/pinned_dependencies_test.go, checks/testdata/workflow-mix-github-and-non-github-not-pinned.yaml, checks/testdata/workflow-mix-github-and-non-github-pinned.yaml, checks/testdata/workflow-mix-pinned-and-non-pinned-github.yaml, checks/testdata/workflow-mix-pinned-and-non-pinned-non-github.yaml, checks/testdata/workflow-non-github-pinned.yaml
#802 
feature update
close https://github.com/ossf/scorecard/issues/802
=> :sparkles: Give low importance to github-owned actions

README.md
This modifies README.md to add hyperlinks
directly to each of the details in `docs/checks.md`.
That way, people who want to know more about a specific check
can jump immediately to that information.
Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>
=> 📖 README.md: Add hyperlinks to docs/checks.md

docs/checks.md, docs/checks/internal/checks.yaml
This fixes the current misleading text about the CII
Best Practices badge. It currently says that "This badge tells us the
repo maintainers are aware of best development practices." - but
merely being "aware" doesn't earn a passing badge.
There's a long list of requirements to earn a passing badge;
we should give a sense of them here.
Note that this only checks for "passing", not silver or gold.
Note: This replaces a previous (messed-up) pull request #1009.
Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>
=> 📖 Fix CII Best Practices badge info

.github/workflows/main.yml
Bug fix
https://github.com/ossf/scorecard/issues/942
Fixes the permission for main.yml
None
None
=> :seedling: Fixes permission for main.yml action

docs/checks.md, docs/checks/internal/checks.yaml
Automated tools normally have some false negatives,
some false positives, or both. However, some scorecard criteria
are *especially* prone to false negatives (where a
project meets the criterion but the tool says it doesn't).
This commit adds warning text about false negatives for
criteria that are especially prone to false negatives.
In all cases the problem is that there are *many* ways to
implement the criterion, so while the tool may detect some
cases, there are countless other situations it will fail to detect.
While this doesn't *fix* the problem, warning the humans
will encourage them to double-check these criteria before
making decisions. Sometimes this is the best you can do, and
it's better than not having a warning.
Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>
=> 📖 Warn when checks are prone to false negatives

docs/checks/internal/checks.yaml
Make various improvements to the text on packaging.
* The original text assumes that only software developers install software
packages, which is absurd; end-users install software packages all
the time.
* The original text seemed to assume that there are only
language-level packages, but system-level packages & containers
are a thing :-). At least acknowledge them.
Also, this doesn't make sense in some cases
(e.g., software specific to one website that's updated through commits,
or IoT software where there are no "packages" - you
upload the entire image); that should be admitted.
* Fix main text to stop using "you/your" to mean "project developer".
There are at least two *different* readers: (1) developers of the project
being measured and (2) potential users of the project being …
=> 📖 Improve text on Packaging

go.mod, go.sum
Bug Fix
The github.com/buger/jsonparser has this vulnerability.
```
"vulns": [
{
"id": "GO-2021-0089",
"package": {
"name": "github.com/buger/jsonparser",
"ecosystem": "Go"
},
"details": "Parsing malformed JSON which contain opening brackets, but not closing brackes,\nleads to an infinite loop. If operating on untrusted user input this can be\nused as a denial of service vector.\n",
"affects": {
"ranges": [
{
"type": "SEMVER",
"fixed": "0.0.0-20200321185410-91ac96899e49"
}
]
},
"aliases": [
"CVE-2020-10675"
], …
```
=> :seedling: Fix GO-2021-0089 vulnerability

Makefile, tools/go.mod, tools/go.sum, tools/tools.go
Feature
At present we don't have a way to identify any new dependencies to go.mod that have osv/cve.
With this it will query the osv.dev for any vulnerabilities and report if it found any.
It also has an option to ignore any vulnerabilities if we chose to ignore.
At present we are ignoring 3 osv that are in our dependencies.
https://github.com/naveensrinivasan/stunning-tribble
None
* …
=> :seedling: Check for OSV for a go.mod changes to scorecard

cron/format/json.go, cron/format/json.v2.schema, cron/format/json_test.go, cron/format/testdata/check1.json, cron/format/testdata/check2.json, cron/format/testdata/check3.json, cron/format/testdata/check4.json, cron/format/testdata/check5.json, cron/format/testdata/check6.json, pkg/json.go, pkg/json_test.go, pkg/scorecard_result.go
feature
see https://github.com/ossf/scorecard/issues/1040 and https://github.com/ossf/scorecard/pull/1046
see https://github.com/ossf/scorecard/issues/1040 and https://github.com/ossf/scorecard/pull/1046
no
=> ✨ Add aggregate score to cron JSON

checks/code_review.go, clients/commit.go, clients/githubrepo/graphql.go, clients/pull_request.go, clients/user.go
bug
see https://github.com/ossf/scorecard/issues/895
see https://github.com/ossf/scorecard/issues/895
yes
close https://github.com/ossf/scorecard/issues/895
=> 🐛  Fix invalid code review

docs/checks.md
This commit commits the result of `make generate-docs`,
producing an updated `docs/checks.md` file, now that the
source documentation files have been changed.
Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>
=> :book: Regenerate docs/checks.md

.github/workflows/goreleaser.yaml
With the latest release of `ghaction-import-gpg`, the input names have been changed. 
No.
=> 🐛 `gpg-private-key` in goreleaser

go.mod, go.sum
Bug fix
Fixes OSV GO-2020-0018 https://github.com/satori/go.uuid/issues/73
None
=> :seedling: Update the uuid library to avoid CVE

clients/localdir/client.go, clients/localdir/client_test.go, clients/localdir/repo.go, clients/repo_client.go, cmd/root.go, cron/format/mock_doc.go, docs/checks/doc.go, docs/checks/impl.go, docs/checks/internal/checks.yaml, docs/checks/internal/reader.go, docs/checks/internal/validate/main.go, pkg/mock_doc.go, pkg/scorecard.go
This is a feature with no breaking changes. 
close https://github.com/ossf/scorecard/issues/1184
The general behavior for check selection is as follows:
1. `--repo=X` => uses all checks supported by the repo interface
2. `--repo=X --check=Y` => uses check Y and verifies it's supported by repo interface
3. `--repo=X --policy=Z` => uses all checks defined in the policy file AND supported by repo interface
4. `--repo=X --policy=Z --checks=Y` => uses Y AND verifies Y is defined in the policy and verifies Y checks are supported by the repo interface
The one thing I don't like is that, if a user passes a policy, we're silently discarding checks not supported by the interface. I wonder if this may be confusing for users.
=> ✨ Use checks.yaml to store which repo types are supported by each check

docs/checks/internal/validate/main.go
This PR adds validation to ensure the `repos` field in the checks.yaml file is consistent with the check's implementation. It currently uses regex to look for repo client APIs, but later we could use a callgraph if needed.
No breaking change in this PR.
=> ✨ Validate check.yaml's repo interface support

.github/CODEOWNERS
We recently changed CODEOWNER file, but it now automatically adds several people as reviewers for all PRs. This is overwhelming.
Let's only use this for the documentation and workflows.
=> 🐛  Use only olivekl@ in CODEOWNER

checks/permissions.go, checks/permissions_test.go
Bug fix
When a non-yaml file (such as a shell or python file) is present in `.github/workflows`, the check will fail with 
```
|--------|-------------------|--------------------------------|--------------------------------|------------------------------------------------------------------------------------------------------------------|
| SCORE  |       NAME        |             REASON             |            DETAILS             |                                            DOCUMENTATION/REMEDIATION                                             | …
```
=> 🐛 Token permission check was failing on non-yaml files

README.md
Updated the community links to be more accessible. Took the idea from https://github.com/tektoncd/community/blob/main/working-groups.md#chains
=> 📖  Updated the community links

docs/checks/internal/validate/main.go
This fixes some spelling mistakes in a previous PR I merged.
No breaking changes, no code changes.
=> ✨ Fix spelling mistakes in comments

cmd/root.go, pkg/sarif.go, pkg/sarif_test.go, pkg/testdata/check1.sarif, pkg/testdata/check2.sarif, pkg/testdata/check3.sarif, pkg/testdata/check4.sarif, pkg/testdata/check5.sarif, pkg/testdata/check6.sarif, pkg/testdata/check7.sarif, pkg/testdata/check8.sarif
This adds support for pull request in the GH action.
The changes required updating how we generate our SARIF results.
This https://github.com/github/codeql-action/issues/811 is an improvement that would be nice, but non-blocking.
=> ✨  Pull request support for GitHub action

pkg/sarif.go, pkg/testdata/check8.sarif
This makes the generation of sarif results deterministic: it will always use the same order for run categories and details.
Found in https://github.com/ossf/scorecard/pull/1232#issuecomment-964754088
=> 🐛  Make sarif generation deterministic

Makefile, docs/checks/internal/validate/main.go
We currently do not validate documentation in pre-submit checks. This is particularly important as the repo interfaces support only a specific number of checks that are defined via the `repos` field in the checks.yaml. The field is used to determined which checks are run, so a change in behavior needs to be detected.
=> 🐛 Validate doc on pre-submit

checks/sast.go
Some SASTs like LGTM don't analyze PRs where code hasn't been changed,
which leads to their status being "neutral" there.
It's a follow up to https://github.com/ossf/scorecard/pull/1232#issuecomment-965552702
I'm not sure what to do about one-offs like the one
mentioned in https://github.com/ossf/scorecard/pull/1232#issuecomment-965585962
that shouldn't affect the aggregate score but it can probably
be fixed later.
cc @laurentsimon
=> :sparkles:SAST: no longer skip "neutral" checks

checks/security_policy.go
It was tested with [the systemd project](https://github.com/systemd/systemd/security) where the security policy
is kept in [docs/SECURITY.md](https://github.com/systemd/systemd/blob/main/docs/SECURITY.md). Without this patch `scorecard`
says that the security policy can't be found.
=> :bug:Security-Policy: really look for the security policy

checks/fileparser/github_workflow.go, checks/pinned_dependencies.go
=> 🐛 Fix nil-ptr access bug

Makefile
Tooling bug fix
I have my GOPATH set to a different location:
```
~/code/ossf/scorecard(main)$ echo $GOPATH
/home/chris/.go
```
The line
```
GOPATH := $(go env GOPATH)
```
appears to be overwriting my environment variable and turning it into a local variable. If I modify the install target to:
```
.PHONY: install
install: ## Installs all dependencies needed to compile Scorecard
install: | $(PROTOC)
@echo Installing tools from tools/tools.go
echo $$GOPATH
go env GOPATH
cd tools; cat tools.go | grep _ | awk -F'"' '{print $$2}' | xargs -tI % go install %
```
It outputs:
``` …
```
=> 🌱 `make install` was not installing to GOPATH

checks/ci_tests.go
Projects with a lot of different CI services use both and the check
should take that into account so as not to report that PRs
like https://github.com/systemd/systemd/pull/21329
with 28 successful, 4 failing, and 2 neutral checks were merged
without any tests.
Without this patch `scorecard` says that 5 out 30 PRs were merged
without running tests:
```
"Debug: CI test found: pr: 21299, context: ci/semaphoreci/pr: Debian autopkgtest (LXC): https://api.github.com/repos/systemd/systemd/statuses/472a52d22b9f505a4c284e7ad020ea1b3728466d",
"Debug: CI test found: pr: 21300, context: ci/semaphoreci/pr: Debian autopkgtest (LXC): https://api.github.com/repos/systemd/systemd/statuses/cf35602cbc1bffcb5ab01153af153d0bf4e5a7e9",
"Debug: CI test found: pr: 21301, context: ci/semaphoreci/pr: Debian …
```
=> :bug: CI-Test: stop assuming either "statuses" or "check runs" are used

checks/branch_protection.go, checks/branch_protection_test.go
=> 🐛 Fix nil-ptr dereference

checks/permissions.go, checks/permissions_test.go, checks/testdata/github-workflow-permissions-packages-writes.yaml, checks/testdata/github-workflow-permissions-release-writes.yaml, utests/utlib.go
This ignores, i.e. does not show a warning, if the `contents:write` is used in a packaging workflow.
close https://github.com/ossf/scorecard/issues/1099
=> ✨ Reduce false positives in Token-Permissions for contents permission

checks/fuzzing.go, e2e/binary_artifacts_test.go, e2e/branch_protection_test.go
Sigh, more broken e2e tests. Hopefully won't continue after #1286 .
Fixes #1289 
No.
=> 🐛 Fix broken e2e tests

.github/workflows/scorecard-analysis.yml
This should help to prevent various linters from complaining about
trailing whitespaces when the file is copy-pasted to other repositories:
```
.github/workflows/scorecard-analysis.yml:2: trailing whitespace.
+on:
.github/workflows/scorecard-analysis.yml:18: trailing whitespace.
+
.github/workflows/scorecard-analysis.yml:40: trailing whitespace.
+
```
=> :sparkles:ci: drop trailing whitespaces

checks/pinned_dependencies.go
Failing repos:
- github.com/johnmcfarlane/cnl
- github.com/shahoob/easePackageCheck
- github.com/mongodb/atlas-osb
No.
=> 🐛 More nilptr issues

cron/config/config.go, cron/config/config.yaml, cron/config/config_test.go, cron/k8s/worker.release.yaml, cron/worker/main.go
Start running the `Dangerous-Workflow` check in the release tests to build confidence before we enable it in production.
No.
=> 🌱 Run `Dangerous-Workflow` in release tests

.github/workflows/integration.yml
=> ✨ Use `pull_request_target` + protected env for e2e

checks/branch_protection.go, checks/branch_protection_test.go, docs/checks.md, docs/checks/internal/checks.yaml, e2e/branch_protection_test.go
Update score to work like 'stages':
- first stage: force push, force deletion. if admin, enforce admins. Those give 3/10
- second stage: review >= 1. for admins, up-to-date branch. Those gives 6/10. Maybe up-to-date branch could go to first stage?
- third stage: status checks defined. Gives 8/10. 
- fourth stage : reviews >= 2. Gives 9/10
- fifth stage: for admins, dismissal (very hard to use). Gives 10/10
If a stage is not satisfied, the score won't go up regardless of the settings of the next stages. Warn/Info messages are shown for all stage, regardless of the score.
I scorecard is run without admin access, the admin settings are ignored.
@olivekl how shall I word this in the checks.yaml?
FYI, I'm working on the unit tests right now but that should not hamper the review.
=> ✨ Update score for branch protection with levels

.github/workflows/integration.yml
See this line https://github.com/ossf/scorecard/blob/main/.github/workflows/integration.yml#L36
We're not checking out the PR using `ref`, so we're effectively testing the main branch.
I unfortunately pushed a breaking change https://github.com/ossf/scorecard/pull/1316
To merge it it, we will need to disable integration tests temporarily in the GitHub UX.
close https://github.com/ossf/scorecard/issues/1317
=> 🐛 Fix integration test

e2e/branch_protection_test.go
See title. There was old code checking the Fail/Pass that is failing because the score calculation has changed.
The PR validation complains about the description not being long enough, so I've added this line.
=> 🐛 Fix e2e branch protection test

checks/fileparser/github_workflow.go, checks/fileparser/github_workflow_test.go, checks/testdata/github-workflow-shells-all-windows-matrix-include-empty.yaml, checks/testdata/github-workflow-shells-all-windows-matrix-include.yaml
Bug fix
This [workflow file](https://github.com/mahmoud/boltons/blob/270e974975984f662f998c8f6eb0ebebd964de82/.github/workflows/tests.yaml) was causing an error for the Pinned-Dependencies check. It was because the only OSes listed in strategy.matrix were in the `include` section. Previously, `fileparser.JobAlwaysRunsOnWindows()` may have returned incorrect results if `strategy.matrix.os` and 'strategy.matrix.include` had different operating systems listed. That will be fixed here.
Part of https://github.com/ossf/scorecard/issues/839#issuecomment-974667652.
* **Does this …
=> 🐛 Get OSes from matrix.include if present

checks/fileparser/listing.go, checks/fileparser/listing_test.go, checks/pinned_dependencies.go
Bug fix
This [Dockerfile](https://github.com/traefik/mesh/blob/957da2d9ca4d4cdd4e00d0bdfbb9f5ae4f2685ff/tmpl.Dockerfile) was causing an error for the pinned dependencies check. It is a template Dockerfile, so it was unable to be parsed.
Part of https://github.com/ossf/scorecard/issues/839#issuecomment-974667652
Template Dockerfiles will be skipped for this check. I did some searching of Github for different formats that filenames for template Dockerfiles take, and so this should cover most of them.
* **Does …
=> 🐛 Skip pinned dependencies check for template Dockerfiles

checks/dangerous_workflow.go
* refactors dangerous-workflow to use the actionlint library 
Part of https://github.com/ossf/scorecard/issues/839
cc @chrismcgehee
=> :seedling: update dangerous workflow to use actionlint

checks/pinned_dependencies_test.go, checks/shell_download_validate.go, checks/testdata/Dockerfile-pkg-managers, checks/testdata/github-workflow-pkg-managers.yaml, checks/testdata/script-pkg-managers
See discussion in https://github.com/ossf/scorecard/issues/1306#issuecomment-974539197
We've had a TODO in https://github.com/ossf/scorecard/blob/main/checks/shell_download_validate.go#L484 for a while.
This means that any `pip install`, `pip --upgrade`, `pip -U` are flagged, as is already the case.
We only allow: `pip install -r <> --require-hashes` and `pip install *.whl`
=> ✨  Allow pip install with --require-hashes only

docs/checks.md
docs seems out of sync and causing a license check failure.
no breaking change in this PR.
=> 🐛  Generate docs

README.md, cmd/root.go
2.Fix the typo of rubygems
docs update
#1168 
=> 📖 Add the check Dangerous-Workflow

checks/pinned_dependencies.go, e2e/branch_protection_test.go, e2e/pinned_dependencies_test.go
The code looking for lock files in package managers is incorrect:
- libraries vs cli https://github.com/ossf/scorecard/issues/689 => false positives
- we only look for lock files in the top folder => false positives
This PR disables this part of the code until we have a better solution. Looking for a lock files next to a manifest file is also error prone: users may copy lock files into dockerfiles from different locations, etc.
I think the right approach is to ensure any scripted installation command requires all dependencies and transitive dependencies to be pinned by hash:
- https://github.com/ossf/scorecard/pull/1314 - `npm ci`
- https://github.com/ossf/scorecard/pull/1313 - `pip install -r <> --require-hashes`
Updates should be performed by tools (dependabot/renovabot), never in …
=> 🐛 Disable pinning lock file search in repo

checks/pinned_dependencies.go
Add whether the non-pinned action is GitHub-owned or not.
=> ✨ update log msg for non-pinned actions

checks/code_review.go
to make it easier to figure out whether those PRs are really merged
without code review or whether there is a bug in scorecard like
https://github.com/ossf/scorecard/issues/1260 that prevents it
from finding reviewed PRs. Other than that, the "CI-Tests" check
already shows "untested" PRs so it seems the "Code-Review" check
should follow suit.
=> ✨ Code-Review: show PRs merged without code review

checks/errors.go, checks/permissions.go, checks/permissions_test.go, checks/testdata/github-workflow-permissions-jobs-only.yaml, docs/checks.md, docs/checks/internal/checks.yaml, e2e/permissions_test.go
We currently give a score of 0 if all job define their permissions but the top level is not.
This PR removes one point if the top level permissions are not defined but the run level ones are all defined.
See https://github.com/ossf/scorecard/issues/1128#issuecomment-973236716 for more details.
closes https://github.com/ossf/scorecard/issues/1128
=> ✨ Token-Permission: Allow top level permissions not defined if all run level permissions are

checks/ci_tests.go, clients/githubrepo/statuses.go, clients/statuses.go
Apparently some projects like systemd and bcc put links (containing
the word "Jenkins") to their Jenkins instances in target urls.
https://buildbot.iovisor.org/jenkins/job/bcc-pr/1157/
https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/8288/
It's a follow-up to https://github.com/ossf/scorecard/pull/1293#issuecomment-976384882
=> ✨ CI-Tests: look for test-related strings in target urls as well

README.md
Adds installation instructions for HomeBrew, NixOS, and Arch Linux
N/A
N/A
No
=> :book: docs: add installation instructions for mac and linux

checks/dangerous_workflow.go, checks/dangerous_workflow_test.go, checks/testdata/github-workflow-dangerous-pattern-trusted-script-injection.yml, checks/testdata/github-workflow-dangerous-pattern-untrusted-inline-script-injection.yml, checks/testdata/github-workflow-dangerous-pattern-untrusted-multiple-script-injection.yml, checks/testdata/github-workflow-dangerous-pattern-untrusted-script-injection-wildcard.yml, checks/testdata/github-workflow-dangerous-pattern-untrusted-script-injection.yml, docs/checks.md, docs/checks/internal/checks.yaml
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process
Feature: Adds script injection to Dangerous-Workflow check
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
part of https://github.com/ossf/scorecard/issues/426
Adds a new check. 
**feedback** …
=> :sparkles: Add Script Injection to Dangerous-Workflow

cmd/root.go, pkg/sarif.go, pkg/sarif_test.go, pkg/testdata/check6.sarif
This uses a default "no-source-file" for results that don't have explicit files to display.
Since we're removing policy files from the GH action, that makes it less confusing for users.
=> ✨ Don't use the policy filename in SARIF results

pkg/sarif.go, pkg/testdata/check1.sarif, pkg/testdata/check2.sarif, pkg/testdata/check3.sarif, pkg/testdata/check4.sarif, pkg/testdata/check5.sarif, pkg/testdata/check6.sarif, pkg/testdata/check7.sarif, pkg/testdata/check8.sarif
This makes a few changes to comply with GH-specific rules:
1. rule ID should be different from rule name
2. rule ID should be pascal case
In addition, I've create a category for the branch protection check, to allow us to run it alone without running other checks - see https://github.com/ossf/scorecard-action/issues/19
=> ✨ Comply with GH-specific rules for SARIF

checks/fileparser/github_workflow.go, checks/packaging.go, checks/packaging_test.go, checks/permissions.go, checks/permissions_test.go, checks/testdata/github-workflow-packaging-cargo.yaml, checks/testdata/github-workflow-packaging-docker-action.yaml, checks/testdata/github-workflow-packaging-docker-push.yaml, checks/testdata/github-workflow-packaging-gem.yaml, checks/testdata/github-workflow-packaging-go.yaml, checks/testdata/github-workflow-packaging-gradle.yaml, checks/testdata/github-workflow-packaging-maven.yaml, checks/testdata/github-workflow-packaging-npm-github.yaml, checks/testdata/github-workflow-packaging-npm.yaml, checks/testdata/github-workflow-packaging-nuget.yaml, checks/testdata/github-workflow-packaging-pypi.yaml, checks/testdata/github-workflow-permissions-run-write-codeql-comment.yaml
Packaging)
Feature
When the Token-Permission check makes logs for packaging workflow, it does not set the line number. Same thing for the Packaging check.
Closes https://github.com/ossf/scorecard/issues/886
All logs from the Token-Permission and Packaging checks will include line numbers. This PR also makes the check for packaging workflow more precise. Instead of doing a string search for an action name, it will parse the workflow file and check that a `uses` field on a step matches the action name.
* **Does …
=> ✨ Adding line numbers for rest of Token-Permissions (and by extension, Packaging)

.ko.yaml, Makefile, cloudbuild/scorecard.yaml
Progress toward https://github.com/ossf/scorecard/issues/1366
Bugfixes
`make ko-build-everything` fails for me.
`make ko-build-everything` builds images, but does not push them.
Images are built for all binaries, not just `scorecard`, and (if `--push=false` is removed) are pushed to, e.g.:
```
gcr.io/imjasonh/scorecard-github-server/server@sha256:a142bd9ad872d94fc55e3b6b92b24d862f0ebfd044fec1154d1e6872544e0a1a
```
SBOMs are also attached to each platform-specific image:
``` …
```
=> 🐛 Fix ko build workflows in Makefile

cron/k8s/worker.release.yaml
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process
* Enables Dangerous-Workflow in release test
Part of https://github.com/ossf/scorecard/issues/1399
no
=> :sparkles: Enable dangerous workflow in release test

checks/permissions.go, checks/permissions_test.go, checks/testdata/github-workflow-permissions-run-level-only.yaml, checks/testdata/github-workflow-permissions-top-level-only.yaml
Token permission check does not handle multiple files for score calculation, due to the fact that all workflows shared the same permission map. This is because the check used to only look for undefined top-level permissions, globally. Now we've switched to looking for both run-level and top-level permissions. We want to only flag when some files don't declare both of them; or if only the run-level permissions are declared.
closes https://github.com/ossf/scorecard/issues/1400
=> 🐛  Fix score calculation for multiple files

cmd/root.go
In order to simplify maintenance and support, we won't publicly advertise support for sarif and the score-based policy file. 
1. sarif will be used internally for the action. Currently, we run the scorecard CLI; but long-term we may have a dedicated CLI for the action. 
2. The policy file will be replaced by a setting-based policy file once we have finished separating checks from policy score-based policy calculation.
=> ✨ Do not expose sarif and policy command

checks/evaluation/binary_artifacts.go, checks/raw/security_policy.go, pkg/sarif.go, pkg/sarif_test.go, pkg/testdata/check6.sarif
we add details for additional information to SARIF when there is no file path to point to: branch protection, code reviews, etc.
Example, users will see
```
branch protection is not maximal on development and all release branches:
Warn: settings do not apply to administrators on branch 'main'
Warn: no status checks found to merge onto branch 'main'
Warn: number of required reviewers is 0 on branch 'main'
Warn: Stale review dismissal disabled on branch 'main'
```
instead of only:
```
branch protection is not maximal on development and all release branches
```
=> ✨ Add details to message for default location in SARIF

checks/packaging.go, e2e/packaging_test.go
Simple fix in the Packaging check.
=> 🐛 Use Debug. instead of Info

checker/check_result.go
There's a hidden assumption that LogMessage enums start at 0: this way if none is provided when calling `Warn()`, it defaults to None = 0. This is, for example, needed for FileTypeNone.
This assumption was recently violated thru refactoring. My bad because there was no comment about it :/
=> 🐛 Make enum start at 0

docs/checks.md, docs/checks/internal/checks.yaml
Update the doc to reflect the changes in the check, in particular around lock files.
Note that once we have proper documentation for package managers, we'll point to it.
=> 🐛  Documentation out of sync with Pinned-Dependencies check

docs/checks/internal/checks.yaml
Some links don't render properly in the GitHub scanning dashboard, in particular those that span multiple lines.
This PR fixes it/
=> 🐛 Fix a few links in the doc

docs/checks.md, docs/checks/internal/checks.yaml
[StepSecurity's online tool](https://app.stepsecurity.io/) helps users determine:
1. the permission to use for they workflows
2. the hash for an action, if it currently uses a version
Both are extremely useful to drive changes along with the scorecard action.
The tool is open-source and free.
=> ✨ Add StepSecurity to docs

checks/shell_download_validate.go
Update messages for pinning warning `"insecure (not pinned by hash) download"` -> `"insecure (not pinned by hash) download-then-run"`. This is better in cases where the highlighted line only executes a file, and the download is many lines before and not shown to user.
no braking changes
=> ✨ Update messages for pinning warning

checks/sast.go
Details contains `no pull requests merged into dev branch` when no check runs are found for a PR. I think this is a mistake.
=> 🐛 Remove inconclusive result from SAST

pkg/sarif.go, pkg/testdata/check2.sarif, pkg/testdata/check3.sarif, pkg/testdata/check4.sarif, pkg/testdata/check7.sarif
GitHub does not support `ByteOffset`, and this prevents GitHub from displaying the message to display.
This PR adds `startLine` in this case.
=> ✨ Add startLine to sarif for binary files

pkg/sarif.go, pkg/testdata/check1.sarif, pkg/testdata/check2.sarif, pkg/testdata/check3.sarif, pkg/testdata/check4.sarif, pkg/testdata/check5.sarif, pkg/testdata/check6.sarif, pkg/testdata/check7.sarif, pkg/testdata/check8.sarif
We currently display "on file available" when no file in the repo can be pointed to in the SARIF report. We use this, for example, for branch-Protection, Code-Review, Security-Policy. It's been reported to be confusing for users.
This PR changes the filename to be empty as " ". "" is not a valid name, which is why I provide a single space.
List of alerts:
When clicking on the alert, no name is shown as:
=> ✨ Change filename when no file is available

checks/sast_test.go
Addresses https://github.com/ossf/scorecard/issues/435
=> :sparkles: Unit test for SAST

checks/binary_artifact_test.go, checks/license_test.go, checks/raw/security_policy.go, clients/githubrepo/client.go, clients/localdir/client.go, clients/localdir/client_test.go, cmd/root.go, cmd/serve.go, cron/format/json.go, cron/format/json_test.go, cron/worker/main.go, e2e/e2e_suite_test.go, log/log.go, pkg/common.go, pkg/json.go, pkg/json_test.go, pkg/sarif.go, pkg/sarif_test.go, pkg/scorecard_result.go
We're roughly mimicking existing functionality and the interface may change in future. Logging usage that has changed exists in packages that already have test coverage.
tl;dr -- If existing tests pass, we should be fine here.
Introduces a logging package to eventually replace go.uber.org/zap.
Here we're effectively quarantining usage of the go.uber.org/zap and go.uber.org/zap/zapcore to a single package, `log`.
See https://github.com/ossf/scorecard/issues/1273.
Functions that create instances of `zap.Logger` …
=> :warning: Create a dedicated logging package to encapsulate calls to `zap`

checks/binary_artifact_test.go, checks/license_test.go, checks/raw/security_policy.go, clients/githubrepo/client.go, clients/githubrepo/roundtripper/rate_limit.go, clients/githubrepo/roundtripper/roundtripper.go, clients/localdir/client_test.go, cmd/root.go, cmd/serve.go, cron/worker/main.go, e2e/e2e_suite_test.go, go.mod, go.sum, log/log.go
Continues https://github.com/ossf/scorecard/pull/1502.
ref: https://github.com/ossf/scorecard/issues/1273
https://github.com/ossf/scorecard/pull/1502 implemented a generic logger that wrapped `zap`. Create a new logger is done by calling `log.Logger(log.Level)`.
`log.Logger` now uses `logr`, which provides a sane interface and has multiple popular implementations.
From @thockin in https://github.com/ossf/scorecard/issues/1273#issuecomment-1018822830:
> Stephen …
=> ⚠️ log: Initial `logr`/`logrusr` implementation

.github/CODEOWNERS
Part of https://github.com/ossf/scorecard/issues/1529.
- CODEOWNERS: Simplify maintainers
.github/workflows/* CODEOWNERS are effectively maintainers, but
with the current configuration, they are not being automatically
tagged for review for other file changes.
Here we simplify to `*`, in preparation for adding additional
maintainers.
(Maintainers have also been alpha-sorted.)
- CODEOWNERS: Add Stephen Augustus (justaugustus) as maintainer
cc: @inferno-chromium @naveensrinivasan @azeemshaikh38 @laurentsimon
N/A
* **What is …
=> :seedling: CODEOWNERS: Add Stephen Augustus (justaugustus) as maintainer

checker/raw_result.go, checks/evaluation/vulnerabilities.go, checks/raw/vulnerabilities.go, checks/vulnerabilities.go, checks/vulnerabilities_test.go, e2e/vulnerabilities_test.go, pkg/json_raw_results.go
checker/raw_results.go: add structure for results
checks/vulnerabilities.go: rewrite fr policy seperation
checks/raw/vulnerabilities.go: data retrieval 
checks/evaluation/vulnerabilities.go: score calculation
pkg/json_raw_results.go: displays the results.
Refactor the Vulnerabilities check by separating the data retrieval and policy (score) evaluation.
This will allow users to create their own policies based on the raw (more structured) results, see ttps://github.com/ossf/scorecard/issues/1245
=> ✨ Separate check from policies for the Vulnerabilities check

docs/checks.md, docs/checks/internal/checks.yaml
docs/checks.md: updated the doc
docs/checks/internal/checks.yaml: updated the source of truth for docs
Link to the responsible disclosure guidelines.
=> 📖 `Security-Policy`: Link to responsible disclosure guidelines for remediation

checks/ci_tests.go
The current check is looking at the github checks data to identify whether a given PR ran tests. Flutter and Dart repos are failing the check because their systems are not recognized as CI Systems.
Bug: https://github.com/ossf/scorecard/issues/1547
Updates the CI Test check adding new CI Systems.
Only common CI systems are included in the CI Test check and the ones used by Dart and Flutter are not included.
https://github.com/ossf/scorecard/issues/1547
flutter-dashboard and Cirrus CI will now be recognized as …
=> 🌱 Add Dart and Flutter CI systems to CI tests check.

utests/utlib.go
Fixes existing nil-ptr issues.
No.
=> 🐛 Fix nil-ptr issue in e2e tests

README.md
📖 README: s/Justin/Stephen
...also fixes link to GitHub profile.
=> 📖 README: s/Justin/Stephen

clients/githubrepo/graphql.go
Only returns PRs used to merge recent commits if any. None otherwise.
Fixes #1524. Part of #575.
No.
=> 🌱 Only return PRs associated with recent commits

checks/binary_artifact_test.go, checks/license_test.go, clients/localdir/client_test.go, clients/localdir/repo.go, cmd/flags.go, cmd/package_managers.go, cmd/root.go, cmd/serve.go
Refactors code. Minor behavior change - instead of `--raw` option, use `--format=raw`.
No.
=> 🌱 Refactor some code

docs/checks.md, docs/checks/internal/checks.yaml
Explicitly say that renovatebot can help migrate from version pinning to hash pinning via a setting.
See https://github.com/dependabot/dependabot-core/issues/3699#issuecomment-1025715911
=> ✨ Mention renovatebot's settings

checks/pinned_dependencies.go, checks/pinned_dependencies_test.go, checks/sast.go
Avoid parsing dockerfiles based on their extension.
closes https://github.com/ossf/scorecard/issues/1573
=> Do not parse non-dockerfile

CONTRIBUTING.md
GitHub renders `:xyz:` aliases in PR titles just fine nowadays.
CONTRIBUTING.md docs update
CONTRIBUTING.md incorrectly claims GitHub doesn't render `:xyz:` aliases in PR titles.
It no longer makes such a claim.
No
=> :book: remove inaccurate claim about github rendering emoji

checks/raw/security_policy.go, checks/security_policy_test.go
checks/security_policy_test.go: updated unit tests
checks/raw/security_policy.go: add support for .adoc policies
Add support for .adoc files.
closes https://github.com/ossf/scorecard/issues/1347
=> ✨ Add support for .adoc files for security policies

pkg/sarif.go, pkg/testdata/check6.sarif
pkg/testdata/check6.sarif: Update message
pkg/sarif.go: Add score to message
Add score information to message displayed in SARIF alerts if the alert packs multiple settings, such as branch protection.
No breaking changes. 
closes https://github.com/ossf/scorecard/issues/1592
=> ✨ Add score to SARIF alerts

checker/raw_result.go, checks/ci_tests.go, checks/code_review_test.go, checks/evaluation/code_review.go, checks/maintained.go, checks/raw/code_review.go, checks/sast.go, checks/sast_test.go, clients/commit.go, clients/githubrepo/client.go, clients/githubrepo/graphql.go, clients/localdir/client.go, clients/mockclients/repo_client.go, clients/pull_request.go, clients/repo_client.go, docs/checks/internal/validate/main.go
Instead of relying on 2 potentially divergent APIs - `ListCommits` and `ListMergedPRs`, reduce the API to only `ListCommits`. Any PRs associated with this commit will be return in the `associatedPR` field. It makes Scorecard more tightly tied to analyzing a repo's commits (part of #575) and helps avoid confusion in future implementations of `RepoClient` (long-term fix of #1524).
Yes.
=> ⚠️ Remove ListMergedPRs API

checks/raw/dependency_update_tool.go, checks/raw/dependency_update_tool_test.go
The Dependabot check does not consider `.github/dependabot.yaml` file, however both `.yml` and `.yaml` extensions should be accepted according to the [documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions).
This PR fixes this bug by adding `.github/dependabot.yaml` to the files checked in the dependency update tool check, and provides a test to check for `.github/dependabot.yaml` file.
Closes #1600
=> :bug: Fix Dependabot check to accept .yaml file extension

.github/workflows/integration.yml
Fixed the `YAML` formatting issue 🤦  which was causing the cache not to work. 
This fix will address the formatting issue which will help with the caching of the workflow runs.
=> 🌱 Fixed the formatting issue

clients/githubrepo/client.go, clients/githubrepo/graphql.go, clients/githubrepo/tarball.go
Add support for non-HEAD commit lookup in GitHub RepoClient. This PR attempts to add the support while not changing the behavior. Once the e2e tests confirm that this does not break anything will follow-up with exposing this feature externally. 
No.
=> 🌱 Add support for commit-based lookup to GitHub APIs

checker/check_request.go, checker/check_runner.go, checks/all_checks.go, checks/all_checks_test.go, checks/binary_artifact.go, checks/branch_protection.go, checks/ci_tests.go, checks/cii_best_practices.go, checks/code_review.go, checks/contributors.go, checks/dangerous_workflow.go, checks/dependency_update_tool.go, checks/fuzzing.go, checks/license.go, checks/maintained.go, checks/packaging.go, checks/permissions.go, checks/pinned_dependencies.go, checks/sast.go, checks/security_policy.go, checks/signed_releases.go, checks/vulnerabilities.go, cmd/root.go, docs/checks/internal/validate/main.go, errors/public.go
Replace file parsing logic for recognizing supported/unsupported checks. 
No.
=> 🌱 Only run allowed checks in different modes

.github/workflows/scorecard-analysis.yml
We're using an old `policy_file` arguments that's no longer used
=> 🐛 Update scorecard action workflow

checks/evaluation/code_review.go, checks/evaluation/code_review_test.go, clients/githubrepo/graphql.go, e2e/code_review_test.go
Part of #575. Repos which do not squash their PR commits end up with multiple commits associated with a single PR. This PR fixes that.
No.
=> 🐛 Fix for repos which do not squash PR commits

checks/dangerous_workflow.go, checks/dangerous_workflow_test.go, checks/testdata/.github/workflows/github-workflow-dangerous-pattern-secret-env-checkout-noref-prt.yml, checks/testdata/.github/workflows/github-workflow-dangerous-pattern-secret-env-environment-prt.yml, checks/testdata/.github/workflows/github-workflow-dangerous-pattern-secret-env-no-checkout-prt.yml, checks/testdata/.github/workflows/github-workflow-dangerous-pattern-secret-env-prt.yml, checks/testdata/.github/workflows/github-workflow-dangerous-pattern-secret-run-prt.yml, e2e/dangerous_workflow_test.go
Check for secrets in pull_request_target in dangerous workflow check.
Today this is handled by the fact that the check looks for pull_request_target. But once https://github.com/ossf/scorecard/issues/1311 is resolved, only cases where permissions are sensitive will be reported.
This PR adds support for checking for secrets regardless of permissions used. Until https://github.com/ossf/scorecard/issues/1311 is resolved, users will see 2 alerts instead of one: one for the secret, and one for the "generic" pull_request_target usage.
closes https://github.com/ossf/scorecard/issues/1633
=> ✨ Check for secrets in pull_request_target

.github/workflows/docker.yml, Makefile
The builds are slow on CI.
- Created a workflow with multiple jobs for each of the docker builds
- Created a workflow with multiple jobs for each of the ko builds
- Removed the reference to dockerbuild and kobuild in the build-targets
make target
- This should reduce the time required to finish the CI builds as it
makes it parallel.
=> :seedling: Parallelize the builds

checker/check_result.go, checks/ci_tests.go, checks/contributors.go, checks/dangerous_workflow.go, checks/evaluation/binary_artifacts.go, checks/evaluation/code_review.go, checks/evaluation/dependency_update_tool.go, checks/evaluation/security_policy.go, checks/evaluation/vulnerabilities.go, checks/license.go, checks/packaging.go, checks/permissions.go, checks/pinned_dependencies.go, checks/sast.go, checks/shell_download_validate.go, checks/signed_releases.go, cron/format/json_test.go, pkg/common.go, pkg/json_test.go, pkg/sarif_test.go, pkg/testdata/check6.sarif, utests/utlib.go
=> 🌱 Remove `Version` field from LogMessage

Makefile, clients/githubrepo/branches.go, clients/githubrepo/branches_e2e_test.go, clients/githubrepo/githubrepo_suite_test.go, clients/githubrepo/graphql.go, clients/githubrepo/graphql_e2e_test.go
=> ✨ Add tests for graphQL costs

clients/githubrepo/client.go
Way back in 2.0 the constructor took a github.Client directly, which is what Allstar instantiated to then run scorecard checks. With the current code, there is no way to override the built-in roundtripper.NewTransport which uses its own methods to authenticate.
To allow Allstar to use the current code, we need to create this client and provide a pre-authenticated transport (or http client, or github client).
cc @justaugustus
=> :sparkles: githubrepo: Allow providing an already authenticated transport

Makefile
- Remove building ko as we aren't using `ko` yet.
- Every build of `ko` slows down the build time.
- When we enable `ko` which will replace `docker` then we can enable `ko` builds
=> :seedling: Remove building ko to speed up builds

checks/errors.go, checks/fileparser/listing.go, checks/fileparser/listing_test.go, checks/license.go, checks/raw/dependency_update_tool.go, checks/raw/errors.go, checks/raw/security_policy.go, checks/raw/security_policy_test.go
Removes all existing versions of `CheckIfFileExists` and replaces them with a more generalized version. Part of #1393 
No.
=> 🌱 Generalize CheckIfFileExists fn

checks/dangerous_workflow.go, checks/fileparser/listing.go, checks/fileparser/listing_test.go, checks/fuzzing.go, checks/permissions.go, checks/pinned_dependencies.go, checks/raw/binary_artifact.go
Removes existing versions of CheckFileContent functions and replaces with a generic fn instead.
No.
=> 🌱 Generalize CheckFileContent functions

.github/workflows/scorecard-analysis.yml
Use the right inputs for Scorecard action.
No.
=> 🐛 Update scorecard-analysis.yml

.github/PULL_REQUEST_TEMPLATE.md
See https://github.com/ossf/scorecard/blob/504f13441636dcc6273d45d9dc1e7ea1ef080ae2/.github/PULL_REQUEST_TEMPLATE.md.
Adding a `release-note` code fence will allow us to start leverage the Kubernetes `release-notes` tool: https://git.k8s.io/release/cmd/release-notes/README.md
See comparison
https://github.com/ossf/scorecard/releases/tag/v4.1.0:
https://github.com/kubernetes/release/releases/tag/v0.13.0:
Partially addresses https://github.com/ossf/scorecard/issues/1677.
I've used the proposed PR template for this PR and added a fake release note that we can later test against.
(In particular, describe what changes users might need to make …
=> 📖 Refine copy for PR template and add a `release-note` code fence

cmd/root.go, cmd/serve.go, main.go, options/flags.go, options/options.go
One part feature, one part bug fix?
- cmd: Allow new scorecard commands to be instantiated with options
- options: Default flags to struct field values
- options: Use constants for flag names
- options: Simplify SARIF check
With https://github.com/ossf/scorecard/pull/1696, we enabled the ability to import the scorecard cobra command to support use cases like https://github.com/ossf/scorecard-action/pull/122.
Unfortunately, because of the way we're currently handling defaulting for the flags, it means any initialization of the scorecard options gets discarded in favor of the flag defaults.
Where this comes up is when we attempt to build an options set via environment variables.
First …
=> ✨ cmd: Allow new scorecard to be instantiated with options

clients/githubrepo/graphql.go
PR verifies the commit's signature when the committer's name is "GitHub" and the committer's login for a merged PR is `""`.
See https://github.com/ossf/scorecard/issues/1543 for more details
In addition, it fixes reviewer names that were not populated( I caught this problem when using `--format raw`)
closes https://github.com/ossf/scorecard/issues/1543
```release-notes
Verify merged commits by GitHub are genuine
```
=> 🐛 Add GitHub committer verification

checks/license.go, checks/security_policy.go, e2e/license_test.go, e2e/security_policy_test.go
Part of #575. Include `License` and `SecPol` checks also in commit-based checks.
Yes.
NONE
```release-note
NONE
```
=> 🌱 Mark `License`, `Security-Policy` as commit-based

.github/workflows/codeql-analysis.yml
Included hard-runner to restrict egress traffic.
NONE
```release-note
NONE
```
=> :seedling: .github: Audit CodeQL egress with harden-runner

clients/githubrepo/checkruns.go, clients/githubrepo/statuses.go
Enable `CI-Test` as a commit-based check. This is the final check needed to support a commit-specific Scorecard result.
No support for commit-specific Scorecard result.
Adds support for `--commit=` option in Scorecard CLI.
Yes, `e2e/ci_tests_test.go` has tests for this.
Fixes #575 
```release-note
Add support for commit-based Scorecard checks.
```
=> ✨ Enable `CI-Tests` to run as commit-based check

.github/workflows/docker.yml, .github/workflows/goreleaser.yaml, .github/workflows/integration.yml, .github/workflows/main.yml, .github/workflows/ok-to-test.yml, .github/workflows/scorecard-analysis.yml, .github/workflows/stale.yml, .github/workflows/verify.yml
Restrict egress for github actions
NONE
```release-note
Restrict egress for GitHub actions
```
=> :seedling: Restrict egress on github actions

e2e/license_test.go
- e2e for local repoclient for license check.
```release-note
NONE
```
=> :seedling: e2e for local repoclient license check

.github/workflows/main.yml
An attempt at fixing failing protoc issues. Part of #1774 
NONE
```release-note
NONE
```
=> 🌱 Use `GITHUB_TOKEN` for downloading protoc

.github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/main.yml, .github/workflows/scorecard-analysis.yml, .github/workflows/stale.yml
small cleanup on the workflow jobs and remove the master branch reference
/assign @laurentsimon @naveensrinivasan 
NONE
```release-note
NONE
```
=> 🌱 small cleanup on the workflow jobs and remove the master branch reference

checker/raw_result.go, checks/evaluation/webhooks.go, checks/evaluation/webhooks_test.go, checks/raw/webhook.go, checks/raw/webhooks_test.go, checks/webhook.go, checks/webhook_test.go, clients/githubrepo/client.go, clients/githubrepo/webhook.go, clients/localdir/client.go, clients/mockclients/repo_client.go, clients/repo_client.go, clients/webhook.go, docs/checks.md, docs/checks/internal/checks.yaml
This adds a new check to validate the GitHub repositories Webhooks if the webhook has a secret configured.
Tested with a token with `public_repo` permission only and worked.
Fixes #1655 
NONE
Add a new check to validate GitHub Webhook
No
=> ✨ checks: add GitHub Webhook check

.github/workflows/docker.yml, .github/workflows/main.yml
Hopefully this fixes the make linter failures
https://github.com/ossf/scorecard/runs/5834278035?check_suite_focus=true
I noticed while trying to debug , which was using go 1.18 in the
workflow log.
Which made me decide to pin it to specific version of go 1.17.7
```
go env -w GOFLAGS=-mod=mod
make check-linter
shell: /usr/bin/bash -e {0}
env:
PROTOC_VERSION: 3.17.3
GOROOT: /opt/hostedtoolcache/go/1.18.0/x64
```
=> :seedling: Pins the golang version in the workflow

e2e/dangerous_workflow_test.go
- e2e for dangerous_workflow for localrepoclient.
https://github.com/ossf/scorecard/issues/861
```release-note
```
=> :seedling: e2e for dangerous_workflow local repo

e2e/pinned_dependencies_test.go
- e2e for pinned_dependencies for localrepoclient
```release-note
```
=> :seedling: e2e for pinned_dependencies for localrepoclient

checks/raw/security_policy.go, checks/raw/security_policy_test.go
Add localclient support for `Security-Policy` check.
Fixes #1752
```release-note
Support `Security-Policy` with `--local`
```
=> ✨ Support `Security-Policy` with `--local`

checks/raw/security_policy.go, checks/raw/security_policy_test.go, checks/security_policy.go
Fixes bug introduced in #1579. `Security-Policy` was never supposed to be run on `--local`.
NONE
```release-note
Remove `Security-Policy` from `--local`
```
=> 🐛 `Security-Policy` should not run on `--local`

.github/workflows/integration.yml, Makefile, e2e/branch_protection_test.go, e2e/e2e_suite_test.go
We want to support the default `GITHUB_TOKEN` token for the scorecard action.
This PR adds e2e tests that use the default GITHUB_TOKEN.
Branch protection is not supported for GITHUB_TOKEN, so this PR ignore this check in the e2e tests if the token is a GITHUB_TOKEN.
```release-notes
Add e2e tests using GITHUB_TOKEN
```
=> ✨ Add e2e tests using GITHUB_TOKEN

clients/githubrepo/branches_e2e_test.go, clients/githubrepo/githubrepo_suite_test.go
See https://github.com/ossf/scorecard/issues/1834
```release-notes
Fix e2e branch
```
=> 🐛 Fix e2e branch

log/log.go
This is a minor tweak to the implementation of `log.NewLogger` to make reuse of scorecard components in ossf/criticality_score easier.
`log.NewLogger()` takes a log level, creates the logrus instance, creates a logr instance and returns a new instance of `log.Logger`.
`log.NewLogrusLogger()` splits the behavior of `log.NewLogger()`, so an external logrus instance can be used to create the logger required for scorecard packages.
NONE
N/A
```release-note
NONE
```
=> :seedling: Split NewLogger into two so we can use a custom logrus instance.

clients/githubrepo/branches_e2e_test.go, e2e/branch_protection_test.go
I broke the unit tests, see https://github.com/ossf/scorecard/issues/1834
It turns out that the ginkgo's `Skip()` function only works in the `It()` function.
Fix e2e tests for branch protection
```release-notes
Fix e2e tests for branch protection
```
=> 🐛 Fix e2e tests for branch protection

clients/githubrepo/branches_e2e_test.go
Fix the githubrepo e2e2 branch test. I used the wrong token type.
```release-notes
Fix the githubrepo e2e2 branch test
```
=> 🐛 last fix for e2e branch tests

cron/k8s/transfer-raw.yaml, cron/k8s/transfer.release-raw.yaml
Env variables used in k8 configs use the wrong name. This PR fixes it.
No braking changes
```release-notes
Fix Env variables used in k8 configs
```
closes https://github.com/ossf/scorecard/issues/1857
=> 🐛 Update env variables in cron

checker/check_result.go, checker/check_runner.go, checks/code_review_test.go, checks/contributors_test.go, checks/evaluation/binary_artifacts_test.go, checks/evaluation/dependency_update_tool_test.go, checks/evaluation/webhooks_test.go, checks/fuzzing_test.go, checks/maintained_test.go, checks/pinned_dependencies_test.go, checks/signed_releases_test.go, checks/webhook_test.go, cron/worker/main.go, e2e/binary_artifacts_test.go, e2e/branch_protection_test.go, e2e/cii_best_practices_test.go, e2e/contributors_test.go, e2e/dangerous_workflow_test.go, e2e/dependency_update_tool_test.go, e2e/license_test.go, e2e/maintained_test.go, e2e/permissions_test.go, e2e/sast_test.go, e2e/security_policy_test.go, e2e/signedreleases_test.go, e2e/vulnerabilities_test.go
- Removing the error field from the `CheckResult`
- https://github.com/ossf/scorecard/issues/1393
```release-note
Removing the error field from CheckResult 
```
=> :warning: Removing the error field from `CheckResult` struct

cmd/root.go
Propagate error in log
```release-notes
Propagate error in log
```
=> 🐛 Propagate error in log

checks/cii_best_practices.go, checks/pinned_dependencies.go, checks/pinned_dependencies_test.go, checks/shell_download_validate.go, checks/shell_download_validate_test.go
Ignore shell parsing errors when reporting results
```release-notes
Ignore shell parsing errors when reporting results
```
closes https://github.com/ossf/scorecard/issues/1876
=> 🐛 Ignore shell parsing errors when reporting results

checks/raw/binary_artifact.go, checks/raw/binary_artifact_test.go, checks/testdata/binaryartifacts/printable.lib, e2e/binary_artifacts_test.go
Fix .lib false positives in binary artifacts
```release-notes
Fix .lib false positives in binary artifacts
```
closes https://github.com/ossf/scorecard/issues/1868
=> 🐛 Fix .lib false positives in binary artifacts

checks/code_review_test.go, checks/evaluation/code_review.go
Supports the "Reviewed By" field used by Phabricator to check if a repo uses Phabricator as their code review system.
Repos that use Phabricator are marked as not requiring code review.
Fixes #1883
```release-note
Repositories using Phabricator will now pass the Code review check.
```
=> ✨ Add support for Phabricator as a code review system

checks/code_review_test.go, checks/evaluation/code_review.go
Support commits reviewed through Piper (Google code review tool). There are 8M+ commits on GitHub which pass this requirement - https://github.com/search?q=PiperOrigin-RevId&type=commits
```release-note
Support PRs reviewed using Piper
```
=> ✨ Support commits reviewed through Piper

checker/check_result.go, checks/permissions.go, checks/pinned_dependencies.go, checks/raw/binary_artifact.go, checks/remediations.go, pkg/sarif.go, pkg/sarif_test.go, pkg/testdata/check-remediation.sarif
Add custom remediation for workflow permissions/pinned dependencies
```release-notes
Add custom remediation for workflow permissions/pinned dependencies
```
see https://github.com/ossf/scorecard/issues/1850
Screenshot:
=> ✨ Add custom remediation for workflow permissions/pinned dependencies

cloudbuild/scorecard-tag.yaml
There is a bug in how we generate Docker images for new tags (like v4.2.0). Currently we tag HEAD as the latest tag irrespective of which commit the tag it applied to. This PR fixes that.
```release-note
Bug fix in Docker image creation
```
=> 🐛 Fix bug in Scorecard tag Docker image creation

README.md
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>
docs update
- [ x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)
README claims that CSV output format is supported.
README only lists default and json as output formats.
NA.
NONE
I actually happen to regret the drop of CSV output support but at least the documentation should be consistent with the code.
Yes, the README no longer misleads the user.
```release-note
Update README to reflect actual list of supported output formats.
```
=> :book: Remove erroneous ref to CSV output

cmd/root.go, options/flags.go
This changes the cmd Usage text to accurately represents the
supported syntax:
Usage:
./scorecard (--repo=\<repo> | --local=\<folder> | --{npm,pypi,rubygems}=<package_name> ) [--checks=check1,...]
[--show-details] [flags]
...
--repo string        repository to check (valid inputs: "owner/repo", "github.com/owner/repo", "https://github.com/owner/repo")
...
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>
Improvement
- [x ] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)
NA
NONE
I'm not sure whether to categorize this change as a "Documentation" change given that it is in the code, or a "Bug Fix" given that it is merely changing the Usage text of the command... :-)
For user-facing changes, …
=> :book: Fix command Usage

checker/check_result.go, cron/format/json.go, pkg/json.go
- Removing the confidence field from `CheckResult` struct
- https://github.com/ossf/scorecard/issues/1393
```release-note
Removing confidence from the CheckResult result.
```
=> :warning: Removing the confidence field from `CheckResult` struct

options/options.go, options/options_test.go
See https://github.com/ossf/scorecard-action/issues/261
Remove Options that belong to the Action
```release-notes
Remove Options that belong to the Action
```
=> 🐛 Remove Options that belong to the Action

checks/permissions.go, checks/permissions_test.go, checks/testdata/.github/workflows/github-workflow-permissions-gh-pages.yaml, e2e/permissions_test.go
Make permission check aware of GH Pages Action
```release-notes
Make permission check aware of GH Pages Action
```
closes https://github.com/ossf/scorecard/issues/1867
=> ✨ Make permission check aware of GH Pages Action

checker/check_result.go
- Remove Pass field from CheckResult
```release-note
Removing the pass from CheckResult.
```
=> :warning: Remove the pass from the `CheckResult`

checker/check_result.go, checker/check_runner.go, cron/format/json.go, cron/format/json_test.go, pkg/json.go, pkg/json_test.go, pkg/sarif.go, pkg/sarif_test.go, pkg/scorecard_result.go
https://github.com/ossf/scorecard/issues/1393
=> ⚠️  Remove the old Details field from CheckResult

checker/raw_result.go, checks/evaluation/dangerous_workflow.go, checks/raw/dangerous_workflow.go, checks/raw/dangerous_workflow_test.go, pkg/json.go, pkg/json_raw_results.go, pkg/scorecard_result.go
Using a `type` for the dangerous workflow results. This will avoid updating the structure/BQ table every time we add a new type of check.
Note: need https://github.com/ossf/scorecard/pull/1864 to be merged
```release-notes
Update raw format for Dangerous workflows
```
=> ✨ Update raw format for Dangerous workflows

checks/raw/vulnerabilities.go, checks/raw/vulnerabilities_test.go, cron/format/json.go
Bug fix: `Vuln` check was failing for empty repositories. 
Part of #1901 
```release-note
NONE
```
=> 🐛 Do not fail on empty repositories

checks/remediations.go
Fix remediation code. The if statement was incorrect: we were not returning in case there was an error. `b` was nil in this case and caused a nil pointer.
```release-notes
Fix remediation code
```
closes https://github.com/ossf/scorecard/issues/1942
=> 🐛 Fix remediation code

.github/workflows/publishimage.yml
Scorecard complains because the top level permissions are not set to read.
Ill tackle this false positive as part of https://github.com/ossf/scorecard/issues/1874
=> ✨ Silence scorecard warning

checks/fuzzing_test.go, checks/raw/fuzzing.go, checks/raw/fuzzing_test.go, clients/githubrepo/client.go, clients/githubrepo/languages.go, clients/languages.go, clients/localdir/client.go, clients/mockclients/repo_client.go, clients/repo_client.go
- A follow-up PR on PR[#1979](https://github.com/ossf/scorecard/pull/1979).
- Modify `type Language string` to `type LanguageName string` in `clients/languages.go`.
- Add a new struct `type Language struct {LanguageName, LoC}` in `clients/languages.go`.
- Add support for interface `ListProgrammingLanguages` to parse the returned JSON to a list of `Language`.
- Add more language name const: `CMake` and `DockerFile`
No.
```release-note
NONE
```
=> ✨ Add Language struct and optimize result parsing for GHClient.ListProgrammingLanguages

cloudbuild/scorecard-tag.yaml
Currently CloudBuild simply tags the Docker image with the version (e.g v4.3.1). But we also need to re-build this Docker image before tagging it so that `scorecard version` command returns the right value.
NONE
```release-note
Fix bug in docker run scorecard version
```
=> 🐛 Fix bug in `docker run scorecard version`

clients/githubrepo/languages.go, pkg/sarif.go, policy/policy_test.go
gofmt -s -w . 
and 
some misspelled words fixed
NONE
No
```release-note
NONE
```
=> 🌱  small fixes

.golangci.yml
Configuration change for `golangci-lint`. With the current linter settings, `default` is useless and satisfying the linter involves adding empty cases that clutter the code more than `default`. I realize this is subjective, but the current setting is overly cautious.
Switch statements on enums currently require cases for all enum members.
`default` will satisfy the linter now. 
NONE
```release-note
NONE
```
=> 🌱 Adjust 'exhaustive' linter to consider 'default' as exhaustive

dependencydiff/dependencydiff.go, dependencydiff/dependencydiff_test.go
Fixing a bug introduced in PR #2046 where the `ghRepo` type of (clients.Repo) was created wrongly by the input `repoURI` rather than the dependency repoURI to be checked by scorecard.
The Dependencydiff module uses the input repo to initialize the `ghRepo` to run the scorecard check, resulting in all of the dependencies having the same check results and scores (of the input repo).
The module will correctly initialize `ghRepo` using the dependency's srcRepo URI.
Fixes #2046 
No.
```release-note
NONE
```
=> 🐛 Bug fixing: Using the wrong URI to initialize the repo in Dependencydiff

checks/evaluation/pinned_dependencies.go, pkg/common.go, pkg/common_test.go, remediation/remediations.go
This PR attempts to address an enhancement in #967 
A warning is generated when a Docker dependency is not pinned.
> Warn: containerImage not pinned by hash: Dockerfile:1
A hash is now provided, as determined by `crane`
> Warn: containerImage not pinned by hash. Fix by updating golang:1.17 to golang:1.17@sha256:e4d220556e80a686fad8874b40ccfa2f3172dfe5c6ca7f36f8ee79d594a9c959: Dockerfile:1
Fixes #967 
NONE
```release-note
Hash suggestions are now made for unpinned images in Dockerfiles
```
=> ✨ Use crane to add hash suggestion to unpinned Docker images

checks/write.md
Fixes a few typos and improves legibility in write.md.
=> 📖 Minor typos and copy-editing to checks/write.md

checks/raw/fuzzing_test.go, checks/sast.go, checks/sast_test.go, checks/testdata/pom-1line.xml, checks/testdata/pom-2lines.xml
See https://github.com/ossf/scorecard/issues/2085
/cc @edwardsph
=> feat: Add pom.xml support for sonarype SAST

dependencydiff/dependencydiff.go, dependencydiff/dependencydiff_test.go, e2e/dependencydiff_test.go
Changing the type of the input parameter of the Dependency-diff API from `map` to `[]string` to make it more intuitive for users to use.
This API hasn't been used by other apps or services (the CLI / the Action visualization haven't arrived in the rpeo yet), so this change should be safe.
The `GetDependencyDiffResults` API takes  `changeTypesToCheck map[pkg.ChangeType]bool` as one of its inputs to specify those change types for which we'll surface scorecard results. However, this is not that intuitive since users have to construct a hashmap to use this API. A better way is to simply take an array of strings, and create the hashmap in the function when it's needed.
`changeTypesToCheck` will be a type of `[]string`.
Additional unit tests added.
The original e2e tests can cover this minor …
=> ✨ Enhancement: Dependency-diff API optimization - changing the input param changeType from a map to an array

README.md
Adds an example query to the README to provide historical data for a project's score over time. This question was asked in the OSSF slack, and is something more people may want to know in the future.
NONE
This query currently processes ~1.6GB of data. My understanding of [BigQuery's pricing model](https://cloud.google.com/bigquery/pricing#analysis_pricing_models) is that this won't affect OSSF's hosting costs as the query cost falls on the user running the query. I just wanted to mention this in case my understanding is wrong and there's an increase in queries from including an example in the docs.
application as a result …
=> 📖 Include an example query for the public BigQuery dataset

checks/all_checks.go, checks/webhook.go, checks/webhook_test.go, cmd/serve.go, docs/checks/internal/validate/main.go, options/flags.go, policy/policy.go
Limit access to registered checks except through `checks.GetAll()` and `checks.GetAllForEnvironment()`. 
The intention is to provide two versions, one which returns everything, and one which excludes experimental features (unless enabled via environment flags). This was causing problems in #2133, as WebHooks was being run by default.
`checks.AllChecks` and `checks.GetAll()` were both public and being used.
`checks.GetAll()` did not filter on environment variable constraints, despite its comment saying it did
`checks.allChecks` made private
`checks.GetAll()` had its comment updated to reflect the behavior
`checks.GetAllForEnvironment()` introduced to filter the checks to those supported by the environment variables.
NONE
For user-facing changes, please add a concise, human-readable release …
=> 🌱 Limit access to registered checks

checks/evaluation/signed_releases.go, checks/raw/contributors.go, checks/signed_releases_test.go
Search for `.intoto.jsonl` in the release check.
```release-notes
Search for `.intoto.jsonl` in the release check.
```
=> ✨  support for SLSA provenance in Signed-Release

checks/raw/fuzzing.go, checks/raw/fuzzing_test.go, docs/checks.md, docs/checks/internal/checks.yaml
Add support for detecting [OneFuzz](https://github.com/microsoft/onefuzz) in fuzzing checks.
- [v] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)
The fuzzing check of scorecard checks for [OSS-Fuzz](https://github.com/google/oss-fuzz), [ClusterFuzzLite](https://google.github.io/clusterfuzzlite/) and in a repo user-defined [golang fuzz functions](https://go.dev/doc/fuzz/) in the repo.
Check for the existence of a [OneFuzz detection file](https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md#detecting-the-use-of-onefuzz) in the repo and give the check a full score (10/10) if such file is found.
- [v] Tests for the changes have been added (for bug fixes/features)
Yes
For …
=> :sparkles: Support OneFuzz in fuzzing checks

checks/permissions_test.go, clients/githubrepo/client.go, clients/localdir/client.go, clients/mockclients/repo_client.go, clients/repo_client.go, remediation/remediations.go
Bug fix - #2051
`remediations.go` uses `GetDefaultBranch` method. `GetDefaultBranch` queries branch protection status. Some of the branch protection attributes need `administration` access, which the `GITHUB_TOKEN` does not have. As a result, remediation code fails when run in scorecard-action, when the repo has branch protection enabled. 
https://github.com/ossf/scorecard/blob/0eb7cb2d748725b177d633bcd421a07fc0732721/clients/githubrepo/branches.go#L94-L106
This PR adds a new method called `GetDefaultBranchName`, which returns the default branch name using `client.repourl.defaultBranch`. This works regardless of branch protection status. 
Signed-off-by: Varun Sharma <varunsh@stepsecurity.io>
Pinned-Dependencies results do not show up in some scorecard-action runs
Pinned-Dependencies …
=> :bug: Fix bug 2051 

checks/all_checks.go, checks/evaluation/signed_releases.go, checks/signed_releases_test.go, e2e/signedreleases_test.go
=> ✨ Favor SLSA provenance over plain signature in Signed-Release

checks/sast.go, checks/webhook.go, cmd/root.go
Scorecard now returns a non-zero exit code if any checks return a runtime error. 
Scorecard returns an exit code of 0 if most checks have runtime errors
Scorecard now returns an exit code of 1 in the same scenarios
Fixes #2124
Had to modify a few existing checks to conform to the new semantics.
```release-note
Scorecard runs with runtime errors now return a non-zero exit code
```
=> ✨ Scorecard returns a non-zero exit code if any check has a runtime error

checks/permissions_test.go, checks/raw/permissions.go, e2e/permissions_test.go
Using `scorecard-action` no longer decreases a project's score. 
Repositories that use `ossf/scorecard-action` lose 1 point due to the Token Permissions check, because `ossf/scorecard-action` requires `security-events: write`. 
This PR adds `ossf/scorecard-action` to the  allowed list of actions that can use `security-events: write` without affecting scoring.
Fixes #2152
```release-note
NONE
```
=> 🐛 Add scorecard-action to the security-events allowlist in Token Permissions check

checks/evaluation/permissions.go, checks/evaluation/pinned_dependencies.go, checks/evaluation/pinned_dependencies_test.go, checks/permissions.go, checks/permissions_test.go, checks/pinned_dependencies.go, remediation/remediations.go, remediation/remediations_test.go
bug fix for incorrect repo info in remediation text. the problem affected the weekly scorecard cron job
The remediation text used to reflect the first repo / branch  processed by a scorecard cron worker.
The remediation text will now match the repo/branch being analyzed. 
#2152 
This is a temporary fix, and modifies the function signatures for `evaluation.PinningDependencies` and `evaluation.TokenPermissions`. I don't think anyone besides ourselves are using these exported functions.
```release-note
NONE
```
=> 🐛 Fix remediation text when Scorecard is run multiple times within a program

.goreleaser.yml
This updates the hash from sha512 to sha256 for release hashes. That's what's expected by the SLSA generator.
sha256 is enough for security
```release-notes
Use sha256 for goreleaser config
```
=> ✨ Use sha256 for release hashes

checks/raw/security_policy.go, checks/security_policy_test.go
This updates the security policy check to find RST files in more places.
Examples of repos this would now catch:
https://github.com/apache/airflow/blob/main/.github/SECURITY.rst
https://github.com/opencast/pyCA/blob/main/SECURITY.rst
RST files are only looked for in doc/ or docs/
RST files are looked for in all the places markdown and asciidoc files are.
NONE
Not a go programmer by trade. Might have messed something up!
```release-note
The Security-Policy check now looks for ReStructuredText (.rst) files in the same place it looks for Markdown and AsciiDoc files.
```
=> :bug: Check for security polices in RST format at toplevel and .github as well

cron/internal/data/add/main.go, cron/internal/data/add/main_test.go, cron/internal/data/add/testdata/skip_duplicates.csv
bug fix
`cron/internal/data/projects.csv` has duplicate entries, which leads to duplicates in the public BigQuery data
e.g.:
```
github.com/adobe-fonts/source-code-pro,criticality_score:0.386850
github.com/adobe-fonts/source-code-pro#release,
```
In the latest BigQuery data, there are two repos with the name `github.com/adobe-fonts/source-code-pro`. One received a score of 4.8 and the other 4.4. The difference is only due to a rate limit error that occurred during one run. They return identical results for me locally.
Uses https://pkg.go.dev/net/url#URL to pull out `host` and `path` when deduplicating `cron/internal/data/projects.csv` entries. Ignoring queries, fragments, etc.
NONE
Changes to `cron/internal/data/projects.csv` were generated by running `make add-projects`
For user-facing …
=> 🐛 Deduplicate projects in cron job by excluding URL queries and fragments

checks/permissions_test.go, checks/raw/permissions.go, checks/testdata/.github/workflows/github-workflow-permissions-contents-writes-release-mvn-release.yaml
This allows workflow steps that call 'mvn release:prepare' to use `contents: write` permissions as they are needed for doing the maven release process.
Somewhere between a bug and a feature
Current behavior is that a workflow that is doing mvn release will get dinged on the Token-Permissions check due to `contents: write` permission for that workflow
A workflow using `mvn release:prepare` will be allowed the `contents: write` permission without lowering the score
NONE
```release-note
The Token-Permissions check no longer penalizes workflows with the `contents: write` permission if they are using it to run `mvn release:prepare`.
```
=> ✨  Allow contents: write for Token-Permissions when doing mvn release 

checks/branch_protection_test.go, checks/evaluation/branch_protection.go, checks/evaluation/branch_protection_test.go, docs/checks.md, docs/checks/internal/checks.yaml, e2e/branch_protection_test.go
Enhance Branch-Protection check to require CODEOWNER review.
This adds 'bonus points' to the Branch-Protection check, but doesn't detract from the score if it's not enabled.
Today, the Branch-Protection check requires that code review must be completed before merge. In GitHub, CODEOWNERS can be assigned to subpaths in a. Without CODEOWNER review, anyone with write access to the repo can approve any PR. In large repos with many modules and many maintainers, CODEOWNERS allows maintainers to delegate code reviews and limit the scope of approval. 
Added a unit test; updated existing unit tests.
```release-note
Scorecard will evaluate whether CODEOWNER review is required for protected branches.
```
=> ✨ Add CODEOWNERS branch protection check

pkg/scorecard.go, pkg/scorecard_test.go
- Fixes the score to `0` for an empty repository.
- Fixes https://github.com/ossf/scorecard/issues/2157
=> :seedling: Fix for empty repository

checks/raw/dependency_update_tool.go, checks/raw/dependency_update_tool_test.go
This adds PyUp as a detected automated dependency update tool
New behavior is that having a .pyup.yml is detected as having an automated dependency tool setup similar to dependabot or renovate.
NONE
```release-note
Projects using PyUp with a .pyup.yml in their repository will now pass the Dependency-Update-Tool check
```
=> ✨ Detect PyUp as an automated dependency update tool

cron/internal/config/config.yaml, cron/internal/config/config_test.go, cron/k8s/worker.release.yaml
feature
SAST is not enabled in the weekly cron
SAST will run in the weekly cron
graphQL API usage will increase from 1 to 2 API calls per repo
NONE
This is running in the daily release test cron job and is working as intended so far. There haven't been any graphQL failures which would require us to fall back to the REST API endpoint. I'll convert this from draft PR to PR when today's test ends.
We have enough graphQL API points available (separate from the REST API limits) to absorb the increase
```release-note
SAST data …
```
=> ✨ Enable SAST check in cron by default

cmd/root.go, errors/public.go
bug fix
Runtime errors in individual checks bubble up to any cobra command created via `cmd.New()` after #2133
This unintentionally broke scorecard-action https://github.com/ossf/scorecard-action/issues/856
Runtime errors are wrapped in a new error, `ErrorCheckRuntime` so that `scorecard-action` can ignore them. Which will be implemented in a separate PR after the next scorecard release.
This is a pretty difficult thing to test, forcing runtime errors to occur in a check.
Partially fixes https://github.com/ossf/scorecard-action/issues/856
application as a result of this …
=> 🐛 Wrap check errors with distinct error for scorecard-action to ignore.

cron/internal/data/iterator.go, cron/internal/data/iterator_test.go, cron/internal/data/testdata/ignore_header.csv, cron/internal/data/testdata/no_header.csv, cron/internal/data/testdata/only_header.csv
Part of a series of refactors to generalize the cron infrastructure to enable re-use by the [ossf criticality score project](https://github.com/ossf/criticality_score)
CSV files read by the controller needed to have a header line:
```
repo,metadata
```
The header line is now optional, and is skipped by the `data.csvIterator`.
Follow up PR for #2235 
```release-note
NONE
```
=> 🌱 cron: make CSV header optional (3/n)

.github/CODEOWNERS
- Invite @spencerschrock as a contributor to Scorecard
- Spencer has been participating and actively contributing https://github.com/ossf/allstar/issues/238
- Spencer has contributed 17 commits https://github.com/ossf/scorecard/commits?author=spencerschrock and some are significant changes.
=> :seedling: Invite @spencerschrock as maintainer

.github/workflows/docker.yml, .github/workflows/main.yml
Signed-off-by: Azeem Shaikh <azeemshaikh38@gmail.com>
Part of #2287. Specify repo-token and cache setup-go. Hopefully to improve CI build times.
```release-note
NONE
```
=> 🌱 Improve API limiting and cache

checks/evaluation/code_review.go, checks/evaluation/code_review_test.go
Fix bug where number of reviewed changesets in a PR was being overcounted.
```release-note
NONE
```
=> 🐛 Fix scoring issue with Code Review check

cron/internal/bq/main.go, cron/internal/bq/main_test.go, cron/internal/worker/main.go
Bug fix
See #2307 for details.
1. the BQ transfer tool will not transfer results for jobs without a `.shard_metadata` file.
2. cron workers won't process requests for jobs without a `.shard_metadata` file.
Note: This makes assumptions about how the pubsub subscription is configured, namely that messages redeliveries are limited. The default value (5 re-tries) works, and is currently being used by scorecardcron.
#2307 
```release-note
NONE
```
=> 🐛 Prevent partial cron transfers caused by controller failures

checks/fileparser/github_workflow.go, checks/fileparser/github_workflow_test.go, checks/testdata/.github/workflows/github-workflow-packaging-maven-multi-line.yaml
Bug fix for #2321 
Line continuations in `run` steps prevented our regex from desired patterns.
Line continuations are removed before matching any `run` steps. This applies to all instances which attempt match run steps, not just maven or packaging usages.
Fixes #2321 
```release-note
NONE
```
=> 🐛 Ignore line continuations when matching run steps.

pkg/scorecard.go, pkg/scorecard_test.go
Bug fix
A bug prevents running on local repos
Running scorecard locally reports a commit of "unknown" since the local directory client doesn't support `ListCommits`. "unknown" is what was being returned before by `sigs.k8s.io/release-utils/version.GetVersionInfo()`
```
"scorecard": {
"version": "",
"commit": "unknown"
},
```
Fixes #2334 
```release-note
NONE
```
=> 🐛 Fix --local functionality

docs/checks.md, docs/checks/internal/checks.yaml
The pinned dependencies check is confusing to authors of libraries, who shouldn't be pinning the dependencies of the library. But it is still valuable for flagging things which are used as part of the build and release process for a library.
Signed-off-by: Jeremy Katz <jeremy@tidelift.com>
Docs update
Currently library maintainers are confused thinking that this check wants them to pin their dependencies but that is not the real intent. This tries to make the documentation a little clearer.
NONE
```release-note
NONE
```
=> 📖 Clarifications about the pinned dependencies check

checks/evaluation/permissions.go, checks/permissions_test.go
Following discussion in #2338, it has been determined that the permissions check should no longer deduct when a job is set to write. This code is a minimalist change, and will require additional polish/cleanup of obsolete logic later.
Signed-off-by: Eddie Knight <iv.eddieknight@gmail.com>
Changes how scoring is done for token permissions
The Token-Permissions check is opinionated regarding job-level permissions.
The Token-Permissions check now will only issue a warning regarding job-level permissions.
Fixes #2338
I wasn't able to get the Token-Permissions check to report anything lower than 10/10 when running locally, even for repos that are less than 10 when checked via the API. As such, my validation checks were limited. I suggest a regular contributor or maintainer validates these …
=> ⚠️ Warn and not fail if job perms are content:write

Dockerfile, cron/internal/bq/Dockerfile, cron/internal/cii/Dockerfile, cron/internal/controller/Dockerfile, cron/internal/webhook/Dockerfile, cron/internal/worker/Dockerfile, cron/k8s/controller.release.yaml, cron/k8s/controller.yaml
* Docker images now use go1.19 like the rest of scorecard. (which was also needed for `GOMEMLIMIT`)
* The controller now has a soft memory limit (with a 5-10% overhead as suggested by the [GC guide](https://tip.golang.org/doc/gc-guide)). The controller failed in a recent run due to `OOMKilled`
NONE
Will apply the config change to the release test first, and then the production controller after a few days
```release-note
NONE
```
=> 🌱 Add soft mem limit to controller k8s spec

checks/evaluation/permissions.go, checks/permissions_test.go
Part of #2338
Signed-off-by: Eddie Knight <knight@linux.com>
=> Removed job-level permissions check for actions and packages

cron/internal/worker/main.go
bug fix
No metadata is present in the public BigQuery dataset
Metadata will now be transferred
NONE
```release-note
NONE
```
=> 🐛 Fix typo which prevented cron metadata from going to BigQuery dataset

.github/dependabot.yml
Dependabot config update
Dependabot auto rebases every one of its open PR when any PR gets merged into main. 
This leads to a lot of unneeded CI runs.
* disables automatic rebasing, so we can rebase 1 by 1 as needed when we approve PRs
* includes some missed Dockerfiles. Some of the distroless base images are 1 year out of date.
NONE
Docs for this flag are [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy)
```release-note …
```
=> 🌱 Disable dependabot auto rebasing when any PR is merged

.github/workflows/goreleaser.yaml, .github/workflows/slsa-goreleaser.yml
Replace deprecated set-output with GITHUB_OUTPUT on workflows.
Use set-output to set outputs in workflows.
Use GITHUB_OUTPUT to set outputs in workflows.
Fixes https://github.com/ossf/scorecard/issues/2376
I was not able to run E2E tests with make e2e-pat.
NONE
=> :bug: Replace deprecated set-output with GITHUB_OUTPUT

.github/dependabot.yml, Dockerfile, cron/internal/bq/Dockerfile, cron/internal/cii/Dockerfile, cron/internal/controller/Dockerfile, cron/internal/webhook/Dockerfile, cron/internal/worker/Dockerfile
Manual group of dependabot PRs, to handle the updates in 1 PR instead of 5.
Also cuts the docker updates to weekly as discussed [here](https://github.com/ossf/scorecard/pull/2378#pullrequestreview-1151317755)
Fixes #2379
Fixes #2380
Fixes #2381 
Fixes #2382  
Fixes #2383
```release-note
NONE
```
=> 🌱 Manual bump every docker distroless:base to `99133cb`

.github/workflows/integration.yml, .github/workflows/main.yml
GitHub action change
codecov fails silently. And the PR waits forever for results to be posted.
the `unit-test` job will fail and can be re-run. 
Typos which affect the codecov upload can be spotted easier
Fixes #2411 
```release-note
NONE
```
=> 🌱 Fail unit-test job if codecov upload fails

checks/raw/binary_artifact.go, cron/k8s/worker.release.yaml
performance optimization
Code relies on calling `unicode.IsPrint`
Fixes #2412
Over the last 3 days, there have been ~40k files in the cron worker release test where the two `isText` implementations have differed.
98% of these differences were the old `raw.isText` returning `false` and new implementation returning `true`. The difference is due to space characters that aren't the ASCII space character (which is the only space where `unicode.IsPrint()` returns true). The following spaces were prevalent in the test repos:
*  [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark)
* [NBSP](https://en.wikipedia.org/wiki/Non-breaking_space)
The other 2% were the new implementation returning `false` and the old implementation returning …
=> 🌱 enable more performant isText

checks/raw/security_policy.go, checks/raw/security_policy_test.go
GitHub probably supports many more file extensions for Markdown files, but at very least `.md` and `.markdown` have been standardized in RFC 7763.
Signed-off-by: favonia <favonia@gmail.com>
`SECURITY.markdown`, `.github/SECURITY.markdown`, or `docs/SECURITY.markdown` will be detected as a security policy.
`SECURITY.markdown`, `.github/SECURITY.markdown`, and `docs/SECURITY.markdown` are ignored.
NONE
```release-note
NONE
```
=> ✨ Detect SECURITY.markdown in addition to SECURITY.md

cron/config/config.go, cron/config/config.yaml, cron/config/config_test.go, cron/internal/monitoring/exporter.go
This is a minor change to configuration to support alternative infrastructure deployments, in particular the criticality score project.
The stackdriver prefix is hardcoded and cannot be overridden.
The stackdriver prefix is now exposed in the config via a `metric-stackdriver-prefix` key.
NONE
```release-note
NONE
```
=> :seedling: cron: expose the stackdriver prefix as a config variable so it can be changed.

cron/internal/controller/main.go
Signed-off-by: Caleb Brown <calebbrown@google.com>
This is a small bug fix to the cron controller
If the raw bucket is not specified in the controller the controller will crash (as is the case for criticality-score).
Previously the non-existent configuration setting would cause a panic, but since it was moved to the additional params section it is now only an empty value.
Writing to the raw bucket will only happen if the value exists in the config.
NONE
```release-note
NONE
```
=> :seedling: [cron] Controller should only write to the rawBucket if the bucket is set in the config.

.github/workflows/scorecard-analysis.yml
Signed-off-by: laurentsimon <64505099+laurentsimon@users.noreply.github.com>
Enable scorecard to run on PR in our CI. Will help us test the Action and find low-hanging problems we can resolve to make pull request support official in the GitHub Action.
```release-note
Run scorecard on incoming pull requests for our CI
```
=> 🌱 Enable scorecard run on pull request

checks/evaluation/permissions.go
closes https://github.com/ossf/scorecard/issues/2482
Only display the remediation message for `Warn` messages.
For more information on release notes see: https://git.k8s.io/release/cmd/release-notes/README.md
-->
```release-note
Only display the remediation message for `Warn` messages.
```
=> 🐛 Fix remediation message

checks/evaluation/cii_best_practices.go, checks/raw/maintained.go, checks/raw/pinned_dependencies.go, options/flags.go
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>
Fixes a few malformed copyright notices.
A few copyright notices are missing the year and one uses the wrong name for the attribution.
All copyright notices have the same format and specify a year (the missing ones were added based on git commit history).
NONE
Only in source code.
```release-note
```
=> :book: Fix copyright notices

checks/raw/permissions.go, checks/raw/pinned_dependencies_test.go, checks/raw/shell_download_validate.go, checks/raw/testdata/.github/workflows/github-workflow-pkg-managers.yaml, checks/raw/testdata/Dockerfile-pkg-managers, checks/raw/testdata/script-pkg-managers, docs/checks.md, docs/checks/internal/checks.yaml
This PR accepts commands like `go install blah@v1.0.0`, considering fully versioned Go modules pinned.
`go install blah@v1.0.0` is currently considered unpinned, but it is effectively pinned in practice.
Fixes #2491.
* This also fixes the current parser in two ways:
1. Do not detect `go INSTALL` but only `go install`.
1. Skip flags between `get`/`install` and packages but record the flag `-insecure`.
* `goconst` is turned off for `"none"` because the string has very different meanings in different places in the package.
```release-note
Go modules with full semantic versions are now considered pinned.
```
=> ✨ Accept Go modules with semantic versions

.golangci.yml, dependencydiff/dependencydiff_test.go, e2e/e2e_suite_test.go
- Remove parallel tests because of rate limiting.
=> :seedling: Remove parallel tests because of rate limiting issues.

README.md
docs update
Fixes #2526 
Not sure about the title, let me know what you think
```release-note
NONE
```
=> 📖 Mention 2FA relevance although not checked by Scorecard

clients/githubrepo/branches.go, clients/githubrepo/contributors.go, clients/githubrepo/graphql.go, clients/githubrepo/languages.go, clients/githubrepo/licenses.go, clients/githubrepo/releases.go, clients/githubrepo/webhook.go, cmd/root.go
Signed-off-by: laurentsimon <laurentsimon@google.com>
closes https://github.com/ossf/scorecard/issues/2522
This PR fixes https://github.com/ossf/scorecard/issues/2522.
To avoid this type of problems in the future, we need to add check that runs scorecard twice (with the same clients) and verify the results are all the same: https://github.com/ossf/scorecard/issues/2533
```release-note
fix: license check accumulates results
```
=> 🐛  license check accumulates results

attestor/README.md, attestor/command/check.go, attestor/policy/attestation_policy.go, attestor/policy/attestation_policy_test.go, e2e/attestor_policy_test.go
Add E2E tests. Also refactor the check runner to allow dependency injection.
=> 🌱 attestor: e2e tests

.gitignore, checker/client.go, checks/evaluation/vulnerabilities.go, checks/raw/vulnerabilities.go, checks/raw/vulnerabilities_test.go, checks/vulnerabilities.go, checks/vulnerabilities_test.go, clients/githubrepo/client.go, clients/githubrepo/tarball.go, clients/gitlabrepo/client.go, clients/localdir/client.go, clients/mockclients/repo_client.go, clients/mockclients/vulnerabilities.go, clients/osv.go, clients/osv_test.go, clients/repo_client.go, clients/vulnerabilities.go, docs/checks.md, docs/checks/internal/checks.yaml, e2e/attestor_policy_test.go, e2e/vulnerabilities_test.go, go.mod, go.sum
Feature
Currently the vulnerability check only checks if the HEAD commit hash has any vulnerability specified in OSV.dev. Most of the time this will return 10/10.
This integrates the OSV-Scanner library, which will scan for manifest and SBOM files, retrieve the dependencies, and match those dependencies with OSV.dev database as well. (The commit hash check is still being done, though through the osvscanner library rather than directly setting up a client to use the OSV API).
Fixes #2162
Currently the e2e tests fail because the Scorecard score has changed since osvscanner found 3 vulnerabilities. I can change the expected results to match, but this might cause more issues in the future as new vulnerabilities are discovered, causing tests to break even though there are no code changes. Not …
=> :warning: OSV scanner integration

.goreleaser.yml
Signed-off-by: laurentsimon <laurentsimon@google.com>
OSV-Scanner depends on a library that cannot be built for 32bit platforms, so this PR removes them from released binaries.
```release-note
Remove 32bit platforms from GoReleaser architectures
```
=> 🐛  Remove 32bit platforms from GoReleaser architectures

checker/raw_result.go, checks/branch_protection_test.go, checks/evaluation/branch_protection.go, checks/evaluation/branch_protection_test.go, checks/raw/branch_protection.go, checks/raw/branch_protection_test.go, e2e/branch_protection_test.go, pkg/json_raw_results.go
Ensure that the CODEOWNRS file exists for the corresponding Branch-Protection check by gathering a set of CODEOWNERS files in the repo. If file doesn't exist, CODEOWNERS branch protection is not in effect even if the setting is enabled. This fixes a bug where we would have incorrectly reported scores for the branch protection check.
Fixes #2348.
=> 🐛 Ensure CODEOWNERS file exists for corresponding Branch-Protection check

checks/raw/shell_download_validate.go, checks/raw/shell_download_validate_test.go
- Fixed the https://github.com/ossf/scorecard/issues/2549
- It was panicking because of this https://github.com/slsa-framework/slsa-github-generator/blob/9dc8c627749ae437f7759a3ecec9f740e677e3e1/.github/actions/detect-workflow/Dockerfile#L20
=> :bug: Fix broken go mod download check

checks/raw/branch_protection.go
bug fix
`scorecard` prints messages like `got codeowners file at .github/CODEOWNERS` which makes the result invalid, at least when using https://github.com/ossf/scorecard-action with sarif output
example: https://github.com/nginxinc/nginx-kubernetes-gateway/actions/runs/3744585459/jobs/6358515861#step:4:238
NONE
```release-note
NONE
```
=> 🐛 Remove unnecessary Printf

.github/workflows/docker.yml
CI fix
Due to path filtering, PRs which only change Markdown files will never run the steps in `docker.yml`:
https://github.com/ossf/scorecard/blob/c6d76807b76b7b72659525e103d6b1284c7b01b5/.github/workflows/docker.yml#L20-L30
Since these checks are (currently) required, PRs which only change Markdown files can never be merged. See #2565 and #2508. As long as these checks are required, there's no native way to solve this for reasons summarized well in [this blog post](https://blog.pantsbuild.org/skipping-github-actions-jobs-without-breaking-branch-protection/).
A third party action is used to detect doc only changes. Since skipped checks count as passing for required checks, this allows for doc only changes to merge.
NONE
I tested this …
=> 🌱 Switch from paths-ignore to changed-files action to skip required checks.

.github/workflows/scorecard-analysis.yml
We keep hit rate limits on PRs, so let's disable anything that's not necessary for now.
```release-note
Disable scorecard on PRs
```
=> ✨ Disable scorecard on PRs

README.md
Signed-off-by: Mike Maraya <mmaraya@users.noreply.github.com>
Doc update to clarify that classic, not fine-grained, personal access tokens are required for the scorecard CLI to work
(Is it a bug fix, feature, docs update, something else?) docs update
```
Error: RunScorecard: internal error: ListCommits:error during graphqlHandler.setup: internal error: githubv4.Query: non-200 OK status code: 401 Unauthorized body: "{\"message\":\"Personal access tokens with fine grained access do not support the GraphQL API\",\"documentation_url\":\"https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql\"}"
```
NONE
(In particular, describe what changes users might need …
=> 📖 specify that classic personal access tokens are needed

docs/checks.md
On GitHub Branch-Protection configuration there was a rule called "Include administrator", which forced the admins to follow the same rules. It was renamed to "Do not allow bypassing the above settings", we we're updating scorecard accordingly.
Signed-off-by: Diogo Teles Sant'Anna <diogoteles@google.com>
Docs Update
No issue created
Talked to @laurentsimon before creating this PR.
No
```release-note
NONE
```
=> :book: Update name of Branch Protection Rule :book:

checks/evaluation/pinned_dependencies.go, remediation/remediations.go, remediation/remediations_test.go
Tagged and unpinned images are detected, but the remediation suggestion discards the tag which is problematic for reasons pointed out in #2581.
The Docker remediation code now maintains the tag, based on whatever is in the `PinnedAt` field of the `checker.Dependency` struct.
Fixes #2581
```release-note
Suggested remediations for unpinned Docker images now maintain any tags that were present.
```
=> 🐛  Retain tag when remediating unpinned docker images.

.github/workflows/integration.yml
This is a CI Performance Improvement. 
Currently, Integration tests take ~13m & every run on every PR (without approval).
This Proposed changes will improve that & it would run Integration Test only on approved PRs.
Fixes #2603
No
```release-note
NONE
```
> Signed-off-by: Siddhant Khare <Siddhantkhare2694@gmail.com>
=> :seedling: performance: run integration tests only on approved PRs

.github/workflows/integration.yml
Bug fix for infra
Reverts ossf/scorecard#2609
`pull_request_review` doesn't have access to secrets, so the e2e tests are failing
https://github.com/ossf/scorecard/actions/runs/3989324836
should work as before
```release-note
NONE
```
=> 🌱  Revert "perf.: run integration tests only on approved PRs (#2609)"

CONTRIBUTING.md
Signed-off-by: Gabriela Gutierrez <gabigutierrez@google.com>
Update docs on how to how to run Scorecard locally and debug Go files by logging to console or to an output file.
Currently the docs don't explain how to run Scorecard locally, only how to build it. I added instructions on how to run it locally. The other thing is there are currently no debug instructions. Debugging is more Go language related than Scorecard related but I thought adding some debug instructions would be useful.
None.
```release-note
Update docs on how to run and debug Scorecard locally
```
=> :book: Update docs on how to run and debug locally

e2e/fuzzing_test.go
Temporary test change
The Oss-Fuzz e2e test is failing because the implementation isn't currently working, consuming extra e2e tokens due to the retry mechanism, before ultimately failing and blocking PRs.
Temporarily skip the test until #2670 is resolved.
```release-note
NONE
```
=> :seedling: Temporarily skip OSS-Fuzz e2e test.

.github/workflows/integration.yml
Integration test change
Some of the integration tests need access to GitHub secrets, specifically the branch protection e2e tests.
The integration test trigger was changed to `pull_request` which does not have access to GitHub secrets.
The status message when integration tests finish was removed to reduce the permissions of the GITHUB_TOKEN
This was tested in another repo to verify the GITHUB_TOKEN was sufficient.
https://github.com/spencerschrock/scorecard-test/actions/runs/4188418627/jobs/7259527613
```release-note
NONE
```
=> 🌱 Limit integration tests to ones that work with the GITHUB_TOKEN.

.github/CODEOWNERS
- Add @raghavkaul as a CODEOWNERS file maintainer
- Update the CODEOWNERS file
https://github.com/ossf/scorecard/graphs/contributors
[.github/CODEOWNERS]
- Add @raghavkaul to CODEOWNERS file
=> 📖    Invite @raghavkaul as maintainer

go.mod, go.sum
- Update dependencies `github.com/emicklei/go-restful` to fix this https://osv.dev/vulnerability/GHSA-r48q-9g5r-8q2h
Fixes https://deps.dev/go/github.com%2Fossf%2Fscorecard%2Fv4
=> :seedling: Update deps for fixing GHSA-r48q-9g5r-8q2h

checks/evaluation/ci_tests.go, checks/evaluation/ci_tests_test.go
Adds Azure Devops as a valid CI system when running the CI check
Repos that are tested with Azure Devops get 0 as a score, as it is not recognized
Repos that are tested with Azure Devops are not penalized
Fixes #2661 
I removed an entry as well, as it did not seem to possibly have any effect and also had
no tests associated
```release-note
Azure Devops is now a recognized CI system
```
=> :sparkles: Add Azure Devops to CI checks

checks/fileparser/github_workflow.go
Slight feature / bug fix. The `imjasonh/setup-ko` workflow was moved to https://github.com/ko-build, and thanks to GitHub redirect magic, both names can be used in a workflow -- the imjasonh ref redirects to the ko-build one.
Workflows using the old `imjasonh/setup-ko` will not be matched as using a packaging workflow.
NONE
NONE
```release-note
ko-build/setup-ko is detected as a packaging workflow
```
=> ✨ Consider ko-build/setup-ko as a packaging workflow

pkg/json.go, pkg/json_test.go, pkg/testdata/check1.json, pkg/testdata/check2.json, pkg/testdata/check3.json, pkg/testdata/check4.json, pkg/testdata/check5.json, pkg/testdata/check6.json
- Update date format in multiple files from `YYYY-MM-DD` to `YYYY-MM-DDTHH:MM:SS-TZ`
Feature
Fixes https://github.com/ossf/scorecard/issues/2711
```release-note
The date format in the JSON results has been changed to RFC3339
```
=> :warning: Update date formats and fields to RFC3339 in JSON results

clients/githubrepo/checkruns.go, clients/githubrepo/checkruns_e2e_test.go, clients/githubrepo/client.go, clients/githubrepo/graphql.go, clients/githubrepo/graphql_e2e_test.go, clients/githubrepo/repo.go
Refactoring to keep all check run code in one place. No logic change.
NONE
```release-note
NONE
```
=> 🌱 Refactor githubrepo CheckRun logic

checks/fileparser/listing.go, checks/fileparser/listing_test.go
Enhancement: improve the quality of the default scoring
Files in `testdata` directories are ignored by default, but files in `src/test` directories are not.
`src/test` is also recognized as a test directory
NONE
This directory is found in projects that follow the Maven [Standard Directory Layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html), which is fairly widely used, not only in Maven but also in adjacent ecosystems like Gradle and clojure.
Longer-term this would become part of the default policy, see discussion at https://github.com/ossf/scorecard/pull/1408#issuecomment-999806097 etc.
For more information on release notes see: https://git.k8s.io/release/cmd/release-notes/README.md
```release-note
`src/test` directories are now …
```
=> :sparkles: Consider 'src/test' test directories

dependencydiff/dependencydiff_test.go
fixes https://github.com/ossf/scorecard/issues/2715
```release-note
```
=> 🌱 Removed failing tests

clients/githubrepo/roundtripper/rate_limit.go, clients/githubrepo/roundtripper/transport.go, clients/githubrepo/stats/stats.go, cron/config/config.yaml, cron/config/config_test.go, cron/k8s/auth.yaml, cron/k8s/worker.release.yaml, cron/k8s/worker.yaml
cron update
The cron used personal access tokens
* Dropped the GITHUB AUTH server to 0 replicas since it doesn't support the GitHub App tokens
* Added logic for `retry-after` headers and some metrics when/if we see it.
* Disabled 4 checks which don't work well at the moment
* Search based checks hit secondary rate limits frequently with the GitHub App tokens
* `Dependency-Update-Tool`
* `Fuzzing`, which should be re-enabled again soon now that #2719 is merged
* `SAST`
* `Vulnerabilities` due to an inefficiency in osv-scanner that has been fixed upstream but needs a new release cut
* Runtime errors are ignored in the release worker due to known errors with the `Branch-Protection` check while using a GitHub App token
[] Tests for the changes have been added (for bug fixes/features)
NONE
For …
=> 🌱 Setup cron for running as GitHub App

Makefile
- Updated the `Makefile` to include the `-coverpkg=./...` flag when running tests.
[Makefile]
- Changed `SKIP_GINKGO=1 go test -race -covermode=atomic  -coverprofile=unit-coverage.out` to `SKIP_GINKGO=1 go test -race -covermode=atomic  -coverprofile=unit-coverage.out -coverpkg=./...` in the `Makefile`
https://github.com/ossf/scorecard/issues/2203
```release-note
NONE
```
=> :seedling: Updated the coverage for tests

checks/raw/pinned_dependencies_test.go, checks/raw/shell_download_validate.go, checks/raw/testdata/.github/workflows/github-workflow-pkg-managers.yaml, checks/raw/testdata/Dockerfile-download-lines, checks/raw/testdata/Dockerfile-pkg-managers, checks/raw/testdata/script-pkg-managers, checks/raw/testdata/shell-download-lines.sh
Handle editable pip installs in Pinned-Dependencies check.
When performing `pip install -e <pkg>`, the install can be considered secure if the package and it's dependencies are hash-pinned. The package can come from a local or remote source (VCS install). If the package is local, it is considered secure. If the package is remote, it needs to pinned by commit hash to be secure. We have no way to identify if the dependencies installed from requirements are hash-pinned. The flag `--require-hashes` does not work with `-e` flag. To guarantee we are not installing malicious dependencies, we can use `--no-deps` flag to not install the dependencies. That way the install can be considered secure.
| | |
| -- | -- |
| secure | pip install --no-deps -e …
=> :bug: Handle editable pip installs

.github/workflows/goreleaser.yaml
- Update `goreleaser/goreleaser-action` to `v2.5.0`
- Remove GPG key import step and `GPG_FINGERPRINT` from environment variables
- Move `version_flags` to `GITHUB_OUTPUT`
[.github/workflows/goreleaser.yaml]
- Remove GPG key import step
- Update `goreleaser/goreleaser-action` to `v2.5.0`
- Remove `GPG_FINGERPRINT` from environment variables
- Move `version_flags` to `GITHUB_OUTPUT`
```release-note
```
=> :seedling: Update .github/workflows/goreleaser.yaml

checks/ci_tests.go, checks/ci_tests_test.go
bug fix
Runtime errors in the `CI-Tests` check would return a `Code-Review` result due to a copy/paste typo.
The typo is fixed and the function returns a `CI-Tests` result.
Fixes #2686 #2746
Will also help https://github.com/ossf/scorecard-action/issues/1076 and https://github.com/ossf/scorecard-action/issues/1094 once a new release is cut
```release-note
The CI-Tests check will show the correct check name when it encounters a runtime error.
```
=> 🐛 Fix typo in CITests runtime errors causing duplicate Code-Review checks.

.goreleaser.yml
- Remove GPG signing from .goreleaser.yml
- Set `skip` parameter to `false` in .goreleaser.yml
[.goreleaser.yml]
- Remove the GPG signing from the .goreleaser.yml file
- Change the `skip` parameter to `false` in the .goreleaser.yml file
```
• starting release...
• loading config file                              file=.goreleaser.yml
• loading environment variables
• getting and validating git state
• building...                                    commit=9ad975764535b9753fbcb0c78335f826dbb213c4 latest tag=v4.10.3
• parsing tag
• setting defaults
• running before hooks
• running                                        hook=go mod download
• checking distribution directory
• --rm-dist is set, cleaning it up
• loading go mod information
• build prerequisites
• proxying go module
• proxying …
```
=> 🌱 Fix goreleaser

checks/raw/code_review.go, checks/raw/code_review_test.go
Remove unused code from changeset creation logic.
```release-note
NONE
```
=> 🌱 Remove unused code from changeset creation

clients/githubrepo/client.go
bug fix
A small typo during a refactor (#2710) caused the checkRun graphQL query to be run with a commit depth of 0 when no commit depth is specified, so the query returned no data. This was causing more SAST checks to be cache misses.
```
go run main.go --repo ossf/scorecard --checks SAST --format json
INFO[0023] listCheckRunsForRef cache miss: ossf/scorecard:476a246ebbafa7f8785505621010f76123bd5059 
INFO[0024] listCheckRunsForRef cache miss: ossf/scorecard:f26282c2f3b3bcc099c1167cf62a87cfd79afbf8 
INFO[0024] listCheckRunsForRef cache miss: ossf/scorecard:227bb4a7df92eb217670c46893ac25cb19dbed25
... etc
```
The proper value is passed to the checkrun handler, so the graphQL query populates data and there are fewer cache misses.
For user-facing changes, please add a concise, human-readable …
=> 🐛  Pass proper commit depth to github checkrun handler.

cmd/root.go, options/options.go, pkg/sarif.go, pkg/sarif_test.go, pkg/scorecard_result.go
See discussion at https://github.com/ossf/scorecard-action/issues/1107
Set 
- `SCORECARD_INTERNAL_GITHUB_INTEGRATION=1`
- `SCORECARD_INTERNAL_GITHUB_SARIF_TOOL_NAME=<tool-name>`
- `SCORECARD_INTERNAL_GITHUB_CHECKS=check1,check2,<others>`
The GitHub team will be able to create a workflow:
```yaml
- uses: ossf/scorecard-action@<ref>
env:
SCORECARD_INTERNAL_GITHUB_INTEGRATION: 1
SCORECARD_INTERNAL_GITHUB_SARIF_TOOL_NAME: <the-name>
SCORECARD_INTERNAL_GITHUB_CHECKS: check1,check2,check3
```
Note that this is a "hidden feature" and that's why we don't expose it via a proper Action input.
```release-note
Add internal flags to support GitHub's internal scans
```
=> ✨ Support for GitHub's internal integration

checks/raw/code_review_test.go
bug fix
`phabricatorCommitD` and `commitB` both have `RevisionID` of 2.
Both of these commits are used in the `mixed: phabricator + gh` test
The map iteration order isn't deterministic and sorting the slices isn't good enough when the revision IDs are equal.
This is causing the unit-tests to fail intermittently on unrelated PRs. e.g. #2780 
https://github.com/ossf/scorecard/actions/runs/4494760078/jobs/7907638544?pr=2780#step:7:138
review platform is used as a tie breaker when sorting in the test code
NONE
```release-note
NONE
```
=> 🐛 Add tie breaker when sorting changesets by RevisionID in tests.

cron/config/config.yaml, cron/config/config_test.go
cron update
The Fuzzing check was disabled in the cron due to high Search API usage.
This was fixed in #2719, so re-enable the fuzzing check
- [] Tests for the changes have been added (for bug fixes/features)
NONE
```release-note
NONE
```
=> 🌱 re-enable fuzzing check in cron.

cron/internal/format/bq.raw.schema
bug fix
The raw result BigQuery transfer has been failing for a while due to schema changes. The [raw results outputted by the cron](
https://github.com/ossf/scorecard/blob/dde9aa1aefb9e26196c03ef7401287ff2fd35b01/cron/internal/format/json_raw_results.go#L101-L115) is kept separate from the [raw results in the rest of Scorecard](https://github.com/ossf/scorecard/blob/dde9aa1aefb9e26196c03ef7401287ff2fd35b01/pkg/json_raw_results.go#L252). This was done intentionally to avoid changes breaking the cron, although the two have diverged quite a bit.
The schema has been updated to include the new fields introduced to the cron version of the struct. Once applied to `openssf:scorecardcron.scorecard-rawdata`, the upload of raw results should resume, although there is further work to be done to get …
=> 🐛  Restore upload of existing raw result Big Query data

clients/githubrepo/roundtripper/rate_limit.go, clients/githubrepo/roundtripper/transport.go
cron update
The `X-RateLimit-Remaining` header value was reported by the `githubTransport` (e.g. `GITHUB_AUTH_TOKEN`, `GITHUB_TOKEN`, or a `GITHUB_AUTH_SERVER`).  This transport isn't used with GitHub Apps so the cron doesn't currently have stats for API quota usage.
The `X-RateLimit-Remaining` `Record()`ing is moved to `rateLimitTransport` so the value is reported regardless of the kind of token used. This seems like the better place for it anyway.
NONE
`TokenIndex` is one of the grouping tags for GitHub token view:
https://github.com/ossf/scorecard/blob/9358843a7f1b85617aa222c17acde2536bf3da8a/clients/githubrepo/stats/stats.go#L35-L42
The docs didn't have a clear answer on what happens if one of the `TagKeys` tags isn't set (the GitHub App transport doesn't set `TokenIndex` since it's …
=> 🌱 Restore API quota metrics for the weekly cron job.

checks/permissions_test.go, checks/raw/permissions.go, checks/testdata/.github/workflows/github-workflow-permissions-secevent-known-actions.yaml
Recognizes that [haskell-actions/hlint-scan](https://github.com/haskell-actions/hlint-scan) is supposed to upload SARIF files and hence needs the `security-events: write` permission.
haskell-actions/hlint-scan is not recognized as a code scanning action which uploads SARIF, so Scorecard reports a `Token-Permissions` alert.
haskell-actions/hlint-scan is now recognized as a code scanning action which uploads SARIF. Unit tests were added that cover not only this addition, but also existing code scanning actions that had no corresponding unit tests.
Fixes https://github.com/ossf/scorecard/issues/2840
application as a result of …
=> :sparkles: Consider haskell-actions/hlint-scan a code scanning action

docs/faq.md
Fixes a few broken links in the FAQ.
NONE
```release-note
NONE
```
=> :book: Fix broken links in FAQ.

.codecov.yml, attestor/policy/attestation_policy.go, attestor/policy/attestation_policy_test.go
- Unit tests for attestor policy
```release-note
```
=> :seedling: Unit tests for attestor policy

checker/client_test.go
- Included the unit tests for checker/client.go
- Coverage to 87%
```release-note
```
=> :seedling: Unit Tests for checker/client

checks/evaluation/license_test.go
- Add tests for license scoring criteria
- Add license checker tests for no license, no license files, and license files detected
- 100% coverage.
```release-note
```
=> :seedling: Unit tests for  checks/evaluation/license.go

clients/githubrepo/checkruns.go, clients/githubrepo/checkruns_test.go
bug fix in the cron
The checkruns handler never clears `errSetup`
The checkruns handler clears `errSetup` when it's `init`'d again, or when `setup` is run.
Fixes #2892 
```release-note
NONE
```
=> 🐛 Reset stored error when handler is re-inited or setup is re-run.

.github/workflows/publishimage.yml
fix workflow
this workflow uses go 1.17 which breaks because our dependencies rely on features in 1.18 or 1.19.
It's been broken for a while now
Use the go version specified in our go.mod file (currently 1.19) so it stays up-to-date
NONE
The `imjasonh/setup-ko` repo was renamed. So https://github.com/imjasonh/setup-ko redirects to https://github.com/ko-build/setup-ko
This was tested locally with [act](https://github.com/nektos/act)
```release-note
NONE
```
=> :seedling: Use Go version as specified by our go.mod file for publishimage.

options/flags.go, options/options.go, pkg/json.go, pkg/scorecard_result.go
This PR adds a new format `finding` to improve on the existing `json` format. This new format will be the same as `json`, but will display the details in a more structured format.
Note that this is *not* the final "structured" format. This is a simpler version of it.
I have named the format "finding" because it's the underlying structure that will be used to populate it, but please suggest a better name.
```release-note
Add a new format for details
```
=> ✨ Add a new format for details

.github/workflows/publishimage.yml
the cosign step fails since it asks for a confirmation prompt:
```
By typing 'y', you attest that (1) you are not submitting the personal data of any other person; and (2) you understand and agree to the statement and the Agreement terms at the URLs listed above.
Are you sure you would like to continue? [y/N] Error: signing [ghcr.io/ossf/scorecard/v4:f3b777086fb670ed5b10b4d1d7257786d0daa6d6]: recursively signing: signing digest: should upload to tlog: user declined the prompt
main.go:74: error during command execution: signing [ghcr.io/ossf/scorecard/v4:f3b777086fb670ed5b10b4d1d7257786d0daa6d6]: recursively signing: signing digest: should upload to tlog: user declined the prompt
Error: Process completed with exit code 1.
```
`cosign …
=> :seedling: Skip cosign confirmation prompt during publishimage action.

docs/faq.md
It is a doc update to add a new question on FAQ.
NONE
```release-note
Update FAQ to cover doubt on dependabot/renovatebot trustfulness
```
=> 📖 Add new frequently asked question to FAQ

checks/sast.go
bug fix
A workflow step with `env` or `with` set, but without a `uses` field causes the SAST check to panic.
https://github.com/nl-design-system/denhaag/blob/329158ae47a4bfafb424741b2699f8c254ffd671/.github/workflows/cicd.yml#L103-L112
We check for nil pointers before deref
NONE
```release-note
NONE
```
=> :bug: Add nil check before accessing a step's uses value.

docs/checks.md, docs/checks/internal/checks.yaml, docs/faq.md
:book: Documentation fix to capitalize proper nouns, Dependabot and Renovate bot. Github is already correct in all instances. 
No change
No change 
Fixes https://github.com/ossf/scorecard/issues/2055
Minor changes to documentation. Generated `docs/checks.md` from `docs/checks/internal/checks.yaml` by running make `generate-docs`
```release-note
NONE
```
=> :book: Capitalize proper nouns like Dependabot, Renovate, and GitHub

docs/checks/internal/checks.yaml
This clarifies that AI/ML doesn't count as human code review. This was earlier done in #2953 but that didn't modify the relevant .yml file - this does.
=> :book: Clarify AI/ML not human code review - in .yml file

README.md
Not sure what the old facilitators table was for. Current list of Maintainers is always in CODEOWNERS.
Meaning of "Maintainers" still is not defined, and should be a part of an upcoming contributor ladder.
doc: update readme.
no
```release-note
NONE
```
=> :book: Change Facilitators to Maintainers

docs/checks.md, docs/checks/internal/checks.yaml
This is a doc update that makes all StepSecurity app endpoints to use https://app.stepsecurity.io/secureworkflow/. Prior to this update, some pages where using https://app.stepsecurity.io/secureworkflow/ whereas some pages had https://app.stepsecurity.io/ as the app endpoint. This update will allow us (StepSecurity) to repurpose the home page for other scenarios in the future.
StepSecurity app references are inconsistent as some references use https://app.stepsecurity.io/secureworkflow/ whereas some references cite https://app.stepsecurity.io/ as the app endpoint.
This update makes all references consistent to use https://app.stepsecurity.io/secureworkflow/.
NONE
(In particular, describe what …
=> :book: Make all StepSecurity app endpoint references consistent

docs/checks.md, docs/checks/internal/checks.yaml
docs update
The current documentation explains why should be configured at least 1 reviewers as required but it does not mention the benefit of having 2 or more reviewers required. Since it is a requisite to maximize branch protection score and most projects would find it difficult to demand 2 reviewers to each PR, it might be a good idea to make it clear why should they require 2 instead of 1.
Doc updated to explain the benefit of having 2 instead of 1 reviewers required.
Fixes #2472 
None
```release-note
Update branch protection document to explain why it is recommended to …
```
=> 📖 Update checks.md to show the benefit of >=2 reviewers

.github/workflows/main.yml
ci fix
e2e-pat was being ran against PRs and causing ci to fail since the PAT is inaccessible from a `pull_request` target.
follow up of #3046 and #3054 
This is to quickly get the CI working again. Still might be a better separation of jobs/workflows, but this should get it working. 
```release-note
```
=> :seedling: Skip e2e-pat target on pull requests

e2e/security_policy_test.go
e2e test speedup
tensorflow/tensorflow is huge and was slowing down tests because the whole repo was downloaded to scan for a security policy file. 
* The e2e tests now use https://github.com/ossf-tests/scorecard-check-security-policy-e2e, which is a much smaller repo and takes less time to clone.
* Also removed the rust e2e tests because they're already present as unit tests.
- [] Tests for the changes have been added (for bug fixes/features)
```release-note
```
=> :seedling: Speed up Security-Policy e2e tests

.github/workflows/main.yml
Don't run GitHub PAT E2E tests on dependabot merges to the `main` branch since those merges don't have access to environment secrets. 
`github.actor` is dependabot when using `dependabot merge`; when the PR approver also merges the PR, they are the github.actor. 
See: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
=> 🌱 CI: Don't run PAT E2E on dependabot merges

e2e/attestor_policy_test.go, e2e/ci_tests_test.go
e2e bandaid fix
1 e2e test is skipped, the other has some cases commented out
Related to #3129 , but does not fix it. Only allows us to merge other PRs
```release-note
NONE
```
=> :seedling: temporarily disable failing e2e tests

.codecov.yml, dependencydiff/dependencydiff.go
- Deprecate the `dependencydiff` package and the `GetDependencyDiffResults` function
- Add a line to the `.codecov.yml` to ignore the `dependencydiff` package
```release-note
```
=> :seedling: Deprecate dependencydiff package 

e2e/dependencydiff_test.go
linter is failing, related to #3125 
linter will ignore the tests.
```release-note
```
=> :seedling: Ignore deprecation warning for dependencydiff tests.

e2e/attestor_policy_test.go, e2e/ci_tests_test.go
Follow up to #3130
* Re-enables skipped tests
Reduced attestor e2e test times by ~50%
* Switches code-review attestor tests to a smaller repo in `ossf-tests`, instead of using `ossf/scorecard`
* trims un-needed policies from tests that aren't using them (code review tests don't need binary artifact policies, etc)
Fixes #3129
It's hard to see changes with everything being uncommented. So a better comparison would be to the version before the tests were disabled (just scroll to the right file):
https://github.com/ossf/scorecard/compare/d961dda3b2350d1484948bd2b7efa46210c47e41...ossf:scorecard:a43601cc408a60f96e5a6e3d7e012a84c13a5239#diff-1eb6d0cf3162bc067afd6a66f7e7380fef3bab5185a2faa320edbe9ea2282453
the …
=> :seedling: Re-enable skipped e2e tests. Switch to smaller code review repo.

clients/githubrepo/webhook_e2e_test.go
- Add e2e test for webhookHandler
```release-note
```
=> 🌱  Improve webhookHandler E2E tests

options/flags.go
Add the available argument strings for the ```--verbosity``` flag in the usage message of the scorecard cli.
```release-note
NONE
```
=> 📖  update usage message of the scorecard --verbosity flag 

Dockerfile, clients/githubrepo/roundtripper/tokens/server/Dockerfile, cron/internal/bq/Dockerfile, cron/internal/cii/Dockerfile, cron/internal/controller/Dockerfile, cron/internal/webhook/Dockerfile, cron/internal/worker/Dockerfile
This is a PR to update the golang docker images in one swoop instead of 7 PRs.
Fixes #3179 
Fixes #3183
Fixes #3184
Fixes #3185
Fixes #3186
Fixes #3187
Fixes #3188
```release-note
```
=> :seedling: Bump golang from `4b1fc02` to `6b3fa4b`

clients/githubrepo/roundtripper/tokens/accessor_test.go
- Add test file for Token Accessor
```release-note
```
=> :seedling: Included tests for accessor

clients/githubrepo/roundtripper/tokens/rpc_test.go
- Add tests for TokenOverRPC.Next and TokenOverRPC.Release
```release-note
```
=> :seedling: Added unit tests for rpc

clients/githubrepo/roundtripper/rate_limit.go, clients/githubrepo/roundtripper/rate_limit_test.go
- Add rate limit testing and handling functionality
- Add tests for successful response and Retry-After header set scenarios
```release-note
```
=> :seedling: Unit tests  rate limit handling in roundtripper

cron/internal/data/update/dependency.go
Linter complains about deprecated package.
Linter is silenced.
Related to #3262 but does not fix it
```release-note
NONE
```
=> :seedling: Ack linter warning for deprecated module and add tracking issue.

checks/sast.go
=> :bug: Fix typo

README.md
Docs update
At the README we're providing the code for the Scorecard badge using the [old result output](https://api.securityscorecards.dev/projects/github.com/ossf/scorecard)
Now the documentation points to the [new viewer](https://securityscorecards.dev/viewer/?uri=github.com/ossf/scorecard)
NONE
```release-note
NONE
```
=> 📖  Suggest new score viewer on badge documentation

Makefile
- Update the cover profile for e2e
- https://github.com/onsi/ginkgo/issues/1161
```release-note
```
=> :seedling: Update the cover profile for e2e

e2e/workflow_test.go
- Add e2e test for workflow runs
- Retrieve successful runs of the scorecard-analysis.yml workflow
```release-note
```
=> :seedling: Improve e2e workflow tests

cmd/internal/scdiff/app/format/format.go, cmd/internal/scdiff/app/generate.go, cmd/internal/scdiff/app/root.go, cmd/internal/scdiff/app/runner/runner.go, cmd/internal/scdiff/app/runner/runner_test.go, cmd/internal/scdiff/main.go
feature
This adds the cobra boilerplate for the binary (`scdiff`), and the subcommand `generate`.
Right now the code expects a newline-delimited list of repos in a file:
```
github.com/ossf/scorecard
github.com/ossf/scorecard-action
```
The command will run Scorecard against all repos in the file
```
go run cmd/internal/scdiff/main.go generate --repos repos.txt
```
Currently this just prints to stdout, but I'll write to a file format in a later PR.
Related to #2462, but this is the first of many PRs
All of this is in an `internal` folder, so I'll be able to make breaking changes to it later as I iterate.
application as a …
=> :sparkles: scdiff: generate cmd skeleton

.github/dependabot.yml, .github/workflows/docker.yml, attestor/Dockerfile
CI and repo config
The attestor dockerfile isnt being updated, so it's using an older version of golang. 
This caused [the build to break](https://github.com/ossf/scorecard/runs/15205406012) on the latest merged PR (#3284).
- golang updated to the same version as all other dockerfiles
- the dockerfile has been added to dependabot
- a build step has been added to catch this sort of thing before merge.
NONE
```release-note
```
=> :seedling: Include attestor Dockerfile in CI and dependabot updates

.github/workflows/docker.yml
ci logic deduplication
The docker images all get built with the same logic and setup. 
When adding a new image (like #3285), this involves a lot of unnecessary copy/pasting which is more of a burden to maintain. 
- workflow uses a single-dimension matrix.
- no longer installs protoc, the docker images build without it.
- disabled caching for `actions/setup-go`, the Go tooling is only needed for a few Makefile expressions, all of the `go build` happens in the docker images. I think this is saving empty caches, and resulting in cache hits in other workflows that should be "misses".
NONE
This includes renaming one of the required checks. I can mark the new one as required once approved.
`cron-cii--worker-docker` -> `cron-cii-worker-docker`
For user-facing changes, please add a concise, …
=> :seedling: Use a matrix for docker image building

.github/workflows/docker.yml
ci fix
After #3290, doc only changes cause the required docker jobs to hang. You can see this in #3246.
This is due to how skipped matrices work https://github.com/orgs/community/discussions/9141
The if statement has been moved down to every step.
NONE
```release-note
NONE
```
=> :seedling: Fix hanging docker jobs for doc only changes.

.github/workflows/gitlab.yml, .github/workflows/integration.yml, .github/workflows/main.yml
ci update
The caching in our ci/cd is flawed, and despite having caching setup for these steps implicitly through `actions/setup-go`, they take a long time to download modules and build.
The 3 longest running jobs (unit-test, github integration, gitlab integration) now share a cache. 
Since they all download the modules, and build, they should have a nearly full cache. 
NONE
```release-note
NONE
```
=> :seedling: Add separate cache for long-running tests

clients/ossfuzz/client_test.go
- Included tests for  IsArchived, LocalPath, ListFiles, GetFileContent, GetBranch, GetDefaultBranch, GetOrgRepoClient, GetDefaultBranchName, ListCommits, ListIssues, ListReleases, ListContributors, ListSuccessfulWorkflowRuns, ListCheckRunsForRef, ListStatuses, ListWebhooks, SearchCommits, Close, ListProgrammingLanguages,
```release-note
```
=> :seedling: Unit tests OSSFuzz client

.github/workflows/main.yml, Makefile
ci change
PR authors/maintainers need to remember to check if `docs/checks/internal/checks.yaml` and `docs/checks.md` are kept in sync. Sometimes this doesn't happen (e.g #2772)
The CI job now calls `git diff --exit-code` to ensure the two are in sync.
- If someone commits to `docs/checks.md` directly, then the changes will be overwritten when `make generate-docs` is ran, and `git diff` will fail the job. 
- If someone commits to `checks.yaml` directly, then `make generate-docs` will modify `checks.md`. Which `git diff` will detect and fail.
I also included some cleanup in the action:
-  version comments are accurate
- we dont need protoc for this job
-  we dont need full commit history
- caching is handled through setup-go
None
For user-facing changes, please add a concise, …
=> :seedling: Ensure check markdown is kept in sync with source yaml.

README.md
Fixes the slack badge that is currently broken
NONE
Let me know if style is an issue... these badges are highly customizable.
No
```release-note
NONE
```
=> :book: Fixed slack badge on README

checks/evaluation/permissions/gitHubWorkflowPermissionsTopNoWrite.yml, probes/toolDependabotInstalled/def.yml
- Update Dependabot documentation links where they currently redirect.
- Remove language code from GitHub documentation URLs in scorecard report.
English specific GitHub documentation links are shown to users in the scorecard report.
Language-agnostic GitHub documentation links are shown to users in the scorecard report. This then allows GitHub's documentation to redirect the user to a more appropriate language (Spanish, Japanese etc.) if relevant to the user viewing them.
NONE
NONE
```release-note
Remove links to English-specific GitHub documentation so users' language preferences are respected where possible.
```
=> :sparkles: Update GitHub documentation links in report

clients/gitlabrepo/languages_e2e_test.go
- Add an end-to-end test for the `gitlabrepo.ListProgrammingLanguages` function
- Include a test for repos without code to check that no programming languages are returned
[clients/gitlabrepo/languages_e2e_test.go]
- Add an e2e test for the `gitlabrepo.ListProgrammingLanguages` function
- Add a test for repos without code to check that no programming languages are returned
```release-note
```
=> :seedling: Improve `gitlabrepo.ListProgrammingLanguages` e2e tests

cmd/internal/scdiff/app/format/format.go, cmd/internal/scdiff/app/format/format_test.go, cmd/internal/scdiff/app/generate.go
feature
scorecard results were printed verbatim by the scdiff tool
certain fields, such as dates or commit shas, are stripped before printing.
these fields are informational, but don't provide value in detecting a change in scorecard behavior. instead they interfere with the comparison
Related to https://github.com/ossf/scorecard/issues/2462, 2/n
```release-note
NONE
```
=> :sparkles: scdiff: normalize scorecard results

clients/gitlabrepo/tarball_e2e_test.go
- Add end-to-end test for the gitlabrepo package
- Initialize a gitlab repo and list its files
- Retrieve content for a specific file in the repo
```release-note
```
=> :seedling: E2e for clients/gitlabrepo/tarball

clients/githubrepo/roundtripper/tokens/accessor.go, clients/githubrepo/roundtripper/tokens/accessor_test.go
test bug fix
If a dev has any of the env vars set, the `TestMakeTokenAccessor` will fail locally for them.
All possible env vars that the accessor reads from are cleared before this test
NONE
@laurentsimon can you confirm this fixes your issue?
```release-note
```
=> :bug: Clear all possible token env vars for token accessor test.

clients/gitlabrepo/issues_e2e_test.go
E2e tests for Gitlab issues. The list issues will fail as it requires additional permissions.
```release-note
```
=> 🌱 E2e Gitlab Issues

clients/gitlabrepo/workflow_e2e_test.go
- List the webhooks and check that there is at least one returned
```release-note
```
=> :seedling: Add E2E test for Gitlab repo webhooks

clients/ossfuzz/client.go, clients/ossfuzz/client_test.go, clients/ossfuzz/testdata/status.json
bug fix
- parsing ossfuzz projects whose `main_repo` field points to a subfolders (eg. `github.com/google/go-cmp/cmp`), doesn't register when asked about `github.com/google/go-cmp`)
- parsing ossfuzz projects that have different capitalization from GitHub's view causes ossfuzz detection to fail
- `main_repo` fields to subfolders are parsed correctly
- the internals of the oss-fuzz client use lowercase strings to standardize capitalization.
Fixes #3256
Fixes #3257 
```release-note
NONE
```
=> :bug: Fix parsing OSSFuzz project repos with subfolders and capitalization.

clients/gitlabrepo/statuses_test.go, clients/gitlabrepo/webhook_test.go
- Update test names and response paths for statuses and webhooks
- Change the error message when fetching webhooks
```release-note
```
=> :seedling: Improve GitLab repo status and webhook tests

.github/workflows/docker.yml, .github/workflows/gitlab.yml, .github/workflows/goreleaser.yaml, .github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/publishimage.yml, .github/workflows/slsa-goreleaser.yml, CONTRIBUTING.md, Dockerfile, attestor/Dockerfile, clients/githubrepo/roundtripper/tokens/server/Dockerfile, cron/internal/bq/Dockerfile, cron/internal/cii/Dockerfile, cron/internal/controller/Dockerfile, cron/internal/webhook/Dockerfile, cron/internal/worker/Dockerfile
dependency update
- use go1.19, which is no longer supported
- use go1.21 for our CI and builds/releases
- keep go1.19 in our go.mod as we don't currently use any 1.20 or 1.21 features. this is for our dependents.
#3386 
```release-note
Scorecard releases will now use go1.21
```
=> :seedling: Migrate to go 1.21

clients/git/client_test.go
- Add test functions to the Git client for testing repository initialization, commit listing, and search functionality
[clients/git/client_test.go]
- Add `createTestRepo` function to set up a test repository
- Add `TestInitRepo` to test the initialization of a repository
- Add `TestListCommits` to test the listing of commits
- Add `TestSearch` to test the search functionality
```release-note
```
=> :seedling: Unit tests for git client

checks/evaluation/permissions/permissions.go, clients/git/client_test.go, clients/gitlabrepo/issues_test.go, clients/gitlabrepo/workflows.go, pkg/json_raw_results.go
bug fix
Loop aliasing produces incorrect behavior. The linter started detecting this after #3411 got merged.
> G601: Implicit memory aliasing in for loop. (gosec)
We create a fresh copy of data so multiple things aren't pointing to the same data by accident.
https://github.com/ossf/scorecard/actions/runs/5942446350
```release-note
```
=> :bug: Fix loop aliasing errors causing linter to fail.

clients/gitlabrepo/client.go, clients/gitlabrepo/licenses.go, e2e/license_test.go
Updates the GitLab client so that we can get SPDXId from the GitLab API. A software license's SPDXId allows us to determine whether a GitLab repo's License is FSF/OSI-recognized, and get the last 1/10 points on the License check, which was previously impossible for GitLab repos.
Fixes #3333.
=> 🐛 Licenses: Get License SPDXId from GitLab API

checks/binary_artifact.go, checks/raw/binary_artifact.go, checks/raw/binary_artifact_test.go, policy/policy_test.go
feature
- local repos can't use the `Binary-Artifacts` check.
- local repos can use `Binary-Artifacts`, but there are no gradle-wrapper exceptions because we can't verify workflow runs locally (see #2039)
Fixes #3258
```release-note
```
=> :sparkles: Support Binary-Artifacts check again for local repos

checks/raw/license.go
bug fix
If GitHub doesn't detect a license, the project gets a 0
We use our existing local file detection if github doesn't detect a license
Fixes #3279
```release-note
Fixed bug where the Licenses folder wasn't being detected.
```
=> :bug: fallback to local file detection on empty GitHub license response.

clients/githubrepo/tarball.go, clients/githubrepo/tarball_test.go
bug fix
> If the Security-Policy check is run for a repo owned by an org with an empty .github repo, it runs a warning.
the error doesn't print if the repo being looked at is `.github`
Fixes #3076
```release-note
The Security-Policy check will no longer print to the log if the org's .github repo is empty.
```
=> :bug: Ignore missing tarballs for empty org .github repos

checker/check_result.go, checks/raw/permissions.go, checks/sast.go, probes/internal/utils/tools/tools.go
Changes "thru" to "through" wherever "thru" occurs in comments.
Typo fix
This fix is unrelated to behavior. 
NONE
No
```release-note
NONE
```
=> :bug: Fix typos

checks/raw/binary_artifact.go
Static archives do not lead to score reduction in Binary Artifacts, although `.o` files do and `.a` correspond to a group of `.o` files.
Static archives lead to score reduction.
Did not add a test because only a few binary checks have these. It may also be in the interest of size for the repository not to have `.a` files stored?
NONE
None
```release-note
Add static archives as binary artifacts
```
=> :sparkles: Check for static archives in Binary Artifacts

.github/workflows/stale.yml
This is a workflow update to reduce the number of label types being exempted from the stale workflow.
Most issues are not being addressed with this stale workflow.
More issues will be processed by stale workflow.
n/a
Please let me know if other labels need to remain exempt.
No used facing change
```release-note
```
=> :seedling: workflows/stale: Update exempt labels

.github/workflows/stale.yml
Adds an action to close issues marked for inactivity after 7 days.
Issues are marked as stale, but not closed.
Issues will be closed after being marked stale, similar to the behavior for stale PRs
NONE
No
```release-note
NONE
```
=> 🌱 workflows/stale: Update workflow to include issue close action

.github/workflows/stale.yml
Increases operations-per-run from default of 30 to 100 to test whether older issues will be marked as inactive
Issues are only marked as inactive as they reach the 60 day trigger, but are not being marked if they have been at 60+ days of inactivity
Older issues will be marked as inactive as well
NONE
No
```NONE
```
=> 🌱 workflows/stale: Update workflow to increase operations-per-run to process more issues

.codecov.yml
- With our current coverage upload setup, it will always show a drop of 6-7% (see #3388). This is also confusing to contributors (https://github.com/ossf/scorecard/pull/3426#issuecomment-1724484499)
- The patch config is broken, so it essentially always passes: `50.00% of diff hit (within 90.00% threshold of 74.34%)`
- The goal here was probably a target of 90%, not a threshold
The project status is converted to [informational](https://docs.codecov.com/docs/commit-status#informational), so it will always pass. 
> Use Codecov in informational mode. Default is false. If true is specified the resulting status will pass no matter what the coverage is or what other settings are specified. Informational mode is great to use if you want to …
=> :seedling: Reduce confusion around codecov check status.

README.md, docs/faq.md
Adds GitLab links in webviewer sections
Docs update
```release-note
```
=> :book: Add gitlab links to viewer example

checks/fileparser/github_workflow_test.go, go.mod
Fixing a likely typo in test code
We import `gotest.tools/assert/cmp` to compare two string slices. This library is only used in one place.
The comparison now uses `cmp.Equal` from `github.com/google/go-cmp/cmp`, allowing us to eliminate the dependency.
NONE
I moved `github.com/rhysd/actionlint` down to be with the other imports.
```release-note
```
=> :seedling: Switch test import to remove gotest.tools dependency.

pkg/scorecard.go
bug fix
The results at head currently always list the commit as `HEAD`. Introduced in #3426 
```console
go run main.go --repo ossf/scorecard --checks License --format json | jq
{
"date": "2023-09-25T08:39:59-07:00",
"repo": {
"name": "github.com/ossf/scorecard",
"commit": "HEAD"
},
```
if successfully fetched, the commit SHA is set in the results.
```console
go run main.go --repo ossf/scorecard --checks License --format json | jq
{
"date": "2023-09-25T08:44:16-07:00",
"repo": {
"name": "github.com/ossf/scorecard",
"commit": "fd12f6a4e2f1d5c9b0afb3c41c67a943f13dea39"
},
```
NONE
application as a result of this pull …
=> :bug: Set repo commit SHA in results after fetching successfully.

.github/workflows/stale.yml
Issues are still getting closed after https://github.com/ossf/scorecard/pull/3493. I assume there's a default value being used somewhere.
ci fix
Issues are still getting closed (like #2614), even though #3493 was merged.
`days-before-issue-close` is explicitly marked `-1` to disable auto-close.
NONE
```release-note
```
=> :seedling: Don't close stale issues explicitly

pkg/scorecard_result_test.go
test fix
Because the unit test uses a hard coded file, and the test deletes this file, a race condition exists when multiple versions of the test are run in parallel. This happens with our e2e tests as we call `ginkgo -p`.
The test doesn't hardcode an output file name, and instead uses a random name provided by [os.CreateTemp](https://pkg.go.dev/os#CreateTemp):
e.g.`/tmp/result-file2178365783`
NONE
The error message from ginkgo was very vague. It used to present more information
https://github.com/ossf/scorecard/actions/runs/6398651796/job/17369225051
```console
Running Suite: Pkg Suite - /home/runner/work/scorecard/scorecard/pkg
====================================================================
Random Seed: 1696369398
Will run 0 of 1 specs
Running in parallel across 2 processes …
```
=> :seedling: Fix race condition in output file test.

probes/internal/utils/test/test.go
Adds a test helper suitable to check the output from probes in tests.
https://github.com/ossf/scorecard/issues/3472
NONE
```release-note
```
=> :seedling: Add probe test utility

Dockerfile, attestor/Dockerfile, clients/githubrepo/roundtripper/tokens/server/Dockerfile, cron/internal/bq/Dockerfile, cron/internal/cii/Dockerfile, cron/internal/controller/Dockerfile, cron/internal/webhook/Dockerfile, cron/internal/worker/Dockerfile
manual dep upgrade to save dependabot spam
Includes the distroless/base uprgade from #3547  and the golang upgrade from https://github.com/ossf/scorecard-action/pull/1272. 
Note: this repo uses the general 1.21 tag (compared to the 1.21.2 tag in `scorecard-action`), but the digest is shared.
```console
$ crane digest golang:1.21
sha256:e9ebfe932adeff65af5338236f0b0604c86b143c1bff3e1d0551d8f6196ab5c5
```
```release-note
NONE
```
=> :seedling: Bump distroless/base from `27647a6` to `29da700` and golang from `ec457a2` to `e9ebfe9`

finding/finding.go
Adds a numeric map to the Finding type as discussed in https://github.com/ossf/scorecard/issues/2928.
https://github.com/ossf/scorecard/issues/2928
NONE
```release-note
```
=> :seedling: Add map to Finding

cmd/internal/scdiff/app/generate.go
bug fix
When no `--checks` arg is provided, the `checksArg` string is the empty string. 
`strings.Split` of the empty string returns a slice containing the empty string, so the `parseChecks` helper func thought it was a requested check.
If no arg is provided, `strings.Split` isn't called, so the intended "run all check instead" behavior is used.
Followup of #3535 
I could alternatively return an error if a requested check doesn't match the available checks 
```release-note
NONE
```
=> :bug: scdiff: fix generate cmd when no `--checks` arg provided

cmd/internal/scdiff/app/compare.go, pkg/json.go, pkg/json_test.go
scdiff enhancement
- timestamps must be RFC3339, which works for data generated by `scdiff generate`. but the cron data uses the `2006-01-02` format.
- `compare` stops at the first error
- Tries to parse again as `2006-01-02` format if parsing as `RFC3339` doesn't work.
- prints all differences, not just the first.
NONE
```release-note
NONE
```
=> :sparkles: scdiff: improve `compare` usability

checks/raw/fuzzing.go, checks/raw/fuzzing_test.go
This PR adds checks support for the `fast-check` (JS/TS) test runners interactions (`@fast-check/ava`, `@fast-check/jest` and `@fast-check/vitest`).
`fast-check` (JS/TS) test runners interactions are not detected.
Fixes #3567
```release-note
Add support for `fast-check` test runners integrations
```
=> :sparkles: Add support for fast-check test runners integrations

checks/sast.go, checks/sast_test.go
The app slug for CodeQL appears to have changed from `github-advanced-security` to `github-code-scanning`, causing the SAST rule to false-negative on commits.
This appears to have happened some time in the last week (the JSON below suggests from `2023-10-17T19:04:33Z` when the app was last updated). I looked into this today after noticing a lot of security warnings appearing in repos I maintain advising that a SAST tool isn't being used this week where it was previously working fine and with no changes to its infrastructure.
Here are some GitHub API responses showing the change to the app's slug in the check runs for commits tested in a pull request.
- [martincostello/lambda-test-server@448887974ed92795d8c5994300d29b4b9a99fb37](https://api.github.com/repos/martincostello/lambda-test-server …
=> :bug: Fix SAST no longer working for CodeQL

clients/gitlabrepo/client.go, clients/gitlabrepo/client_test.go
Cannot scan private GitLab repos with access token.
Fixes https://github.com/ossf/scorecard/issues/3581
```release-note
Fix scanning for GitLab private repositories.
```
=> :bug: scanning gitlab private repositories

checks/raw/fuzzing.go, cron/internal/controller/main.go, cron/internal/pubsub/subscriber_gcs.go, cron/internal/worker/main.go, policy/policy.go, policy/policy_test.go
lint fix
There are linter errors
Errors are either addressed or ignored if false positives.
NONE
This is the second time this has happened, so I opened #3602 to get to the root cause.
```release-note
```
=> :seedling: Fix linter issues caught by new linters in golangci-lint v1.55.0

finding/finding.go
feature
Add WithValues function to findings to simplify the creation of probes findings.
```release-note
Add WithValues function to findings
```
=> :sparkles: Add WithValues function to findings

.github/CODEOWNERS, MAINTAINERS.md
Docs update
- (N/A) Tests for the changes have been added (for bug fixes/features)
Individual maintainer assignments within CODEOWNERS mean that we cannot take advantage of GitHub code review distribution schemes for team review assignments.
In this commit, we switch to team assignments within CODEOWNERS.
A common complaint with this approach is that unless you are a part of the GitHub organization, you will not be able to view a team's membership/understand who the maintainers of a project are.
To provide visibility into the maintainer list, we've added a MAINTAINERS.md here as well.
Resolves the TODO comments left in https://github.com/ossf/scorecard/pull/1530.
(In particular, describe what …
=> :book: CODEOWNERS: Support distribution of code reviews via team assignments

.github/workflows/stale.yml
Exempts Structured Results issues from being labeled stale
Exemptions are based on labels only and it is not immediately clear which labels are exempt.
Contributors can apply Structured Results milestone rather than having to remember labels for exemption.
NONE
```None
```
=> 🌱 Update stale workflow to exempt Structured Results milestone

pkg/common.go
data quality issue?
For now, this is just producing very long detail strings. Probably negatively affecting cron results
Remediation details from findings aren't included in the detail strings
Related to #3349
```release-note
NONE
```
=> :bug: remove probe remediations from detail strings

checker/raw_result.go, checks/evaluation/sast.go, checks/evaluation/sast_test.go, checks/raw/sast.go, checks/raw/sast_test.go, checks/raw/testdata/.github/workflows/airflows-codeql.yaml, checks/raw/testdata/.github/workflows/pom.xml, checks/sast.go, checks/sast_test.go, checks/testdata/.github/workflows/airflow-codeql-workflow.yaml, e2e/sast_test.go, finding/finding.go, probes/entries.go, probes/sastToolCodeQLInstalled/def.yml, probes/sastToolCodeQLInstalled/impl.go, probes/sastToolCodeQLInstalled/impl_test.go, probes/sastToolRunsOnAllCommits/def.yml, probes/sastToolRunsOnAllCommits/impl.go, probes/sastToolRunsOnAllCommits/impl_test.go, probes/sastToolSonarInstalled/def.yml, probes/sastToolSonarInstalled/impl.go, probes/sastToolSonarInstalled/impl_test.go
This PR rewrites the SAST check to 3 different probes. The SAST check before this change contained both creation of raw results and the evaluation part, so to convert it to probes, I've had to split it into raw results, probes and evaluation. As such, the SAST check was also missing testing - both whole unit tests and variety of input in existing tests - and I have added more tests.
At a high level, the raw results will return a new struct called `SASTData`. This struct contains the following information for each probe:
**CodeQL Probe:**
- All CI workflows of the project that use CodeQL
**Sonar Probe:**
- All CI workflows of the project that use Sonar
**Probe that checks whether SAST runs in every commit:**
- A list of all commits. Each commit is marked either Compliant or not Compliant …
=> :seedling: Convert SAST check to probes

e2e/attestor_policy_test.go, e2e/fuzzing_test.go
e2e test speedup
Theres 2 tests which are 1-2 orders of magnitude slower than other e2e tests:
- "Should return use of OSS-Fuzz"
* `tensorflow/tensorflow` is a really big repo and this test downloads the repo.
- "Should attest to repos based on policy"
* this one runs scorecard repeatedly on the same repos
- "Should return use of OSS-Fuzz"
* `ossf/scorecard-webapp` is a much smaller repo which is fuzzed by OSSFuzz
- "Should attest to repos based on policy"
* split into 3 smaller tests
* Since only one test dealt with `ossf-tests/scorecard-binauthz-test-good`, I changed the existing test to just test this one.
* for the other two repos ( `ossf-tests/scorecard-binauthz-test-bad` and `ossf-tests/scorecard-attestor-code-review-e2e`), I changed the tests so they only fetch the results once, …
=> :seedling: speedup slowest e2e tests

.github/dependabot.yml
dependabot config change
- GitHub actions are their own PR
- Updates are sent daily
- updates are sent weekly
- Most actions are grouped. Actions which influence the build/release process are excluded, so dependabot will send individual updates for those.
* "actions/setup-go"
* "arduino/setup-protoc"
* "goreleaser/goreleaser-action"
```release-note
```
=> :seedling: configure dependabot to group (most) GitHub actions weekly

checks/raw/pinned_dependencies.go, checks/raw/pinned_dependencies_test.go, checks/raw/testdata/vendor/Dockerfile-not-pinned-as
This checks whether Dockerfiles being checked by Pinned Dependencies are in a `vendor` or `third_party` directory.
With this PR, Scorecard will check whether any of the subdirectories that a file exists in is called either `vendor` or `third_party`.
https://github.com/ossf/scorecard/issues/1095
Yes, scores will change, but that is inherited from https://github.com/ossf/scorecard/issues/1095
```release-note
Scorecard no longer considers unpinned Dockerfiles in `vendor` and `third_party` directories.
```
=> :bug: Ignore unpinned dependencies in Dockerfiles in vendored directories

.github/workflows/scdiff.yml
workflow fix
- The functionality was limited to members, owners, and collaborators, as I had thought that would cover all of the maintainers. But my association for [this comment](https://github.com/ossf/scorecard/pull/3680#issuecomment-1815290915) was as a contributor (can check with the [api response](https://api.github.com/repos/ossf/scorecard/issues/comments/1815290915)). So my attempt to call it [here](https://github.com/ossf/scorecard/actions/runs/6896330152/job/18762213022) failed
```
Error: You don't have access to run scdiff
```
- Repo contributors can call scdiff
- also removes the edited trigger. codecov edits PR comments a few times, which causes this action to trigger 3x. It ends up skipped though since it doesnt have the command in it, but might as well remove it
NONE
For …
=> :seedling: allow repo contributors to call scdiff workflow

checks/evaluation/pinned_dependencies.go, checks/evaluation/pinned_dependencies_test.go
The goal of this PR is to refactor the Pinned Dependencies evaluation to process findings instead of dependencies. The reason for doing this is to structure the code to resemble how it would look once it gets split into probes without modifying the score. As such, this is an intermediary code change towards migrating the Pinned Dependencies check into probes. Some of the code changes in this PR will be moved into probes in the near future.
My motivation for this PR is to reduce the review overhead. This PR is already substantial, and adding probes would add to that. As such, with this PR I want to refactor the code so it works as-is and make incremental steps towards migrating the check to probes.
The core change of this PR is an added step of converting the dependencies to findings and …
=> :seedling: refactor pinned dependencies

checks/evaluation/maintained.go, probes/hasRecentCommits/impl.go, probes/issueActivityByProjectMember/impl.go
Converts the Maintained finding value keys to constants as discussed in https://github.com/ossf/scorecard/issues/3641.
Part of https://github.com/ossf/scorecard/issues/3641
NONE
```release-note
```
=> :seedling: make maintained values keys constants

checks/raw/shell_download_validate_test.go
follow up of #3705 to get the linter green again. 
This was an order of operation issue, since #3694 was merged, but we only surface new issues.
```release-note
```
=> :seedling: remove ununsed nolint directives

checks/evaluation/pinned_dependencies.go, checks/evaluation/pinned_dependencies_test.go
Refactoring
Currently processing errors are not converted to findings before evaluation logs them.
Change the pinned dependencies evaluation so that processing errors are converted to findings with `OutcomeNotAvailable` before evaluation logs them.
NONE
NONE
```release-note
```
=> :seedling: Pinned dependencies: create findings from processing errors

checks/branch_protection_test.go, checks/evaluation/branch_protection.go, checks/evaluation/branch_protection_test.go, clients/branch.go, clients/githubrepo/branches.go, clients/githubrepo/branches_test.go, clients/gitlabrepo/branches.go, cron/internal/format/json_raw_results.go, pkg/json_raw_results.go, pkg/json_raw_results_test.go
While the current approach works with the tiered scoring, it wont work for probes or if we remove tiers. Making the struct nil to signal that PRs aren't required hides some of the data we do have.
This is especially problematic for repo rules, where we can infer all settings by what we see or don't see.
bug fix, followup of #3499
`RequiredPullRequestReviews` is a pointer
`RequiredPullRequestReviews` is a struct again
there's a new field `Required *bool` to measure if the PRs are required
The most important changes are in `clients/githubrepo/branches.go`:
1. For admin tokens, Required is assumed to be `&false`, unless we have data otherwise.
2. For non admin tokens, Required is left nil, unless we have data otherwise.
3. For repo rules, Required is assumed to be `&false`, unless we have …
=> :bug: revert making RequiredPullRequestReviews a pointer

cron/internal/format/json_raw_results.go, pkg/json_raw_results.go, pkg/json_test.go, pkg/scorecard_result_test.go
Adding the Required field to PullRequestReviewRule in #3728  made BranchRef slightly too big (>128 bytes) for the linter's `rangeValCopy` rule. This code isn't highly used, so just ignoring any potential inefficiency.
Not sure why the `staticcheck` linter started complaining about the date error checking, but fixed it while I was here.
linter fix
```release-note
NONE
```
=> :seedling: fix rangeValCopy linter issues

remediation/remediations.go
Small typos in comments in the remediation package.
Those small typos in comments in the remediation package have been corrected.
NONE
NONE
Generated docs will have fewer typos in the remediation package.
```release-note
NONE
```
=> :book: fixup transposition typos in remediation package copy

clients/gitlabrepo/checkruns.go, clients/gitlabrepo/checkruns_test.go
Adds a check to `listCheckRunsForRef` in the Gitlab Handler to differentiate between shas and branches/tags and makes appropriate changes to the gitlab api call based on that check. 
`listCheckRunsForRef` in the GItlab Handler takes in a `ref` string, but assumes that the ref is a sha when making the gitlab api call. Gitlab API sometimes handles refs as a branch or tag name, while sha refers to a commit hash. If in the future we passed in a branch or tag to `listCheckRunsForRef` the API would fail since we would handle it as a sha. 
Added a check to compare the passed in `ref` string against a regex matching a SHA value. If there is a match we handle the ref as a SHA, otherwise we handle it as a ref (branch/tag)
Fixes #3395 
For user-facing changes, please add a concise, human-readable …
=> 🌱  differentiate between refs and sha gitab

pkg/json.go, pkg/sarif.go, pkg/sarif_test.go
- Fixed potential nils.
```release-note
```
=> :bug: Fix nils

checks/dependency_update_tool_test.go, checks/raw/dependency_update_tool.go
bug fix
Repos which dont have any dependency update tool config files fallback to searching for dependabot commits. For local repos, this search isn't supported and results in an error
The primary data is the configuration files and the search commit data is just extra, so better to return some data than no data in this case.
We can eventually add the commit searching for local repos via #1709.
Fixes #2985
```release-note
NONE
```
=> :bug: Dependency-Update-Tool: ignore search commit data for repo clients which dont support it

checks/evaluation/permissions/permissions.go
- Update message for when no tokens are found
[checks/evaluation/permissions/permissions.go]
- Change the message for when no tokens are found from "no github tokens found" to "no tokens found"
```release-note
```
=> :bug: Update token permissions check and scoring

checks/evaluation/signed_releases.go, checks/evaluation/signed_releases_test.go
- Fixed the issue where an empty gitlab repo is causing this error. `Error: check runtime error: Signed-Releases: internal error: could not get release name 2023/12/27 18:07:19 error during command execution: check runtime error: Signed-Releases: internal error: could not get release name exit status 1`
```release-note
```
=> :bug: Fix signed release error for empty gitlab repo

checks/evaluation/signed_releases.go, checks/evaluation/signed_releases_test.go, probes/releasesHaveProvenance/impl.go, probes/releasesHaveProvenance/impl_test.go
bug fix
the `releasesHaveProvenance` was creating too many findings for repos which had more than 5 releases with provenance, which violated an assumption of the `Signed-Releases` evaluation code
the `releasesHaveProvenance` probe only generates 5 releases, and a consistency check was added to the evaluation code
Fixes #3766
```release-note
Fixed a bug which allowed some repos to score higher than 10 in the Signed-Releases check.
```
=> :bug: ensure Signed-Releases only scores 5 releases

checks/signed_releases_test.go, probes/releasesAreSigned/impl.go
Scorecard fails to detect `*.sigstore` signature bundles.
Fixes #3771
```release-note
Support `.sigstore` bundles to check for signed releases
```
=> :sparkles: Support `.sigstore` bundles to check for signed releases

probes/hasOSVVulnerabilities/def.yml, probes/hasOSVVulnerabilities/impl.go, probes/hasOSVVulnerabilities/impl_test.go
bug fix
The OSV IDs are joined together when generating a link, leading to a broken link:
For example, if a vuln is known by both `foo` and `bar`, the link was `https://osv.dev/bar,foo` which is broken, but `https://osv.dev/bar` or `https://osv.dev/foo` would have worked.
The first Vuln ID is used for the link, from the example above that leads to `https://osv.dev/bar`
Also added a space after the link, so the period wouldn't be interpreted as part of the link in the remediation text.
Fixes #3609
```release-note
NONE
```
=> :bug: Fix OSV URI in probe remediation text

README.md
=> 📖 Clarify lack of 2FA check in README

checks/raw/fuzzing.go, internal/fuzzers/fuzzers.go, probes/fuzzedWithCLibFuzzer/impl.go, probes/fuzzedWithCLibFuzzer/impl_test.go, probes/fuzzedWithClusterFuzzLite/impl.go, probes/fuzzedWithClusterFuzzLite/impl_test.go, probes/fuzzedWithCppLibFuzzer/impl.go, probes/fuzzedWithCppLibFuzzer/impl_test.go, probes/fuzzedWithGoNative/impl.go, probes/fuzzedWithGoNative/impl_test.go, probes/fuzzedWithJavaJazzerFuzzer/impl.go, probes/fuzzedWithJavaJazzerFuzzer/impl_test.go, probes/fuzzedWithOSSFuzz/impl.go, probes/fuzzedWithOSSFuzz/impl_test.go, probes/fuzzedWithPropertyBasedHaskell/impl.go, probes/fuzzedWithPropertyBasedHaskell/impl_test.go, probes/fuzzedWithPropertyBasedJavascript/impl.go, probes/fuzzedWithPropertyBasedJavascript/impl_test.go, probes/fuzzedWithPropertyBasedTypescript/impl.go, probes/fuzzedWithPropertyBasedTypescript/impl_test.go, probes/fuzzedWithPythonAtheris/impl.go, probes/fuzzedWithPythonAtheris/impl_test.go, probes/fuzzedWithRustCargofuzz/impl.go, probes/fuzzedWithRustCargofuzz/impl_test.go, probes/fuzzedWithSwiftLibFuzzer/impl.go, probes/fuzzedWithSwiftLibFuzzer/impl_test.go
structured result cleanup
the constants are defined in multiple places across the code base (raw data and probes)
The constants are defined in one place, and used elsewhere. 
Fixes #3407
```release-note
NONE
```
=> :seedling: use a single source of truth for fuzzer names

finding/finding.go, finding/finding_test.go, remediation/remediations_test.go, rule/rule.go, rule/rule_test.go
- Fixed field alignment
```release-note
```
=> :seedling: Fixed field alignment

checks/raw/dependency_update_tool.go, checks/raw/dependency_update_tool_test.go
enhancement/fix
no gitlab config files
gitlab config files added
also organize the list in order of appearance on website. this makes it easier to compare.
Related to #542
```release-note
Dependency-Update-Tool now detects Renovate config files in a `.gitlab` folder.
```
=> :sparkles: dependency-update-tool: detect GitLab Renovate config files

.github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/gitlab.yml, .github/workflows/goreleaser.yaml, .github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/publishimage.yml, .github/workflows/scdiff.yml, .github/workflows/slsa-goreleaser.yml, Dockerfile, attestor/Dockerfile, clients/githubrepo/roundtripper/tokens/server/Dockerfile, cron/internal/bq/Dockerfile, cron/internal/cii/Dockerfile, cron/internal/controller/Dockerfile, cron/internal/webhook/Dockerfile, cron/internal/worker/Dockerfile, tools/go.mod
Go version bump
Use Go 1.21
* Use Go 1.22 for our CI and dockerfiles.
* Our minimum Go version in our `go.mod` is unchanged
* I did bump the `tools/go.mod` proactively incase any of our tools switch to requiring 1.22, this makes it so we dependabot PRs don't fail later
```release-note
NONE
```
=> :seedling: Update Go toolchain to 1.22

checks/sast_test.go
test cleanup
we only checked the result score, which produces test failures without clear actionable feedback.
I discovered this during another refactor and it was hard to figure out what the issue was.
```
--- FAIL: Test_SAST (0.00s)
--- FAIL: Test_SAST/SAST_checker_should_return_failed_status_when_no_PRs_are_found (0.00s)
~/checks/sast_test.go:319: Expected score 0, got -1 for SAST checker should return failed status when no PRs are found
--- FAIL: Test_SAST/Successful_SAST_checker_should_return_success_status_for_sonarcloud (0.00s)
~/checks/sast_test.go:319: Expected score 10, got -1 for Successful SAST checker should return success status for sonarcloud
```
We use our test helper: `ValidateTestReturn`, which provides much more actionable feedback when tests fail:
```
--- FAIL: …
```
=> :seedling: use ValidateTestReturn for SAST tests

.github/workflows/docker.yml
removing dependency
we use [tj-actions/changed-files](https://github.com/tj-actions/changed-files) to detect when only markdown files are changed
we use git diff, since the logic we need is simple and this reduces a dependency
NONE
You can see some example PRs of this working as expected:
* https://github.com/spencerschrock/actions-test/pull/5
* Confirms it shows non-md files (including `HEAD~1` works as expected on the whole PR and not just the last commit)
* https://github.com/spencerschrock/actions-test/pull/6
* Confirms it ignores a readme only PR
```release-note
NONE
```
=> :seedling: Use git diff instead of external action for changed files

checks/code_review_test.go
test cleanup, similar to #3872. 
This is the first step before hooking up the Code-Review probes to the evaluation code
we only checked the result score, which produces test failures without clear actionable feedback.
* We use our test helper: ValidateTestReturn, which provides much more actionable feedback when tests fail
* `ctrl.Finish()` is removed, as it's not needed after Go 1.14
* simplified err checking logic
* removed some unneeded lints
NONE
```release-note
NONE
```
=> :seedling: use ValidateTestReturn for Code-Review tests

checks/fileparser/listing.go, checks/fileparser/listing_test.go, checks/fuzzing_test.go, checks/permissions_test.go, checks/pinned_dependencies_test.go, checks/raw/binary_artifact_test.go, checks/raw/dangerous_workflow_test.go, checks/raw/fuzzing_test.go, checks/raw/github/packaging.go, checks/raw/gitlab/packaging.go, checks/raw/gitlab/packaging_test.go, checks/raw/pinned_dependencies_test.go, checks/raw/sast_test.go, checks/raw/security_policy_test.go, checks/sast_test.go, checks/security_policy_test.go, clients/git/client.go, clients/githubrepo/client.go, clients/githubrepo/tarball.go, clients/githubrepo/tarball_test.go, clients/gitlabrepo/client.go, clients/gitlabrepo/tarball.go, clients/gitlabrepo/tarball_e2e_test.go, clients/gitlabrepo/tarball_test.go, clients/localdir/client.go, clients/localdir/client_test.go, clients/mockclients/repo_client.go, clients/ossfuzz/client.go, clients/ossfuzz/client_test.go, clients/repo_client.go
breaking change
Checks which deal with file content must work with the whole file contents. Some usages don't require any data, some require only the first line, others require 1 KiB. This is inefficient, and leads to crashes. (See https://github.com/ossf/scorecard/issues/3831#issuecomment-1969978434)
- Clients will provide an `io.ReadCloser` when accessing a file, so the callers can use as much or as little data as they need.
- Existing callers of `GetFileContent` will use `io.ReadAll` to get the whole file contents, and then `Close` the Reader.
- Individual uses can be migrated in follow-up PRs.
- Cleaned up the tests to return `io.ReadClosers`.
- For tests that had strings, this uses a strings/bytes Reader, and an io.NopCloser
- For tests that previously opened and read files, the test …
=> :warning: Switch RepoClient file access to io.ReadCloser

docs/checks.md, docs/checks/internal/checks.yaml
docs
`.sigstore` bundles were added to Signed-Releases check by #3772 but docs weren't updated
Docs will reflect checks as they presently are in `main`
NA - [ ] Tests for the changes have been added (for bug fixes/features)
Fixes #3914
`checks.yaml` was edited and then `checks.md` was generated with `make generate-docs`, but as it's a trivial change there's no obvious evidence of the docs generation process (which is probably as things should be).
Yes:
```release-note
Document that `.sigstore` bundles are part of check for Signed-Releases
```
=> 📖docs: Add `.sigstore` bundles to Signed-Releases

clients/osv.go
bug fix / e2e test fix
Go stdlib vulns are reported (since osv scanner 1.4 i think)
Dont surface Go stdlib vulns. Whether or not a project is affected is a more complicated question than the version declared in the Go directive.
Fixes #3891
As well as our e2e tests:
https://github.com/ossf/scorecard/actions/runs/8177010131/job/22357695449#step:9:23142
```release-note
Go stdlib vulns are removed Vulnerabilities check output
```
=> :bug: ignore Go stdlib vulns

checks/branch_protection_test.go, checks/evaluation/branch_protection.go, checks/evaluation/branch_protection_test.go
bug fix
When run with a non-admin token, if we cant tell if PRs are required, we throw a warning.
> Warn: could not determine whether branch 'main' requires PRs to change code
Since requiring PRs is listed as potentially admin only data, not having the data is now DEBUG, not WARN.
> Debug: could not determine whether branch 'main' requires PRs to change code
https://github.com/ossf/scorecard/blob/90a3708b19883d176d84dc23e3b399b53f1ee1e9/docs/checks.md?plain=1#L113-L115
NONE
I got rid of the `switch` statement since the function is only called by 3 probes, and all of them want that behavior.
application as a result of this …
=> :bug: Branch-Protection: use debug message when unsure if PRs are required

checks/fileparser/listing.go, checks/raw/binary_artifact.go
bug fix
The whole file is read, even though we only use 1024 bytes when determining if a file is text or binary
Only up to the first 1024 bytes are read.
Part 1 of 2 to address #3831
```release-note
NONE
```
=> :bug: Limit Binary Artifact file reads to first 1024 bytes

checks/raw/sast.go
bug fix
Every file's whole contents are read. But for any file not called `pom.xml` this is wasted work.
* File content is only read once we know the file is called `pom.xml`
* Changed strings/bytes comparison functions to avoid allocating extra strings. 
(should be covered by existing tests)
Related to #3831 (SAST won't run locally, but this will hopefully save time in the cron)
```release-note
NONE
```
=> :bug: Avoid reading every file searching for sonar configs

clients/localdir/client.go
- ignore .git folder for localdir
Fixes #3908
```release-note
```
=> :bug: ignore .git folder for localdir

clients/osv.go, clients/vulnerabilities.go, cron/internal/worker/main.go, cron/k8s/worker.release.yaml
cron feature
All vuln requests go to osv.dev, which takes time. The vulnerabilities check is a bottleneck for our processing, and the cron has been struggling to complete recently.
the release test cron worker will try using the local DB option for osv-scanner, which you can read about here:
https://github.com/google/osv-scanner/blob/5151082e73f912d203776c0618f50ccef7866219/docs/offline-mode.md#local-database-option
NONE
```release-note
NONE
```
=> :sparkles: Add experimental local OSV mode for cron releasetest worker

.github/workflows/scorecard-analysis.yml
workflow update
Some version comments are out of date. 
One actions is out of date
* Adds version comments
* adds some explanatory comments
* deleted `repo_token` arg since it will use the GitHub token by default anyway
* Updates `github/codeql-action/upload-sarif` to the latest release, not sure why dependabot hasn't updated it.
The intent is to use this file as an example for the Scorecard Action repo (see https://github.com/ossf/scorecard-action/pull/1352) so it remains up-to-date through dependabot. Currently the workflow example from the Scorecard Action readme is out of date (see #3968) .
Where possible I tried to make the workflow match our [example](https://github.com/ossf/scorecard-action/blob/5fc43dc5154fb0ce7cc74b6264142ac8621bda1d/README.md#workflow-example), in terms of …
=> :seedling: polish scorecard workflow for use as example workflow

CONTRIBUTING.md, errors/errors.md
doc update
The doc has gotten stale
* Made some things more prominent (DCO has been a problem for some contributors in the past)
* Updated needed tool list
* Recommend people don't force push after reviews
* fix the make command table
* General cleanup / rephrasing
NONE
```release-note
```
=> :book: Review and update CONTRIBUTING.md

CONTRIBUTING.md
docs. 
reverts part of #4002. it turns out `public_repo` scope is needed for branch protection after all.
A few basic Go resources added for contributors unfamiliar with the language
```release-note
```
=> :book: revert PAT scope change and document Go resources

finding/finding.go, pkg/scorecard_test.go, pkg/testdata/probe1.json, probes/sastToolRunsOnAllCommits/impl_test.go
structured result cleanup which is technically a breaking change
Outcome is an int based type
Outcome is a string based type, which leads to better output format
Related to https://github.com/ossf/scorecard/issues/2928#issuecomment-2040433089
```release-note
NONE
```
=> :warning: Switch `Outcome` type to string

.github/workflows/codeql-analysis.yml, .github/workflows/scorecard-analysis.yml
I don't see Dependabot updating the `github/codeql` action in this particular action workflow, though it's updating a) other actions in this workflow and b) `github/codeql` in other actions.
Just a while speculation, but this is the only one with the whitespace between the actual name key and the uses? Just in case, firing this to see if the next Dependabot scan will start patching the codeql action in this file also. (and if so, it may infer a minor text checking bug in the upstream Dependabot algorithm?)
Should allow Dependabot to bump the codeql action in this file.
While here, I also bumped the actions manually to the latest v3.x series (which also includes Node 20, which should help eliminate any actions warnings about Node …
=> :seedling: Bump CodeQL Action version to 3.24.10 and remove whitespace

checks/evaluation/signed_releases.go, checks/evaluation/signed_releases_test.go
bug fix I guess?
After the Signed-Releases probe conversion (#3610), we started generating warns for not having a signature file, even though we had a provenance and were scoring a 10/10. This doesn't match what we did in v4.13.1, so correcting before the next release.
For `ossf/scorecard` for example:
```
"Warn: release artifact v4.13.1 not signed: <asset link>",
"Warn: release artifact v4.13.0 not signed: <asset link>",
"Warn: release artifact v4.12.0 not signed: <asset link>",
"Warn: release artifact v4.11.0 not signed: <asset link>",
"Warn: release artifact v4.10.5 not signed: <asset link>",
"Info: provenance for release artifact: multiple.intoto.jsonl: <asset link>",
"Info: provenance for release artifact: multiple.intoto.jsonl: <asset link>",
"Info: provenance for release artifact: …
```
=> :bug: Signed-Releases: dont warn about signatures if provenance present

checks/evaluation/signed_releases.go, probes/internal/utils/permissions/permissions.go
bug fix? This was an unintentional regression from v4.13.1
The detail used to (v4.13.1) say something like:
```
"topLevel 'pull-requests' permission set to 'read'"
```
But the conversion PR (#3816) replaced the individual scopes with a generic message:
```
"found token with 'read' permissions"
```
Read permissions findings use the same text helper function that write permission findings do, which matches what v4.13.1 did.
```
"topLevel 'pull-requests' permission set to 'read'"
```
NONE (preparing for release)
```release-note
NONE
```
=> :bug: Token-Permissions: use same text for read token details as write token details

options/options.go, pkg/probe.go, pkg/probe_test.go, pkg/scorecard.go, pkg/scorecard_result.go
feature and breaking change
`--format probe` is  gated behind `SCORECARD_EXPERIMENTAL=1`
- `--format probe` is no longer gated behind `SCORECARD_EXPERIMENTAL=1`
- Also delete finding and structured results formats as they weren't used
NONE (prepping for release)
```release-note
A new --format option "probe" is available.
```
=> :warning: remove experimental gate from `probe` format

checker/check_runner.go, checks/raw/shell_download_validate.go, checks/webhook.go, clients/githubrepo/repo.go, clients/gitlabrepo/repo.go, cmd/internal/scdiff/app/runner/runner.go, cmd/root.go, cron/config/config.go, cron/config/config_test.go, cron/data/iterator_test.go, errors/public.go, errors/public_test.go
fix linting expections around errors 
FIX Took care of the `//nolint:errname` directives while we're doing breaking changes.
uses directive to skip lint
does not skip lint, fixed the errors
Fixes #4033 
From OSSNA workshop
```release-note
NONE
```
=> :warning: errors in ErrXXX format

.github/dependabot.yml
ci update
- We get multiple PRs for the same update, across multiple PRs
- Go example:
- #4056
- #4058 
- Docker example:
- #4007
-  #4008
-  #4009
-  #4010
-  #4011
- #4012
-  #4013
-  #4014
We use dependabot's new beta feature: 
https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/
this does not group all Go updates, or all Docker updates. But for any single updates to these dependencies that exist in multiple lockfiles, they will all be updated in 1 PR.
NONE
```release-note
NONE
```
=> :seedling: Enable dependabot multi-directory updates

probes/releasesAreSigned/impl.go, probes/releasesAreSigned/impl_test.go, probes/releasesHaveProvenance/impl.go, probes/releasesHaveProvenance/impl_test.go
bug fix
if the 6th release had no assets, the lookback limit exit condition was being skipped. This led to scenarios where too many releases were being considered by the Signed-Releases check.
The lookback exit condition is now the first thing performed.
Fixes #4059
```release-note
Fixed a Signed-Releases bug where more releases were being analyzed than intended.
```
=> :bug: fix signed-releases lookback limit precedence

README.md
Docs update to remove announcement in readme
Survey link at top of readme
Survey link removed from readme
NONE
```release-note
NONE
```
=> 🌱 Remove survey

checks/binary_artifact_test.go, checks/license_test.go
Updates tests to follow best practices (and corrects previous PR #4078 )
binary_analysis and license check tests currently use localDirRepo instead of gomock
binary_analysis does not utilize scut (license test already uses scut and does not need modification)
- No behavior change anticipated
- binary_analysis and license check tests updated to use gomock
- ListFiles and GetFileReader mocked for both
- ListLicenses mocked for license check (replicates localDirRepo by throwing Unsupported Feature error)
- binary_analysis updated to use scut
- test cases modified to include some logging information
Fixes #4032
=> 🌱  Update Binary-Artifacts and License checks

checks/code_review_test.go, checks/raw/code_review.go, checks/raw/code_review_test.go
bug fix
The old regex used `\w` which only allowed `[0-9A-Za-z_]`, however most projects use full URLs with phabricator (e.g.
`https://reviews.foo.org/D###`). This led to errors parsing the revisions, where `https` was seen as the revision (the portion which matched `\w`), leading to an underreporting of code review practices as everything was considered 1 changeset.
```
go run main.go --repo freebsd/freebsd-src --checks Code-Review --format json --show-details | jq
{
"date": "2024-05-06T14:23:32-07:00",
"repo": {
"name": "github.com/freebsd/freebsd-src",
"commit": "a7db82cfd940431037e748280825931a46ed2d12"
},
"scorecard": {
"version": "devel",
"commit": "unknown"
},
"score": 0.0,
"checks": [
{
"details": null,
"score": 0,
"reason": "Found 1/14 approved changesets -- score normalized to …
```
=> :bug: Code-Review: change phabricator regex to allow URLs

cron/internal/cii/main.go
bug fix 
We are getting connection reset requests from bestpractices.dev and 429 errors from our GCS bucket for too many writes. 
bestpractices.dev [has a limit of 1 QPS](https://github.com/coreinfrastructure/best-practices-badge/blob/main/docs/api.md)
GCS has a [limit of 1000 QPS](https://cloud.google.com/storage/docs/request-rate)
Use the lower limit of 1 QPS limit for bestpractices.dev when populating the cron data.
Each page has 30 projects, so 30 QPS is below the GCS limit.
The construct was taken from https://go.dev/wiki/RateLimiting which "works well for rates up to tens of operations per second."
Related to #4037 (but may not fix it yet)
(In particular, describe what changes users …
=> :seedling: implement 1 QPS rate limiting for cron best practices worker.

cron/internal/cii/main.go
cron fix
We still run into the 429 GCS responses due to the lower limits on writes to the same object. All of the projects without a `repo_url` are being mapped to the same object `/result.json` and leading to rate limiting.
"Maximum rate of writes to the same object name: One write per second"
https://cloud.google.com/storage/quotas#objects
We don't try to write anything for projects without an associated `repo_url`
Follow up of #4090 , related to #4037
```release-note
NONE
```
=> :seedling: cron: don't write any bestpractices data for projects without repo URL

checks/raw/binary_artifact.go, checks/raw/binary_artifact_test.go, checks/testdata/binaryartifacts/workflows/verify-new-gradle-name.yaml, go.mod, go.sum
bug fix
`gradle/wrapper-validation-action` must be present and pinned to a hash
* detects `gradle/actions/wrapper-validation`
* From gradle/wrapper-validation-action's readme: "As of v3 this action has been superceded by gradle/actions/wrapper-validation"
* Also support actions pinned to a hash.
Fixes #2477
Fixes #2357
Related to https://github.com/ossf/scorecard-action/issues/782#issuecomment-2101915990, but requires a release (which was going to be cut today anyway)
```release-note
Binary-Artifacts check now supports the new gradle wrapper validation action, and can be …
```
=> :bug: Support renamed gradle verification action and callers which pin to hash

attestor/command/check.go, checker/check_request.go, checker/client.go, checker/client_test.go, cmd/internal/scdiff/app/runner/runner.go, cmd/root.go, cmd/serve.go, cron/internal/worker/main.go, dependencydiff/dependencydiff.go, e2e/attestor_policy_test.go, pkg/scorecard.go, pkg/scorecard_e2e_test.go, pkg/scorecard_test.go
Pass ProjectPackageClient to `RunScorecard`. This will allow raw data collection/probes to make use of the new interface.
=> :warning: ProjectPackageClient: pass client to RunScorecard

docs/repositories.md
ref: https://github.com/ossf/scorecard/issues/4073, https://github.com/ossf/scorecard/issues/3204, https://github.com/UlisesGascon/openssf-scorecard-monitor/pull/74
```release-note
NONE
```
=> 📖 Add repository guidelines e.g., for project donations

pkg/scorecard_test.go
It makes the tests more resilient against differences in the environment in which scorecard is built.
Tests assume they are ran in an environment where the application version is not known/set.
Tests make no assumptions about version fields anymore
NONE
```release-note
NONE
```
=> :seedling: avoid assumptions about versions in tests

checks/raw/dependency_update_tool.go, checks/raw/dependency_update_tool_test.go, docs/checks/dependencyupdatetool/README.md
Recognize [scala-steward](https://github.com/scala-steward-org/scala-steward) as dependency update tool
Repositories that are configured to use scala-steward score '0' on the 'Dependency-Update-Tool' check
Repositories that are configured to use scala-steward score '10' on the 'Dependency-Update-Tool' check
NONE
```release-note
Recognize scala-steward as dependency update tool
```
=> :sparkles: Recognize scala-steward as dependency update tool

checks/raw/pinned_dependencies.go, checks/raw/pinned_dependencies_test.go
Bug fix
As both the check for unpinned dependencies in GitHub Actions and the check for unpinned Docker dependencies contribute to d.Dependencies, the loop that created remediations for Docker dependencies would also create try to create Docker remediations for the unpinned GitHub Actions dependencies.
This could get really slow, especially when scanning a repo with many GitHub Actions such as https://github.com/apache/beam.
Only create Docker remediations for Docker dependencies (and similar for GitHub workflow remediations)
NONE
```release-note
Improve Pinned-Dependencies …
```
=> :bug: fix Docker remediations for unpinned GHA dependencies

pkg/scorecard.go, pkg/scorecard_test.go, pkg/testdata/.github/scorecard.yml, pkg/testdata/.scorecard.yml, pkg/testdata/scorecard.yml
Look for maintainer annotation config files in multiple locations: `scorecard.yml`, `.scorecard.yml`, `.github/scorecard.yml`. Scorecard uses the first one it finds regardless of whether it's valid.
Only look for `scorecard.yml` and don't apply maintainer annotation if that file doesn't exist.
Addresses #4048
=> 🌱 maintainer annotations: search for config

cmd/internal/scdiff/app/format/format.go, pkg/json.go, pkg/json_test.go, pkg/scorecard_result.go
breaking change
Some of the `AsX` functions take pointers (`AsProbe`), some take structs (`AsString`, `AsJSON2`)
All three `AsX` functions which have option structs, take pointers.
One item from #4048 
```release-note
NONE
```
=> :warning: Make all ScorecardResult format options pointers

Dockerfile
- Move the static cgr.dev base image as it has less foot print and zero vuln.
cgr.dev 
```
➜  scorecard git:(main) ✗ grype docker.io/library/scorecard
✔ Vulnerability DB                [no update available]
✔ Loaded image                                                                                                    index.docker.io/library/scorecard:latest
✔ Parsed image                                                                     sha256:9dc0b3a5edf538cc6e7cb559a037a4076ac68f1fca0010049da9f6111addd339
✔ Cataloged contents                                                                      4e28f40763377e1ffe75bfd4400e924ef62cf04db7b5b136338a932569afa3c8
├── ✔ Packages                        [121 packages]
├── ✔ File digests                    [397 files]
├── ✔ File metadata …
```
=> ✨ move to cgr base image

clients/osv.go
feature
only print a error string for osv-scanner panic error
also print the stacktrace
Updates #4171 
```release-note
NONE
```
=> :seedling: add stack info to osv-scanner error

cmd/internal/scdiff/app/runner/runner.go, cmd/internal/scdiff/app/runner/runner_test.go
- uses older `pkg.RunScorecard`
- uses new `pkg.Run`
Follow up of #3717 
```release-note
NONE
```
=> :seedling: Use new entrypoint for scdiff

.github/dependabot.yml
This is apparently required with the current implementation of multi dir PRs.
ci update
- without groups dependabot only updates the deps in the first declared directory, a known bug reported upstream. For example in #4160, I had to bump the other 7 occurrences in a manual fix.
- dependabot actually groups updates. Examples:
- https://github.com/spencerschrock/actions-test/pull/15
- https://github.com/spencerschrock/actions-test/pull/16
NONE
```release-note
NONE
```
=> :seedling: fix dependabot config to group docker images

SECURITY.md
The [current security policy](https://github.com/ossf/scorecard/blob/5f7cea363724ba03923eb07bdb4e6fa3b2927c15/SECURITY.md) was last updated three years and appears to be boilerplate from Google open source projects.
This updated security policy is specific to the OpenSSF Scorecard project and considers:
- the previously-written policy
- the inherited [SECURITY.md from ossf/.github](https://github.com/ossf/.github/blob/692a363fd99ad0ea50a9512795d53a24e1754d9c/SECURITY.md)
- the LF vulnerability disclosure process for projects: https://www.linuxfoundation.org/security
- the Cisco open source project [SECURITY.md](https://github.com/cisco-ospo/oss-template/blob/main/SECURITY.md), which was itself inspired by the [Wayfair OSS project …
=> :book: Update security policy to be specific to OpenSSF Scorecard

cron/internal/worker/main.go
cron update
Uses the old `pkg.RunScorecard`
Uses the new `pkg.Run`
There are further simplifications that are possible, but leaving for later to keep this PR small.
Follow up of #3717 
```release-note
NONE
```
=> :seedling: Use new entrypoint for cron worker

attestor/command/check.go, cmd/serve.go, e2e/attestor_policy_test.go, pkg/scorecard.go, pkg/scorecard_e2e_test.go, pkg/scorecard_test.go
api cleanup. I grouped these separately as they're lower impact
Use `pkg.RunScorecard`
Use `pkg.Run`
Follow up of #3717 
```release-note
NONE
```
=> :seedling: Migrate other RunScorecard callers

cmd/root.go, pkg/scorecard.go, pkg/scorecard_test.go
refactor
- the CLI uses the old `pkg.ExperimentalRunProbes` function
- deleted `ExperimentalRunProbes`  (not a breaking change since marked experimental
- CLI uses the new `pkg.Run` entrypoint.
Followup to #3717 
```release-note
NONE
```
=> :seedling: Use new Scorecard entrypoint for CLI

cmd/internal/scdiff/app/runner/runner_test.go, options/flags.go, options/flags_test.go, options/options.go, pkg/scorecard.go
feature enablement
Looking for maintainer annotations is gated behind the SCORECARD_EXPERIMENTAL flag
The feature is no longer gated
NONE
```release-note
NONE
```
=> :sparkles: remove experimental gate on maintainer annotation parsing

docs/probes.md, probes/codeApproved/def.yml, probes/sastToolRunsOnAllCommits/def.yml
doc change
The motivation behind the probes won't change, but I want to reserve the ability to change the probe to return 1 finding per changeset. We've received feedback that being able to see which individual change passes or doesn't pass is helpful (https://github.com/ossf/scorecard/issues/4237#issuecomment-2227104276).
NONE
```release-note
NONE
```
=> :book: mark codeApproved and sastToolRunsOnAllCommits as experimental

clients/githubrepo/statuses_e2e_test.go
disabling one e2e test
The e2e test is blocking PRs, see #4267
The test is disabled and a TODO issue was filed #4273 
NONE
```release-note
NONE
```
=> :seedling: skip failing GitHub status e2e test temporarily

probes/internal/utils/branchprotection/branchProtection.go
Fix typo in branch protections details message.
Messages such as the following are emitted in scorecard reports:
```text
Warn: 'stale review dismissal' is disable on branch 'main'
```
Grammar in message is fixed to use the correct text:
```diff
- Warn: 'stale review dismissal' is disable on branch 'main'
+ Warn: 'stale review dismissal' is disabled on branch 'main'
```
NONE
```release-note
Fix typo in branch protections details.
```
=> :book: Fix typo in branch protections details

clients/githubrepo/releases.go
This PR introduces a feature change for the release links generated by the following command: 
`go run main.go --repo ossf/scorecard --checks Signed-Releases --format json --show-details | jq`
When running command to view releases, links display API format
When running command to view releases, links display non-API format
Fixes #4030 
Did not add test for changes but ran current test 
```release-note
NONE
```
=> :sparkles: Switched API release links to non-API release links

.github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/gitlab.yml, .github/workflows/goreleaser.yaml, .github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/publishimage.yml, .github/workflows/scdiff.yml, .github/workflows/slsa-goreleaser.yml, Dockerfile, attestor/Dockerfile, clients/githubrepo/roundtripper/tokens/server/Dockerfile, cron/internal/bq/Dockerfile, cron/internal/cii/Dockerfile, cron/internal/controller/Dockerfile, cron/internal/webhook/Dockerfile, cron/internal/worker/Dockerfile, tools/go.mod
Go version bump
Our tooling uses Go 1.22.x (see #3859)
Use Go 1.23.X for our CI and dockerfiles.
* Our minimum Go version in our `go.mod` is unchanged
* I did bump the tools/go.mod proactively incase any of our tools switch to requiring 1.23, this makes it so we dependabot PRs don't fail later
```release-note
NONE
```
=> :seedling: Update Go toolchain to 1.23

clients/azuredevops/repo.go, clients/azuredevops/repo_test.go
Initial part of feature #4177.
Mainly to see if the overall feature would be accepted and if I am following the contribution guidelines correctly, before I put a lot of work into the rest of the implementation.
N/A
Azure DevOps URLs can now be parsed
Initial part of #4177 
```release-note
NONE
```
=> :seedling: add support for parsing azure devops urls

CONTRIBUTING.md, clients/gitlabrepo/repo_test.go, go.mod
go directive bump
Go 1.21 is the minimum version required to compile Scorecard or use it as a library.
Go 1.22.0 is now the minimum version. 
At least one of our dependencies now requires 1.22. Additionally, with the Go 1.23 release, Go 1.21 is no longer supported. Due to the [loopvar changes](https://go.dev/doc/go1.22#language), I'm submitting this as a standalone change.
Unblocks #4319 
Note this is different from #3859 or #4300 which update our toolchain versions.
```release-note
Go 1.22.0 is now required to build Scorecard or use it as a library.
```
=> :seedling: Require minimum version of Go 1.22.0

docs/checks.md, docs/checks/internal/checks.yaml, probes/testsRunInCI/impl.go, probes/testsRunInCI/impl_test.go
It addresses #4210
It does not count tests run by Woodpecker
e.g. `CI-Tests` score of woodpecker's own main repo is 8/10
it detects woodpecker and score the tests acordingly
e.g. `CI-Tests` score of woodpecker's own main repo is 10/10
`scorecard --repo=https://github.com/woodpecker-ci/woodpecker `:
Fixes #4210
no
=> ✨ Add woodpecker as known CI

.gitignore
=> :ghost: git ignore vendor folder

.github/workflows/scdiff.yml
workflow change
Any previous contributor can run the `scdiff` workflow
Only members of the `ossf` GitHub org can run the `scdiff` workflow. 
Previously we matched GitHub's "Require approval for first-time
contributors", which represents a minor barrier for attackers
(e.g. submitting a typo fix). Project members should ensure their
visibility in the "ossf" GitHub org is "Public" to be able to run
scdiff.
```release-note
NONE
```
=> :seedling: Tighten restrictions for running `scdiff` workflow 

checks/raw/fuzzing.go, checks/raw/fuzzing_test.go, clients/languages.go, docs/checks.md, docs/checks/internal/checks.yaml, internal/fuzzers/fuzzers.go
Use the presence of property-based tests to detect the use of fuzzing in Erlang code.
There is no support for fuzz detection for Erlang.
Adds Erlang as a client language.
Scans for the import of property-based test frameworks to detect the use of fuzzing in Erlang
NONE
~For the next section, I think there are no user-facing changes, but a previous PR for Haskell #2843 wrote a release note~
```release-note
Support detection of fuzzing in Erlang through the import of property-based testing modules
```
=> :sparkles: Add Erlang as a language

checker/client.go, clients/azuredevopsrepo/branches.go, clients/azuredevopsrepo/branches_test.go, clients/azuredevopsrepo/client.go, clients/azuredevopsrepo/client_test.go, clients/azuredevopsrepo/commits.go, clients/azuredevopsrepo/repo.go, clients/azuredevopsrepo/repo_test.go, cmd/root.go, go.mod, go.sum, pkg/scorecard/scorecard.go
This PR introduces early experimental support for Azure DevOps. It's the MVP for a scorecard scan to complete without panicing.
No Support for Azure DevOps repository scanning
This is a followup from #4178, and the next step for #4177. It is the minimal client implementation for Azure DevOps repository support.
I'd like to get feedback at this stage, before I implement the remainder of the client.
Continued work on #4177 
This change is currenltly gated behind the `SCORECARD_EXPERIMENTAL` environment variable, same as the initial GitLab client was.
```release-note
Initial …
```
=> ✨ Initial experimental Azure DevOps client

clients/azuredevopsrepo/audit.go, clients/azuredevopsrepo/audit_test.go, clients/azuredevopsrepo/client.go, clients/azuredevopsrepo/commits.go, clients/azuredevopsrepo/work_items.go, clients/azuredevopsrepo/work_items_test.go
`ListIssues` and `GetCreatedAt` throw an unsupported error
`ListIssues` and `GetCreatedAt` have implementations
Next step of https://github.com/ossf/scorecard/issues/4177
Azure DevOps doesn't have an official API to retrieve user permissions for a project or a repository. As a stopgap solution, I've defaulted all issue and comment authors to `RepoAssociationMember`. This is probably a good minimum bar.
The audit log is the best way to retrieve the repository creation date, but this may not be enabled. So I am using the first repository commit as a fallback value. …
=> :sparkles: implement `ListIssues` and `GetCreatedAt` for Azure DevOps

Makefile, clients/azuredevopsrepo/azure_devops_suite_test.go, clients/azuredevopsrepo/client.go, clients/azuredevopsrepo/search.go, clients/azuredevopsrepo/search_e2e_test.go, clients/azuredevopsrepo/search_test.go
`Search` throws an unsupported error
`Search` has an implementation for Azure DevOps
Next step of https://github.com/ossf/scorecard/issues/4177
This does not appear to be used in a current check. However, I verified the functionality by writing an E2E test. Unfortunately, I can't check in the E2E test as we don't have an E2E repository configured for Scorecard.
```release-note
implement `Search` for Azure DevOps
```
=> ✨ implement `Search` for Azure DevOps

clients/azuredevopsrepo/client.go, clients/azuredevopsrepo/languages.go, clients/azuredevopsrepo/languages_test.go, clients/azuredevopsrepo/zip.go
`ListProgrammingLanguages` throws an unsupported error for Azure DevOps
Next step of #4177
I also fixed a bug in the zip implementation when testing the `Fuzzing` check
```release-note
add `ListProgrammingLanguages` for Azure DevOps
```
=> sparkles: add `ListProgrammingLanguages` for Azure DevOps

checks/contributors_test.go, checks/evaluation/contributors.go
cleanup for scdiff
The orgs are printed in map iteration order (random), and there's a lot of duplication in the text:
```
Info: CatalystCode contributor org/company found, microsoft corporation contributor org/company found,
python-trio contributor org/company found, googlers contributor org/company found,
Azure-Samples contributor org/company found, microsoft contributor org/company found,
syncweek-react-aad contributor org/company found, webhintio contributor org/company found,
IPPETAD contributor org/company found, projectkudu contributor org/company found,
Azure contributor org/company found,
```
specifically with iteration order, this creates noisy `scdiff` diffs where the only difference is the order:
```diff
-                                                       "eclipse",
+ …
```
=> :seedling: sort organizations in Contributors detail string

clients/azuredevopsrepo/client.go, clients/azuredevopsrepo/contributors.go, clients/azuredevopsrepo/contributors_test.go, go.mod
Feature
`LisContributors` throws an unsupported error on Azure DevOps
`LisContributors` is implemented for Azure DevOps
Next step of https://github.com/ossf/scorecard/issues/4177
I am a little unsure what to put for `Companies` or `Organizations`. For now, I've defaulted to the current Azure DevOps organization.
```release-note
implement `ListContributors` for Azure DevOps
```
=> :sparkles: implement `ListContributors` for Azure DevOps

clients/gitlabrepo/branches.go, clients/gitlabrepo/branches_test.go, clients/gitlabrepo/checkruns.go, clients/gitlabrepo/checkruns_test.go, clients/gitlabrepo/client.go, clients/gitlabrepo/client_e2e_test.go, clients/gitlabrepo/client_test.go, clients/gitlabrepo/commits.go, clients/gitlabrepo/commits_test.go, clients/gitlabrepo/contributors.go, clients/gitlabrepo/contributors_test.go, clients/gitlabrepo/issues.go, clients/gitlabrepo/issues_test.go, clients/gitlabrepo/languages.go, clients/gitlabrepo/licenses.go, clients/gitlabrepo/project.go, clients/gitlabrepo/releases.go, clients/gitlabrepo/repo.go, clients/gitlabrepo/search.go, clients/gitlabrepo/searchCommits.go, clients/gitlabrepo/search_test.go, clients/gitlabrepo/statuses.go, clients/gitlabrepo/statuses_test.go, clients/gitlabrepo/tarball.go, clients/gitlabrepo/webhook.go, clients/gitlabrepo/webhook_test.go, clients/gitlabrepo/workflows.go, go.mod, go.sum
dep update
We used the `github.com/xanzy/go-gitlab` package.
The package is [deprecated](https://github.com/xanzy/go-gitlab/commit/68add0327e425160bc0933fb3fae4cdfaec950d5), in favor of the GitLab ran one: 
https://gitlab.com/gitlab-org/api/client-go
Related to #4451 
```release-note
NONE
```
=> :seedling: migrate gitlab client import

clients/azuredevopsrepo/contributors_test.go
test fix follow up of #4437
The intention for the test was always to sort, but the wrong sort function was used. This led to an unsorted list, which was dependent on map iteration order, leading to flaky unit tests. This was reproducible with `go test` when passing a large `--count` option.
The contributors are sorted correctly.
See https://github.com/ossf/scorecard/actions/runs/12300084637/job/34327383076#step:9:26
```
--- FAIL: Test_listContributors (0.00s)
--- FAIL: Test_listContributors/multiple_contributors (0.00s)
contributors_test.go:126: contributorsHandler.setup() mismatch (-want +got):
[]clients.User{
{
- 		Login:            "test@example.com",
+ 		Login:            "test2@example.com",
Companies:        {"testOrg"},
Organizations:    nil,
- 		NumContributions: 1,
+ …
```
=> :seedling: fix sorting contributors before comparing in test

governance/meetings/2021.md, governance/meetings/2022.md, governance/meetings/2023.md, governance/meetings/2024.md
Discussed in today's meeting to clean up our meeting notes, as we now have 4 years accumulated.
cc: @spencerschrock @raghavkaul 
```release-note
NONE
```
=> 📖 governance: Add meeting note archives from 2021 through 2024

clients/githubrepo/roundtripper/tokens/accessor.go, clients/githubrepo/roundtripper/tokens/accessor_test.go
Print a warning if several GitHub Access Tokens with different values are found.
Scorecard ignores any GitHub PAT environment variables after the first one it finds.
Scorecards checks all possible PAT env vars and prints a warning if their values differ. It still uses the first one it finds, such that the behaviour is non-breaking.
Fixes #4475
The local tests failed already for a clean checkout of the main branch. I am hoping for the CI to sucessfully run them for me.
```release-note
Print a warning if several GitHub PAT environment variables with different values are set.
```
=> :seedling: Logging a warning if readGitHubTokens finds several values which clash.

.goreleaser.yml, tools/go.mod
release config
- `scorecard_5.0.0_darwin_amd64`
- `scorecard_5.0.0_darwin_arm64`
- `scorecard_5.0.0_linux_amd64`
- `scorecard_5.0.0_linux_arm64`
- `scorecard_5.0.0_windows_amd64.exe`
- `scorecard_5.0.0_windows_arm64.exe`
There will be a single binary called `scorecard`, or for windows `scorecard.exe`
Fixes #4517 
```release-note
Scorecard binary name is now consistent across all release platforms
```
=> :seedling: remove OS and Arch info from scorecard release binary name

internal/gitfile/gitfile.go
bug fix from #4474 
Each call to `ListFiles` would walk the HEAD commit's tree, but `go-git` is not thread-safe.
So the old method would lead to race conditions when multiple checks called `ListFiles` at the same time. This slipped by my development but was reproducible when built with `-race`:
```shell
go build -race && ./scorecard --repo ossf-tests/scorecard-check-license-e2e --file-mode git
...
fatal error: concurrent map read and map write
...
==================
WARNING: DATA RACE
Write at 0x00c000222f30 by goroutine 67:
runtime.mapassign()
~/sdk/go1.24.0/src/internal/runtime/maps/runtime_swiss.go:191 +0x0
< omitted > 
github.com/go-git/go-git/v5.(*Repository).Head()
~/go/pkg/mod/github.com/go-git/go-git/v5@v5.13.2/repository.go:1497 +0x1ee …
```
=> :bug: save file names during gitfile handler setup to avoid data race

MAINTAINERS.md
📖 MAINTAINERS: Reflect active project contributors and affiliations
***To all emeritus contributors, thank you immensely for making this project what it is today!***
@ossf/scorecard-admins — I'm presenting this PR ahead of making any changes to the GitHub teams.
@azeemshaikh38 @laurentsimon @naveensrinivasan @olivekl — explicitly tagging you as well.
If there are any questions, feel free to ask here or privately!
```release-note
NONE
```
=> 📖 MAINTAINERS: Reflect active project contributors and affiliations

go.mod, go.sum, options/flags.go, options/options.go, pkg/scorecard/json.go, pkg/scorecard/scorecard_result.go, pkg/scorecard/statement.go, pkg/scorecard/statement_test.go
Feature
Currently scorecard does not support generating in-toto statements.
This PR adds support to generate the scorecard output in an in-toto statement. It introduces a new possible value for the format flag: `--format=intoto`.
**The predicate format is open to discussion**, right now is just a reformated version of `JSONScorecardResultV2` with the repo removed (as it is now in the statement's subject section):
```
scorecard --format=intoto --checks=Maintained --repo=github.com/protobom/protobom
```
```json
{
"type": "https://in-toto.io/Statement/v1",
"subject": [
{
"name": "github.com/protobom/protobom",
"uri": "git+https://github.com/protobom/protobom@0aa9659c6dc7354c5c60945f44b35bb2ed457857",
"digest": {
"gitCommit": "0aa9659c6dc7354c5c60945f44b35bb2ed457857"
}
}
],
"predicate_type": …
```
=> :sparkles: Support results output as in-toto statement

.github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/gitlab.yml, .github/workflows/goreleaser.yaml, .github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/publishimage.yml, .github/workflows/scdiff.yml, .github/workflows/slsa-goreleaser.yml, CONTRIBUTING.md, go.mod, tools/go.mod
go directive bump
Go 1.22.10 is the minimum version required to compile Scorecard or use it as a library.
Workflows use Go 1.23
Go 1.23.0 is now the minimum version. 
Workflows use Go 1.24
At least one of our dependencies now requires 1.23 (see #4544, which is why the build is failing). Additionally, with the Go 1.24 release, Go 1.22 is no longer supported.
NONE
```release-note
Go 1.23.0 is now required to build Scorecard or use it as a library.
```
=> :seedling: Require minimum version of Go 1.23.0

README.md
📖 Fix GitHub Actions badges in README.md
=> 📖 Fix GitHub Actions badges in README.md

pkg/scorecard/sarif.go, pkg/scorecard/sarif_test.go, pkg/scorecard/testdata/check3.sarif
Currently if a filename contains a `%` character it is passed through in plain text in the result in `sarif` file. If the location is later parsed again, an URL-decoder will stumble upon it as it tries decode the escape sequence.
As an example see the following `scorecard-action` where the SARIF upload failed: https://github.com/Quantco/copier-template-python-open-source/actions/runs/14924466359
`%` characters are escaped in the SARIF output.
NONE
```release-note
NONE
```
=> 🐛 Ensure % character in the artifactLocation in sarif output are escaped

clients/cii_blob_client.go, cron/data/blob.go, go.mod
bug fix
https://github.com/ossf/scorecard/issues/4626#issuecomment-2902376370
Our indirect GCS dependency began wrapping an object not found error in v1.51.0, which broke our calls to `bucket.Exists`. While gocloud.dev was updated for the comparison (v0.41.0), it also requires Go 1.24 which we can't upgrade to yet due to our Go version policy.
We check for the wrapped error ourselves, so we don't need to upgrade to Go 1.24 yet.
Fixes #4626
Tested using the local cron environment: https://github.com/ossf/scorecard/tree/e51d93e9022b61976836d584f4e1de0564235860/cron/internal/emulator
application as a result of this pull …
=> :bug: add stopgap check for GCS error that is now wrapped

cron/internal/webhook/main.go
cron fix
The webhook is used to promote latest (staging) to stable (production) for the weekly cron. This process previously promoted `gcr.io/openssf/scorecard` too. We aren't hosting the base scorecard image on GAR, but rather GHCR, and Cloud Build was disabled for that image already. This causes the webhook call to return a 500 error as the container doesn't exist for the given commit.
`gcr.io/openssf/scorecard` isn't promoted as part of the transfer
Relates to #4626 
```release-note
NONE
```
=> :seedling: remove scorecard image from Google AR promotion

checks/raw/pinned_dependencies.go, checks/raw/pinned_dependencies_test.go, checks/raw/testdata/Dockerfile-from-scratch
Bug fix.
A multi-stage Dockerfile containing a stage based off of a named stage, in turn created from scratch is marked as being unpinned.
<details>
<summary>Full example image that is currently failing</summary>
```dockerfile
FROM --platform=${BUILDPLATFORM} node:22.16.0@sha256:0b5b940c21ab03353de9042f9166c75bcfc53c4cd0508c7fd88576646adbf875 AS web-builder
WORKDIR /src
COPY .yarnrc.yml package.json yarn.lock .
COPY .yarn .yarn
RUN yarn install
COPY tsconfig.json vite.config.ts .
COPY web web
ARG CUPDATE_VERSION="development build"
RUN VITE_CUPDATE_VERSION="${CUPDATE_VERSION}" yarn build
FROM --platform=${BUILDPLATFORM} golang:1.24.3@sha256:86b4cff66e04d41821a17cea30c1031ed53e2635e2be99ae0b4a7d69336b5063 AS builder
WORKDIR /src
ENV GOTOOLCHAIN=auto
COPY go.mod go.sum .
RUN go mod download …
```
=> :bug: Fix pinned check for Dockerfiles with from scratch

checks/raw/fuzzing.go, checks/raw/fuzzing_test.go
Fuzzing supports `.js` and `.ts` files but not `.jsx` and `.tsx` files.
Adds support for more JavaScript file types.
Fixes #4663 
```release-note
```
=> :sparkles: feat(jsx): support fuzzing in jsx files #4663

checks/raw/security_policy.go, checks/raw/security_policy_test.go
I think this counts as a feature (a micro feature).
Some security policy documents may include an email address partially
obfuscated in the form security[at]example.org or, especially in
markdown, escaped like security\\[at\\]example.org.
This change updates the regex to recognize those two forms, with the
tests expanded to cover those cases as well.
Only emails of the form security@example.org are recognized.
Emails of the form security[at]example.org and security\[at\]example.org are recognized.
NONE
This depends first on https://github.com/ossf/scorecard/pull/4674 being merged.
```release-note
Start recognizing escaped emails in security policy documents
```
=> :sparkles: recognize escaped emails in security policy documents

.github/workflows/goreleaser.yaml, .github/workflows/slsa-goreleaser.yml
This pull request pins all GitHub Actions in workflow files to specific commit hashes to improve security and ensure reproducible builds. kind of change does this PR introduce?
This pull request pins all GitHub Actions in workflow files to specific commit hashes to improve security and ensure reproducible builds. is the current behavior?
This pull request pins all GitHub Actions in workflow files to specific commit hashes to improve security and ensure reproducible builds. is the new behavior (if this is a feature change)?**
application as a result of this pull …
=> :seedling: security: pin GitHub Actions to commit hashes

checks/fileparser/github_workflow.go, checks/fileparser/github_workflow_test.go, checks/testdata/.github/workflows/spicedb-release.yaml
Currently, the Go `JobMatcher` requires both the `setup-go` and `goreleaser` actions to be used to consider the project to use and automated releaser. Some users have adopted other actions that install Go and still use the `goreleaser` action in which case Scorecard will not see the `goreleaser` action.
This PR removes the requirement that users _must_ use the `setup-go` action to Scorecard recognizing `goreleaser`.
Fixes https://github.com/ossf/scorecard/issues/4617
```release-note
Fix bug in parsing workflow files.
```
=> 🐛 remove setup-go requirement for Packaging with goreleaser

checks/signed_releases_test.go, docs/checks.md, docs/checks/internal/checks.yaml, probes/releasesAreSigned/impl.go
The offical [sigstore/gh-action-sigstore-python](https://github.com/sigstore/gh-action-sigstore-python) GitHub Action outputs signatures with a `.sigstore.json` suffix that is not detected by Signed-Releases.
This change updates Signed-Releases to support the .sigstore.json suffix, adds a new test, and updates the documentation.
Bug fix
Signed-Releases does not detect signatures in GitHub release artifacts with the `.sigstore.json` suffix.
Signed-Releases detects signatures in GitHub release artifacts with the ".sigstore.json" suffix.
Fixes #4727.
Yes
```release-note
Signed-Releases now detects signatures ending with `.sigstore.json`
```
=> 🐛 Update Signed-Releases to support .sigstore.json signatures

MAINTAINERS.md
The @ossf/scorecard-maintainers would like to nominate Adam Korczynski (@AdamKorcz) to ***join the project as a maintainer***!
Adam (and ADA Logics) have made outsized contributions to the Scorecard project, including the [Structured Results](https://openssf.org/blog/2024/04/17/beyond-scores-with-openssf-scorecard-granular-structured-results-for-custom-policy-enforcement/) feature, analysis and remediation of project fuzzing results (via contributions and in [OSS-Fuzz](https://google.github.io/oss-fuzz/)), and conducting our soon-to-be released first security audit.
As of 2025-10-02, Adam has:
- contributed [45 pull requests](https://github.com/ossf/scorecard/pulls?q=is%3Apr+is%3Amerged+author%3AAdamKorcz+created%3A%3C%3D2025-10-02)
- participated in [15 issue …
=> :seedling: MAINTAINERS: Add Adam Korczynski (AdamKorcz), ADA Logics
